{{{d`f1`o1`qfa`dsd`du`\[Pi]im`p1, d`f1`o1`qfa`dsd`dd`\[Eta]`p1, 
   d`f1`o1`qfa`dsd`dd`\[Pi]i0`p1, d`f1`o1`qfa`dsd`dd`etas`p1, 
   d`f1`o1`qfa`dsd`ds`\[CapitalKappa]i0`p1, 
   s`f1`o1`qfa`sdd`su`\[CapitalKappa]im`p1, 
   s`f1`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p1, s`f1`o1`qfa`sdd`ss`\[Eta]`p1, 
   s`f1`o1`qfa`sdd`ss`etas`p1, u`f1`o1`qfa`dsd`du`\[Pi]im`p2, 
   d`f1`o1`qfa`dsd`dd`\[Eta]`p2, d`f1`o1`qfa`dsd`dd`\[Pi]i0`p2, 
   d`f1`o1`qfa`dsd`dd`etas`p2, s`f1`o1`qfa`dsd`ds`\[CapitalKappa]i0`p2, 
   u`f1`o1`qfa`sdd`su`\[CapitalKappa]im`p2, 
   d`f1`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p2, s`f1`o1`qfa`sdd`ss`\[Eta]`p2, 
   s`f1`o1`qfa`sdd`ss`etas`p2, d`f1`o1`qfb`dds`dd`\[Eta]`p1, 
   d`f1`o1`qfb`dds`dd`\[Pi]i0`p1, d`f1`o1`qfb`dds`dd`etas`p1, 
   d`f1`o1`qfb`dsd`ds`\[CapitalKappa]i0`p1, 
   s`f1`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p1, d`f1`o1`qfb`dds`dd`\[Eta]`p2, 
   d`f1`o1`qfb`dds`dd`\[Pi]i0`p2, d`f1`o1`qfb`dds`dd`etas`p2, 
   s`f1`o1`qfb`dsd`ds`\[CapitalKappa]i0`p2, 
   d`f1`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p2}, {u`f1`o2`qfa`uds`uu`\[Eta]`p1, 
   u`f1`o2`qfa`uds`uu`etas`p1, u`f1`o2`qfa`uds`uu`\[Pi]i0`p1, 
   u`f1`o2`qfa`uds`ud`\[Pi]ip`p1, u`f1`o2`qfa`uds`us`\[CapitalKappa]ip`p1, 
   d`f1`o2`qfa`dus`du`\[Pi]im`p1, d`f1`o2`qfa`dus`dd`\[Eta]`p1, 
   d`f1`o2`qfa`dus`dd`etas`p1, d`f1`o2`qfa`dus`dd`\[Pi]i0`p1, 
   d`f1`o2`qfa`dus`ds`\[CapitalKappa]i0`p1, 
   s`f1`o2`qfa`sdu`su`\[CapitalKappa]im`p1, 
   s`f1`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p1, s`f1`o2`qfa`sdu`ss`\[Eta]`p1, 
   s`f1`o2`qfa`sdu`ss`etas`p1, u`f1`o2`qfa`uds`uu`\[Eta]`p2, 
   u`f1`o2`qfa`uds`uu`etas`p2, u`f1`o2`qfa`uds`uu`\[Pi]i0`p2, 
   d`f1`o2`qfa`uds`ud`\[Pi]ip`p2, s`f1`o2`qfa`uds`us`\[CapitalKappa]ip`p2, 
   u`f1`o2`qfa`dus`du`\[Pi]im`p2, d`f1`o2`qfa`dus`dd`\[Eta]`p2, 
   d`f1`o2`qfa`dus`dd`etas`p2, d`f1`o2`qfa`dus`dd`\[Pi]i0`p2, 
   s`f1`o2`qfa`dus`ds`\[CapitalKappa]i0`p2, 
   u`f1`o2`qfa`sdu`su`\[CapitalKappa]im`p2, 
   d`f1`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p2, s`f1`o2`qfa`sdu`ss`\[Eta]`p2, 
   s`f1`o2`qfa`sdu`ss`etas`p2, u`f1`o2`qfb`uds`ud`\[Pi]ip`p1, 
   u`f1`o2`qfb`usd`us`\[CapitalKappa]ip`p1, d`f1`o2`qfb`dus`du`\[Pi]im`p1, 
   d`f1`o2`qfb`dsu`ds`\[CapitalKappa]i0`p1, 
   s`f1`o2`qfb`sud`su`\[CapitalKappa]im`p1, 
   s`f1`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p1, d`f1`o2`qfb`uds`ud`\[Pi]ip`p2, 
   s`f1`o2`qfb`usd`us`\[CapitalKappa]ip`p2, u`f1`o2`qfb`dus`du`\[Pi]im`p2, 
   s`f1`o2`qfb`dsu`ds`\[CapitalKappa]i0`p2, 
   u`f1`o2`qfb`sud`su`\[CapitalKappa]im`p2, 
   d`f1`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p2}, {u`f1`o3`qfa`uus`uu`\[Eta]`p1, 
   u`f1`o3`qfa`uus`uu`\[Pi]i0`p1, u`f1`o3`qfa`uus`uu`etas`p1, 
   u`f1`o3`qfa`uus`ud`\[Pi]ip`p1, u`f1`o3`qfa`uus`us`\[CapitalKappa]ip`p1, 
   s`f1`o3`qfa`suu`su`\[CapitalKappa]im`p1, 
   s`f1`o3`qfa`suu`sd`\[CapitalKappa]i0b`p1, s`f1`o3`qfa`suu`ss`\[Eta]`p1, 
   s`f1`o3`qfa`suu`ss`etas`p1, u`f1`o3`qfa`uus`uu`\[Eta]`p2, 
   u`f1`o3`qfa`uus`uu`\[Pi]i0`p2, u`f1`o3`qfa`uus`uu`etas`p2, 
   d`f1`o3`qfa`uus`ud`\[Pi]ip`p2, s`f1`o3`qfa`uus`us`\[CapitalKappa]ip`p2, 
   u`f1`o3`qfa`suu`su`\[CapitalKappa]im`p2, 
   d`f1`o3`qfa`suu`sd`\[CapitalKappa]i0b`p2, s`f1`o3`qfa`suu`ss`\[Eta]`p2, 
   s`f1`o3`qfa`suu`ss`etas`p2, u`f1`o3`qfb`uus`uu`\[Eta]`p1, 
   u`f1`o3`qfb`uus`uu`\[Pi]i0`p1, u`f1`o3`qfb`uus`uu`etas`p1, 
   u`f1`o3`qfb`usu`us`\[CapitalKappa]ip`p1, 
   s`f1`o3`qfb`suu`su`\[CapitalKappa]im`p1, u`f1`o3`qfb`uus`uu`\[Eta]`p2, 
   u`f1`o3`qfb`uus`uu`\[Pi]i0`p2, u`f1`o3`qfb`uus`uu`etas`p2, 
   s`f1`o3`qfb`usu`us`\[CapitalKappa]ip`p2, 
   u`f1`o3`qfb`suu`su`\[CapitalKappa]im`p2}, {u`f1`o4`qfa`udu`uu`\[Eta]`p1, 
   u`f1`o4`qfa`udu`uu`\[Pi]i0`p1, u`f1`o4`qfa`udu`uu`etas`p1, 
   u`f1`o4`qfa`udu`ud`\[Pi]ip`p1, u`f1`o4`qfa`udu`us`\[CapitalKappa]ip`p1, 
   d`f1`o4`qfa`duu`du`\[Pi]im`p1, d`f1`o4`qfa`duu`dd`\[Eta]`p1, 
   d`f1`o4`qfa`duu`dd`\[Pi]i0`p1, d`f1`o4`qfa`duu`dd`etas`p1, 
   d`f1`o4`qfa`duu`ds`\[CapitalKappa]i0`p1, u`f1`o4`qfa`udu`uu`\[Eta]`p2, 
   u`f1`o4`qfa`udu`uu`\[Pi]i0`p2, u`f1`o4`qfa`udu`uu`etas`p2, 
   d`f1`o4`qfa`udu`ud`\[Pi]ip`p2, s`f1`o4`qfa`udu`us`\[CapitalKappa]ip`p2, 
   u`f1`o4`qfa`duu`du`\[Pi]im`p2, d`f1`o4`qfa`duu`dd`\[Eta]`p2, 
   d`f1`o4`qfa`duu`dd`\[Pi]i0`p2, d`f1`o4`qfa`duu`dd`etas`p2, 
   s`f1`o4`qfa`duu`ds`\[CapitalKappa]i0`p2, u`f1`o4`qfb`uud`uu`\[Eta]`p1, 
   u`f1`o4`qfb`uud`uu`\[Pi]i0`p1, u`f1`o4`qfb`uud`uu`etas`p1, 
   u`f1`o4`qfb`udu`ud`\[Pi]ip`p1, d`f1`o4`qfb`duu`du`\[Pi]im`p1, 
   u`f1`o4`qfb`uud`uu`\[Eta]`p2, u`f1`o4`qfb`uud`uu`\[Pi]i0`p2, 
   u`f1`o4`qfb`uud`uu`etas`p2, d`f1`o4`qfb`udu`ud`\[Pi]ip`p2, 
   u`f1`o4`qfb`duu`du`\[Pi]im`p2}, {u`f1`o5`qfa`udd`uu`\[Eta]`p1, 
   u`f1`o5`qfa`udd`uu`\[Pi]i0`p1, u`f1`o5`qfa`udd`uu`etas`p1, 
   u`f1`o5`qfa`udd`ud`\[Pi]ip`p1, u`f1`o5`qfa`udd`us`\[CapitalKappa]ip`p1, 
   d`f1`o5`qfa`ddu`du`\[Pi]im`p1, d`f1`o5`qfa`ddu`dd`\[Eta]`p1, 
   d`f1`o5`qfa`ddu`dd`\[Pi]i0`p1, d`f1`o5`qfa`ddu`dd`etas`p1, 
   d`f1`o5`qfa`ddu`ds`\[CapitalKappa]i0`p1, u`f1`o5`qfa`udd`uu`\[Eta]`p2, 
   u`f1`o5`qfa`udd`uu`\[Pi]i0`p2, u`f1`o5`qfa`udd`uu`etas`p2, 
   d`f1`o5`qfa`udd`ud`\[Pi]ip`p2, s`f1`o5`qfa`udd`us`\[CapitalKappa]ip`p2, 
   u`f1`o5`qfa`ddu`du`\[Pi]im`p2, d`f1`o5`qfa`ddu`dd`\[Eta]`p2, 
   d`f1`o5`qfa`ddu`dd`\[Pi]i0`p2, d`f1`o5`qfa`ddu`dd`etas`p2, 
   s`f1`o5`qfa`ddu`ds`\[CapitalKappa]i0`p2, u`f1`o5`qfb`udd`ud`\[Pi]ip`p1, 
   d`f1`o5`qfb`dud`du`\[Pi]im`p1, d`f1`o5`qfb`ddu`dd`\[Eta]`p1, 
   d`f1`o5`qfb`ddu`dd`\[Pi]i0`p1, d`f1`o5`qfb`ddu`dd`etas`p1, 
   d`f1`o5`qfb`udd`ud`\[Pi]ip`p2, u`f1`o5`qfb`dud`du`\[Pi]im`p2, 
   d`f1`o5`qfb`ddu`dd`\[Eta]`p2, d`f1`o5`qfb`ddu`dd`\[Pi]i0`p2, 
   d`f1`o5`qfb`ddu`dd`etas`p2}, {d`f1`o6`qfa`dss`du`\[Pi]im`p1, 
   d`f1`o6`qfa`dss`dd`\[Eta]`p1, d`f1`o6`qfa`dss`dd`\[Pi]i0`p1, 
   d`f1`o6`qfa`dss`dd`etas`p1, d`f1`o6`qfa`dss`ds`\[CapitalKappa]i0`p1, 
   s`f1`o6`qfa`ssd`su`\[CapitalKappa]im`p1, 
   s`f1`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p1, s`f1`o6`qfa`ssd`ss`\[Eta]`p1, 
   s`f1`o6`qfa`ssd`ss`etas`p1, u`f1`o6`qfa`dss`du`\[Pi]im`p2, 
   d`f1`o6`qfa`dss`dd`\[Eta]`p2, d`f1`o6`qfa`dss`dd`\[Pi]i0`p2, 
   d`f1`o6`qfa`dss`dd`etas`p2, s`f1`o6`qfa`dss`ds`\[CapitalKappa]i0`p2, 
   u`f1`o6`qfa`ssd`su`\[CapitalKappa]im`p2, 
   d`f1`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p2, s`f1`o6`qfa`ssd`ss`\[Eta]`p2, 
   s`f1`o6`qfa`ssd`ss`etas`p2, d`f1`o6`qfb`dss`ds`\[CapitalKappa]i0`p1, 
   s`f1`o6`qfb`sds`sd`\[CapitalKappa]i0b`p1, s`f1`o6`qfb`ssd`ss`\[Eta]`p1, 
   s`f1`o6`qfb`ssd`ss`etas`p1, s`f1`o6`qfb`dss`ds`\[CapitalKappa]i0`p2, 
   d`f1`o6`qfb`sds`sd`\[CapitalKappa]i0b`p2, s`f1`o6`qfb`ssd`ss`\[Eta]`p2, 
   s`f1`o6`qfb`ssd`ss`etas`p2}, {u`f1`o7`qfa`uss`uu`\[Eta]`p1, 
   u`f1`o7`qfa`uss`uu`\[Pi]i0`p1, u`f1`o7`qfa`uss`uu`etas`p1, 
   u`f1`o7`qfa`uss`ud`\[Pi]ip`p1, u`f1`o7`qfa`uss`us`\[CapitalKappa]ip`p1, 
   s`f1`o7`qfa`sus`su`\[CapitalKappa]im`p1, 
   s`f1`o7`qfa`sus`sd`\[CapitalKappa]i0b`p1, s`f1`o7`qfa`sus`ss`\[Eta]`p1, 
   s`f1`o7`qfa`sus`ss`etas`p1, u`f1`o7`qfa`uss`uu`\[Eta]`p2, 
   u`f1`o7`qfa`uss`uu`\[Pi]i0`p2, u`f1`o7`qfa`uss`uu`etas`p2, 
   d`f1`o7`qfa`uss`ud`\[Pi]ip`p2, s`f1`o7`qfa`uss`us`\[CapitalKappa]ip`p2, 
   u`f1`o7`qfa`sus`su`\[CapitalKappa]im`p2, 
   d`f1`o7`qfa`sus`sd`\[CapitalKappa]i0b`p2, s`f1`o7`qfa`sus`ss`\[Eta]`p2, 
   s`f1`o7`qfa`sus`ss`etas`p2, u`f1`o7`qfb`uss`us`\[CapitalKappa]ip`p1, 
   s`f1`o7`qfb`sus`su`\[CapitalKappa]im`p1, s`f1`o7`qfb`ssu`ss`\[Eta]`p1, 
   s`f1`o7`qfb`ssu`ss`etas`p1, s`f1`o7`qfb`uss`us`\[CapitalKappa]ip`p2, 
   u`f1`o7`qfb`sus`su`\[CapitalKappa]im`p2, s`f1`o7`qfb`ssu`ss`\[Eta]`p2, 
   s`f1`o7`qfb`ssu`ss`etas`p2}, {u`f1`o8`qfa`uds`uu`\[Pi]i0`p1, 
   u`f1`o8`qfa`uds`uu`\[Eta]`p1, u`f1`o8`qfa`uds`uu`etas`p1, 
   u`f1`o8`qfa`uds`ud`\[Pi]ip`p1, u`f1`o8`qfa`uds`us`\[CapitalKappa]ip`p1, 
   d`f1`o8`qfa`dus`du`\[Pi]im`p1, d`f1`o8`qfa`dus`dd`\[Pi]i0`p1, 
   d`f1`o8`qfa`dus`dd`\[Eta]`p1, d`f1`o8`qfa`dus`dd`etas`p1, 
   d`f1`o8`qfa`dus`ds`\[CapitalKappa]i0`p1, 
   s`f1`o8`qfa`sdu`su`\[CapitalKappa]im`p1, 
   s`f1`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p1, s`f1`o8`qfa`sdu`ss`\[Eta]`p1, 
   s`f1`o8`qfa`sdu`ss`etas`p1, u`f1`o8`qfa`uds`uu`\[Pi]i0`p2, 
   u`f1`o8`qfa`uds`uu`\[Eta]`p2, u`f1`o8`qfa`uds`uu`etas`p2, 
   d`f1`o8`qfa`uds`ud`\[Pi]ip`p2, s`f1`o8`qfa`uds`us`\[CapitalKappa]ip`p2, 
   u`f1`o8`qfa`dus`du`\[Pi]im`p2, d`f1`o8`qfa`dus`dd`\[Pi]i0`p2, 
   d`f1`o8`qfa`dus`dd`\[Eta]`p2, d`f1`o8`qfa`dus`dd`etas`p2, 
   s`f1`o8`qfa`dus`ds`\[CapitalKappa]i0`p2, 
   u`f1`o8`qfa`sdu`su`\[CapitalKappa]im`p2, 
   d`f1`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p2, s`f1`o8`qfa`sdu`ss`\[Eta]`p2, 
   s`f1`o8`qfa`sdu`ss`etas`p2, u`f1`o8`qfb`uds`ud`\[Pi]ip`p1, 
   u`f1`o8`qfb`usd`us`\[CapitalKappa]ip`p1, d`f1`o8`qfb`dus`du`\[Pi]im`p1, 
   d`f1`o8`qfb`dsu`ds`\[CapitalKappa]i0`p1, 
   s`f1`o8`qfb`sud`su`\[CapitalKappa]im`p1, 
   s`f1`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p1, d`f1`o8`qfb`uds`ud`\[Pi]ip`p2, 
   s`f1`o8`qfb`usd`us`\[CapitalKappa]ip`p2, u`f1`o8`qfb`dus`du`\[Pi]im`p2, 
   s`f1`o8`qfb`dsu`ds`\[CapitalKappa]i0`p2, 
   u`f1`o8`qfb`sud`su`\[CapitalKappa]im`p2, 
   d`f1`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p2}}, 
 {{u`f2`o1`qfa`dsd`du`\[Pi]im`p3, d`f2`o1`qfa`dsd`dd`\[Eta]`p3, 
   d`f2`o1`qfa`dsd`dd`\[Pi]i0`p3, d`f2`o1`qfa`dsd`dd`etas`p3, 
   s`f2`o1`qfa`dsd`ds`\[CapitalKappa]i0`p3, 
   u`f2`o1`qfa`sdd`su`\[CapitalKappa]im`p3, 
   d`f2`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p3, s`f2`o1`qfa`sdd`ss`\[Eta]`p3, 
   s`f2`o1`qfa`sdd`ss`etas`p3, s`f2`o1`qfa`dsd`du`\[Pi]im`p4, 
   s`f2`o1`qfa`dsd`dd`\[Eta]`p4, s`f2`o1`qfa`dsd`dd`\[Pi]i0`p4, 
   s`f2`o1`qfa`dsd`dd`etas`p4, s`f2`o1`qfa`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f2`o1`qfa`sdd`su`\[CapitalKappa]im`p4, 
   d`f2`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p4, d`f2`o1`qfa`sdd`ss`\[Eta]`p4, 
   d`f2`o1`qfa`sdd`ss`etas`p4, d`f2`o1`qfa`dsd`du`\[Pi]im`p5, 
   d`f2`o1`qfa`dsd`dd`\[Eta]`p5, d`f2`o1`qfa`dsd`dd`\[Pi]i0`p5, 
   d`f2`o1`qfa`dsd`dd`etas`p5, d`f2`o1`qfa`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f2`o1`qfa`sdd`su`\[CapitalKappa]im`p5, 
   d`f2`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p5, d`f2`o1`qfa`sdd`ss`\[Eta]`p5, 
   d`f2`o1`qfa`sdd`ss`etas`p5, d`f2`o1`qfb`dds`dd`\[Eta]`p3, 
   d`f2`o1`qfb`dds`dd`\[Pi]i0`p3, d`f2`o1`qfb`dds`dd`etas`p3, 
   s`f2`o1`qfb`dsd`ds`\[CapitalKappa]i0`p3, 
   d`f2`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p3, d`f2`o1`qfb`dds`dd`\[Eta]`p4, 
   d`f2`o1`qfb`dds`dd`\[Pi]i0`p4, d`f2`o1`qfb`dds`dd`etas`p4, 
   s`f2`o1`qfb`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f2`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p4, s`f2`o1`qfb`dds`dd`\[Eta]`p5, 
   s`f2`o1`qfb`dds`dd`\[Pi]i0`p5, s`f2`o1`qfb`dds`dd`etas`p5, 
   d`f2`o1`qfb`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f2`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p5}, {u`f2`o2`qfa`uds`uu`\[Eta]`p3, 
   u`f2`o2`qfa`uds`uu`etas`p3, u`f2`o2`qfa`uds`uu`\[Pi]i0`p3, 
   d`f2`o2`qfa`uds`ud`\[Pi]ip`p3, s`f2`o2`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f2`o2`qfa`dus`du`\[Pi]im`p3, d`f2`o2`qfa`dus`dd`\[Eta]`p3, 
   d`f2`o2`qfa`dus`dd`etas`p3, d`f2`o2`qfa`dus`dd`\[Pi]i0`p3, 
   s`f2`o2`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f2`o2`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f2`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f2`o2`qfa`sdu`ss`\[Eta]`p3, 
   s`f2`o2`qfa`sdu`ss`etas`p3, d`f2`o2`qfa`uds`uu`\[Eta]`p4, 
   d`f2`o2`qfa`uds`uu`etas`p4, d`f2`o2`qfa`uds`uu`\[Pi]i0`p4, 
   d`f2`o2`qfa`uds`ud`\[Pi]ip`p4, d`f2`o2`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f2`o2`qfa`dus`du`\[Pi]im`p4, u`f2`o2`qfa`dus`dd`\[Eta]`p4, 
   u`f2`o2`qfa`dus`dd`etas`p4, u`f2`o2`qfa`dus`dd`\[Pi]i0`p4, 
   u`f2`o2`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f2`o2`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f2`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f2`o2`qfa`sdu`ss`\[Eta]`p4, 
   d`f2`o2`qfa`sdu`ss`etas`p4, s`f2`o2`qfa`uds`uu`\[Eta]`p5, 
   s`f2`o2`qfa`uds`uu`etas`p5, s`f2`o2`qfa`uds`uu`\[Pi]i0`p5, 
   s`f2`o2`qfa`uds`ud`\[Pi]ip`p5, s`f2`o2`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f2`o2`qfa`dus`du`\[Pi]im`p5, s`f2`o2`qfa`dus`dd`\[Eta]`p5, 
   s`f2`o2`qfa`dus`dd`etas`p5, s`f2`o2`qfa`dus`dd`\[Pi]i0`p5, 
   s`f2`o2`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f2`o2`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f2`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f2`o2`qfa`sdu`ss`\[Eta]`p5, 
   u`f2`o2`qfa`sdu`ss`etas`p5, d`f2`o2`qfb`uds`ud`\[Pi]ip`p3, 
   s`f2`o2`qfb`usd`us`\[CapitalKappa]ip`p3, u`f2`o2`qfb`dus`du`\[Pi]im`p3, 
   s`f2`o2`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f2`o2`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f2`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f2`o2`qfb`uds`ud`\[Pi]ip`p4, 
   s`f2`o2`qfb`usd`us`\[CapitalKappa]ip`p4, u`f2`o2`qfb`dus`du`\[Pi]im`p4, 
   s`f2`o2`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f2`o2`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f2`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f2`o2`qfb`uds`ud`\[Pi]ip`p5, 
   d`f2`o2`qfb`usd`us`\[CapitalKappa]ip`p5, s`f2`o2`qfb`dus`du`\[Pi]im`p5, 
   u`f2`o2`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f2`o2`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f2`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p5}, {u`f2`o3`qfa`uus`uu`\[Eta]`p3, 
   u`f2`o3`qfa`uus`uu`\[Pi]i0`p3, u`f2`o3`qfa`uus`uu`etas`p3, 
   d`f2`o3`qfa`uus`ud`\[Pi]ip`p3, s`f2`o3`qfa`uus`us`\[CapitalKappa]ip`p3, 
   u`f2`o3`qfa`suu`su`\[CapitalKappa]im`p3, 
   d`f2`o3`qfa`suu`sd`\[CapitalKappa]i0b`p3, s`f2`o3`qfa`suu`ss`\[Eta]`p3, 
   s`f2`o3`qfa`suu`ss`etas`p3, u`f2`o3`qfa`uus`uu`\[Eta]`p4, 
   u`f2`o3`qfa`uus`uu`\[Pi]i0`p4, u`f2`o3`qfa`uus`uu`etas`p4, 
   u`f2`o3`qfa`uus`ud`\[Pi]ip`p4, u`f2`o3`qfa`uus`us`\[CapitalKappa]ip`p4, 
   u`f2`o3`qfa`suu`su`\[CapitalKappa]im`p4, 
   u`f2`o3`qfa`suu`sd`\[CapitalKappa]i0b`p4, u`f2`o3`qfa`suu`ss`\[Eta]`p4, 
   u`f2`o3`qfa`suu`ss`etas`p4, s`f2`o3`qfa`uus`uu`\[Eta]`p5, 
   s`f2`o3`qfa`uus`uu`\[Pi]i0`p5, s`f2`o3`qfa`uus`uu`etas`p5, 
   s`f2`o3`qfa`uus`ud`\[Pi]ip`p5, s`f2`o3`qfa`uus`us`\[CapitalKappa]ip`p5, 
   u`f2`o3`qfa`suu`su`\[CapitalKappa]im`p5, 
   u`f2`o3`qfa`suu`sd`\[CapitalKappa]i0b`p5, u`f2`o3`qfa`suu`ss`\[Eta]`p5, 
   u`f2`o3`qfa`suu`ss`etas`p5, u`f2`o3`qfb`uus`uu`\[Eta]`p3, 
   u`f2`o3`qfb`uus`uu`\[Pi]i0`p3, u`f2`o3`qfb`uus`uu`etas`p3, 
   s`f2`o3`qfb`usu`us`\[CapitalKappa]ip`p3, 
   u`f2`o3`qfb`suu`su`\[CapitalKappa]im`p3, u`f2`o3`qfb`uus`uu`\[Eta]`p4, 
   u`f2`o3`qfb`uus`uu`\[Pi]i0`p4, u`f2`o3`qfb`uus`uu`etas`p4, 
   s`f2`o3`qfb`usu`us`\[CapitalKappa]ip`p4, 
   u`f2`o3`qfb`suu`su`\[CapitalKappa]im`p4, s`f2`o3`qfb`uus`uu`\[Eta]`p5, 
   s`f2`o3`qfb`uus`uu`\[Pi]i0`p5, s`f2`o3`qfb`uus`uu`etas`p5, 
   u`f2`o3`qfb`usu`us`\[CapitalKappa]ip`p5, 
   u`f2`o3`qfb`suu`su`\[CapitalKappa]im`p5}, {u`f2`o4`qfa`udu`uu`\[Eta]`p3, 
   u`f2`o4`qfa`udu`uu`\[Pi]i0`p3, u`f2`o4`qfa`udu`uu`etas`p3, 
   d`f2`o4`qfa`udu`ud`\[Pi]ip`p3, s`f2`o4`qfa`udu`us`\[CapitalKappa]ip`p3, 
   u`f2`o4`qfa`duu`du`\[Pi]im`p3, d`f2`o4`qfa`duu`dd`\[Eta]`p3, 
   d`f2`o4`qfa`duu`dd`\[Pi]i0`p3, d`f2`o4`qfa`duu`dd`etas`p3, 
   s`f2`o4`qfa`duu`ds`\[CapitalKappa]i0`p3, d`f2`o4`qfa`udu`uu`\[Eta]`p4, 
   d`f2`o4`qfa`udu`uu`\[Pi]i0`p4, d`f2`o4`qfa`udu`uu`etas`p4, 
   d`f2`o4`qfa`udu`ud`\[Pi]ip`p4, d`f2`o4`qfa`udu`us`\[CapitalKappa]ip`p4, 
   u`f2`o4`qfa`duu`du`\[Pi]im`p4, u`f2`o4`qfa`duu`dd`\[Eta]`p4, 
   u`f2`o4`qfa`duu`dd`\[Pi]i0`p4, u`f2`o4`qfa`duu`dd`etas`p4, 
   u`f2`o4`qfa`duu`ds`\[CapitalKappa]i0`p4, u`f2`o4`qfa`udu`uu`\[Eta]`p5, 
   u`f2`o4`qfa`udu`uu`\[Pi]i0`p5, u`f2`o4`qfa`udu`uu`etas`p5, 
   u`f2`o4`qfa`udu`ud`\[Pi]ip`p5, u`f2`o4`qfa`udu`us`\[CapitalKappa]ip`p5, 
   u`f2`o4`qfa`duu`du`\[Pi]im`p5, u`f2`o4`qfa`duu`dd`\[Eta]`p5, 
   u`f2`o4`qfa`duu`dd`\[Pi]i0`p5, u`f2`o4`qfa`duu`dd`etas`p5, 
   u`f2`o4`qfa`duu`ds`\[CapitalKappa]i0`p5, u`f2`o4`qfb`uud`uu`\[Eta]`p3, 
   u`f2`o4`qfb`uud`uu`\[Pi]i0`p3, u`f2`o4`qfb`uud`uu`etas`p3, 
   d`f2`o4`qfb`udu`ud`\[Pi]ip`p3, u`f2`o4`qfb`duu`du`\[Pi]im`p3, 
   u`f2`o4`qfb`uud`uu`\[Eta]`p4, u`f2`o4`qfb`uud`uu`\[Pi]i0`p4, 
   u`f2`o4`qfb`uud`uu`etas`p4, d`f2`o4`qfb`udu`ud`\[Pi]ip`p4, 
   u`f2`o4`qfb`duu`du`\[Pi]im`p4, d`f2`o4`qfb`uud`uu`\[Eta]`p5, 
   d`f2`o4`qfb`uud`uu`\[Pi]i0`p5, d`f2`o4`qfb`uud`uu`etas`p5, 
   u`f2`o4`qfb`udu`ud`\[Pi]ip`p5, u`f2`o4`qfb`duu`du`\[Pi]im`p5}, 
  {u`f2`o5`qfa`udd`uu`\[Eta]`p3, u`f2`o5`qfa`udd`uu`\[Pi]i0`p3, 
   u`f2`o5`qfa`udd`uu`etas`p3, d`f2`o5`qfa`udd`ud`\[Pi]ip`p3, 
   s`f2`o5`qfa`udd`us`\[CapitalKappa]ip`p3, u`f2`o5`qfa`ddu`du`\[Pi]im`p3, 
   d`f2`o5`qfa`ddu`dd`\[Eta]`p3, d`f2`o5`qfa`ddu`dd`\[Pi]i0`p3, 
   d`f2`o5`qfa`ddu`dd`etas`p3, s`f2`o5`qfa`ddu`ds`\[CapitalKappa]i0`p3, 
   d`f2`o5`qfa`udd`uu`\[Eta]`p4, d`f2`o5`qfa`udd`uu`\[Pi]i0`p4, 
   d`f2`o5`qfa`udd`uu`etas`p4, d`f2`o5`qfa`udd`ud`\[Pi]ip`p4, 
   d`f2`o5`qfa`udd`us`\[CapitalKappa]ip`p4, d`f2`o5`qfa`ddu`du`\[Pi]im`p4, 
   d`f2`o5`qfa`ddu`dd`\[Eta]`p4, d`f2`o5`qfa`ddu`dd`\[Pi]i0`p4, 
   d`f2`o5`qfa`ddu`dd`etas`p4, d`f2`o5`qfa`ddu`ds`\[CapitalKappa]i0`p4, 
   d`f2`o5`qfa`udd`uu`\[Eta]`p5, d`f2`o5`qfa`udd`uu`\[Pi]i0`p5, 
   d`f2`o5`qfa`udd`uu`etas`p5, d`f2`o5`qfa`udd`ud`\[Pi]ip`p5, 
   d`f2`o5`qfa`udd`us`\[CapitalKappa]ip`p5, u`f2`o5`qfa`ddu`du`\[Pi]im`p5, 
   u`f2`o5`qfa`ddu`dd`\[Eta]`p5, u`f2`o5`qfa`ddu`dd`\[Pi]i0`p5, 
   u`f2`o5`qfa`ddu`dd`etas`p5, u`f2`o5`qfa`ddu`ds`\[CapitalKappa]i0`p5, 
   d`f2`o5`qfb`udd`ud`\[Pi]ip`p3, u`f2`o5`qfb`dud`du`\[Pi]im`p3, 
   d`f2`o5`qfb`ddu`dd`\[Eta]`p3, d`f2`o5`qfb`ddu`dd`\[Pi]i0`p3, 
   d`f2`o5`qfb`ddu`dd`etas`p3, d`f2`o5`qfb`udd`ud`\[Pi]ip`p4, 
   u`f2`o5`qfb`dud`du`\[Pi]im`p4, d`f2`o5`qfb`ddu`dd`\[Eta]`p4, 
   d`f2`o5`qfb`ddu`dd`\[Pi]i0`p4, d`f2`o5`qfb`ddu`dd`etas`p4, 
   d`f2`o5`qfb`udd`ud`\[Pi]ip`p5, d`f2`o5`qfb`dud`du`\[Pi]im`p5, 
   u`f2`o5`qfb`ddu`dd`\[Eta]`p5, u`f2`o5`qfb`ddu`dd`\[Pi]i0`p5, 
   u`f2`o5`qfb`ddu`dd`etas`p5}, {u`f2`o6`qfa`dss`du`\[Pi]im`p3, 
   d`f2`o6`qfa`dss`dd`\[Eta]`p3, d`f2`o6`qfa`dss`dd`\[Pi]i0`p3, 
   d`f2`o6`qfa`dss`dd`etas`p3, s`f2`o6`qfa`dss`ds`\[CapitalKappa]i0`p3, 
   u`f2`o6`qfa`ssd`su`\[CapitalKappa]im`p3, 
   d`f2`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p3, s`f2`o6`qfa`ssd`ss`\[Eta]`p3, 
   s`f2`o6`qfa`ssd`ss`etas`p3, s`f2`o6`qfa`dss`du`\[Pi]im`p4, 
   s`f2`o6`qfa`dss`dd`\[Eta]`p4, s`f2`o6`qfa`dss`dd`\[Pi]i0`p4, 
   s`f2`o6`qfa`dss`dd`etas`p4, s`f2`o6`qfa`dss`ds`\[CapitalKappa]i0`p4, 
   s`f2`o6`qfa`ssd`su`\[CapitalKappa]im`p4, 
   s`f2`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p4, s`f2`o6`qfa`ssd`ss`\[Eta]`p4, 
   s`f2`o6`qfa`ssd`ss`etas`p4, s`f2`o6`qfa`dss`du`\[Pi]im`p5, 
   s`f2`o6`qfa`dss`dd`\[Eta]`p5, s`f2`o6`qfa`dss`dd`\[Pi]i0`p5, 
   s`f2`o6`qfa`dss`dd`etas`p5, s`f2`o6`qfa`dss`ds`\[CapitalKappa]i0`p5, 
   d`f2`o6`qfa`ssd`su`\[CapitalKappa]im`p5, 
   d`f2`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p5, d`f2`o6`qfa`ssd`ss`\[Eta]`p5, 
   d`f2`o6`qfa`ssd`ss`etas`p5, s`f2`o6`qfb`dss`ds`\[CapitalKappa]i0`p3, 
   d`f2`o6`qfb`sds`sd`\[CapitalKappa]i0b`p3, s`f2`o6`qfb`ssd`ss`\[Eta]`p3, 
   s`f2`o6`qfb`ssd`ss`etas`p3, s`f2`o6`qfb`dss`ds`\[CapitalKappa]i0`p4, 
   d`f2`o6`qfb`sds`sd`\[CapitalKappa]i0b`p4, s`f2`o6`qfb`ssd`ss`\[Eta]`p4, 
   s`f2`o6`qfb`ssd`ss`etas`p4, s`f2`o6`qfb`dss`ds`\[CapitalKappa]i0`p5, 
   s`f2`o6`qfb`sds`sd`\[CapitalKappa]i0b`p5, d`f2`o6`qfb`ssd`ss`\[Eta]`p5, 
   d`f2`o6`qfb`ssd`ss`etas`p5}, {u`f2`o7`qfa`uss`uu`\[Eta]`p3, 
   u`f2`o7`qfa`uss`uu`\[Pi]i0`p3, u`f2`o7`qfa`uss`uu`etas`p3, 
   d`f2`o7`qfa`uss`ud`\[Pi]ip`p3, s`f2`o7`qfa`uss`us`\[CapitalKappa]ip`p3, 
   u`f2`o7`qfa`sus`su`\[CapitalKappa]im`p3, 
   d`f2`o7`qfa`sus`sd`\[CapitalKappa]i0b`p3, s`f2`o7`qfa`sus`ss`\[Eta]`p3, 
   s`f2`o7`qfa`sus`ss`etas`p3, s`f2`o7`qfa`uss`uu`\[Eta]`p4, 
   s`f2`o7`qfa`uss`uu`\[Pi]i0`p4, s`f2`o7`qfa`uss`uu`etas`p4, 
   s`f2`o7`qfa`uss`ud`\[Pi]ip`p4, s`f2`o7`qfa`uss`us`\[CapitalKappa]ip`p4, 
   u`f2`o7`qfa`sus`su`\[CapitalKappa]im`p4, 
   u`f2`o7`qfa`sus`sd`\[CapitalKappa]i0b`p4, u`f2`o7`qfa`sus`ss`\[Eta]`p4, 
   u`f2`o7`qfa`sus`ss`etas`p4, s`f2`o7`qfa`uss`uu`\[Eta]`p5, 
   s`f2`o7`qfa`uss`uu`\[Pi]i0`p5, s`f2`o7`qfa`uss`uu`etas`p5, 
   s`f2`o7`qfa`uss`ud`\[Pi]ip`p5, s`f2`o7`qfa`uss`us`\[CapitalKappa]ip`p5, 
   s`f2`o7`qfa`sus`su`\[CapitalKappa]im`p5, 
   s`f2`o7`qfa`sus`sd`\[CapitalKappa]i0b`p5, s`f2`o7`qfa`sus`ss`\[Eta]`p5, 
   s`f2`o7`qfa`sus`ss`etas`p5, s`f2`o7`qfb`uss`us`\[CapitalKappa]ip`p3, 
   u`f2`o7`qfb`sus`su`\[CapitalKappa]im`p3, s`f2`o7`qfb`ssu`ss`\[Eta]`p3, 
   s`f2`o7`qfb`ssu`ss`etas`p3, s`f2`o7`qfb`uss`us`\[CapitalKappa]ip`p4, 
   u`f2`o7`qfb`sus`su`\[CapitalKappa]im`p4, s`f2`o7`qfb`ssu`ss`\[Eta]`p4, 
   s`f2`o7`qfb`ssu`ss`etas`p4, s`f2`o7`qfb`uss`us`\[CapitalKappa]ip`p5, 
   s`f2`o7`qfb`sus`su`\[CapitalKappa]im`p5, u`f2`o7`qfb`ssu`ss`\[Eta]`p5, 
   u`f2`o7`qfb`ssu`ss`etas`p5}, {u`f2`o8`qfa`uds`uu`\[Pi]i0`p3, 
   u`f2`o8`qfa`uds`uu`\[Eta]`p3, u`f2`o8`qfa`uds`uu`etas`p3, 
   d`f2`o8`qfa`uds`ud`\[Pi]ip`p3, s`f2`o8`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f2`o8`qfa`dus`du`\[Pi]im`p3, d`f2`o8`qfa`dus`dd`\[Pi]i0`p3, 
   d`f2`o8`qfa`dus`dd`\[Eta]`p3, d`f2`o8`qfa`dus`dd`etas`p3, 
   s`f2`o8`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f2`o8`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f2`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f2`o8`qfa`sdu`ss`\[Eta]`p3, 
   s`f2`o8`qfa`sdu`ss`etas`p3, d`f2`o8`qfa`uds`uu`\[Pi]i0`p4, 
   d`f2`o8`qfa`uds`uu`\[Eta]`p4, d`f2`o8`qfa`uds`uu`etas`p4, 
   d`f2`o8`qfa`uds`ud`\[Pi]ip`p4, d`f2`o8`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f2`o8`qfa`dus`du`\[Pi]im`p4, u`f2`o8`qfa`dus`dd`\[Pi]i0`p4, 
   u`f2`o8`qfa`dus`dd`\[Eta]`p4, u`f2`o8`qfa`dus`dd`etas`p4, 
   u`f2`o8`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f2`o8`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f2`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f2`o8`qfa`sdu`ss`\[Eta]`p4, 
   d`f2`o8`qfa`sdu`ss`etas`p4, s`f2`o8`qfa`uds`uu`\[Pi]i0`p5, 
   s`f2`o8`qfa`uds`uu`\[Eta]`p5, s`f2`o8`qfa`uds`uu`etas`p5, 
   s`f2`o8`qfa`uds`ud`\[Pi]ip`p5, s`f2`o8`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f2`o8`qfa`dus`du`\[Pi]im`p5, s`f2`o8`qfa`dus`dd`\[Pi]i0`p5, 
   s`f2`o8`qfa`dus`dd`\[Eta]`p5, s`f2`o8`qfa`dus`dd`etas`p5, 
   s`f2`o8`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f2`o8`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f2`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f2`o8`qfa`sdu`ss`\[Eta]`p5, 
   u`f2`o8`qfa`sdu`ss`etas`p5, d`f2`o8`qfb`uds`ud`\[Pi]ip`p3, 
   s`f2`o8`qfb`usd`us`\[CapitalKappa]ip`p3, u`f2`o8`qfb`dus`du`\[Pi]im`p3, 
   s`f2`o8`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f2`o8`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f2`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f2`o8`qfb`uds`ud`\[Pi]ip`p4, 
   s`f2`o8`qfb`usd`us`\[CapitalKappa]ip`p4, u`f2`o8`qfb`dus`du`\[Pi]im`p4, 
   s`f2`o8`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f2`o8`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f2`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f2`o8`qfb`uds`ud`\[Pi]ip`p5, 
   d`f2`o8`qfb`usd`us`\[CapitalKappa]ip`p5, s`f2`o8`qfb`dus`du`\[Pi]im`p5, 
   u`f2`o8`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f2`o8`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f2`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p5}}, 
 {{u`f3`o1`qfa`dsd`du`\[Pi]im`p3, d`f3`o1`qfa`dsd`dd`\[Eta]`p3, 
   d`f3`o1`qfa`dsd`dd`\[Pi]i0`p3, d`f3`o1`qfa`dsd`dd`etas`p3, 
   s`f3`o1`qfa`dsd`ds`\[CapitalKappa]i0`p3, 
   u`f3`o1`qfa`sdd`su`\[CapitalKappa]im`p3, 
   d`f3`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p3, s`f3`o1`qfa`sdd`ss`\[Eta]`p3, 
   s`f3`o1`qfa`sdd`ss`etas`p3, s`f3`o1`qfa`dsd`du`\[Pi]im`p4, 
   s`f3`o1`qfa`dsd`dd`\[Eta]`p4, s`f3`o1`qfa`dsd`dd`\[Pi]i0`p4, 
   s`f3`o1`qfa`dsd`dd`etas`p4, s`f3`o1`qfa`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f3`o1`qfa`sdd`su`\[CapitalKappa]im`p4, 
   d`f3`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p4, d`f3`o1`qfa`sdd`ss`\[Eta]`p4, 
   d`f3`o1`qfa`sdd`ss`etas`p4, d`f3`o1`qfa`dsd`du`\[Pi]im`p5, 
   d`f3`o1`qfa`dsd`dd`\[Eta]`p5, d`f3`o1`qfa`dsd`dd`\[Pi]i0`p5, 
   d`f3`o1`qfa`dsd`dd`etas`p5, d`f3`o1`qfa`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f3`o1`qfa`sdd`su`\[CapitalKappa]im`p5, 
   d`f3`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p5, d`f3`o1`qfa`sdd`ss`\[Eta]`p5, 
   d`f3`o1`qfa`sdd`ss`etas`p5, d`f3`o1`qfb`dds`dd`\[Eta]`p3, 
   d`f3`o1`qfb`dds`dd`\[Pi]i0`p3, d`f3`o1`qfb`dds`dd`etas`p3, 
   s`f3`o1`qfb`dsd`ds`\[CapitalKappa]i0`p3, 
   d`f3`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p3, d`f3`o1`qfb`dds`dd`\[Eta]`p4, 
   d`f3`o1`qfb`dds`dd`\[Pi]i0`p4, d`f3`o1`qfb`dds`dd`etas`p4, 
   s`f3`o1`qfb`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f3`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p4, s`f3`o1`qfb`dds`dd`\[Eta]`p5, 
   s`f3`o1`qfb`dds`dd`\[Pi]i0`p5, s`f3`o1`qfb`dds`dd`etas`p5, 
   d`f3`o1`qfb`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f3`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p5}, {u`f3`o2`qfa`uds`uu`\[Eta]`p3, 
   u`f3`o2`qfa`uds`uu`etas`p3, u`f3`o2`qfa`uds`uu`\[Pi]i0`p3, 
   d`f3`o2`qfa`uds`ud`\[Pi]ip`p3, s`f3`o2`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f3`o2`qfa`dus`du`\[Pi]im`p3, d`f3`o2`qfa`dus`dd`\[Eta]`p3, 
   d`f3`o2`qfa`dus`dd`etas`p3, d`f3`o2`qfa`dus`dd`\[Pi]i0`p3, 
   s`f3`o2`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f3`o2`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f3`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f3`o2`qfa`sdu`ss`\[Eta]`p3, 
   s`f3`o2`qfa`sdu`ss`etas`p3, d`f3`o2`qfa`uds`uu`\[Eta]`p4, 
   d`f3`o2`qfa`uds`uu`etas`p4, d`f3`o2`qfa`uds`uu`\[Pi]i0`p4, 
   d`f3`o2`qfa`uds`ud`\[Pi]ip`p4, d`f3`o2`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f3`o2`qfa`dus`du`\[Pi]im`p4, u`f3`o2`qfa`dus`dd`\[Eta]`p4, 
   u`f3`o2`qfa`dus`dd`etas`p4, u`f3`o2`qfa`dus`dd`\[Pi]i0`p4, 
   u`f3`o2`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f3`o2`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f3`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f3`o2`qfa`sdu`ss`\[Eta]`p4, 
   d`f3`o2`qfa`sdu`ss`etas`p4, s`f3`o2`qfa`uds`uu`\[Eta]`p5, 
   s`f3`o2`qfa`uds`uu`etas`p5, s`f3`o2`qfa`uds`uu`\[Pi]i0`p5, 
   s`f3`o2`qfa`uds`ud`\[Pi]ip`p5, s`f3`o2`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f3`o2`qfa`dus`du`\[Pi]im`p5, s`f3`o2`qfa`dus`dd`\[Eta]`p5, 
   s`f3`o2`qfa`dus`dd`etas`p5, s`f3`o2`qfa`dus`dd`\[Pi]i0`p5, 
   s`f3`o2`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f3`o2`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f3`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f3`o2`qfa`sdu`ss`\[Eta]`p5, 
   u`f3`o2`qfa`sdu`ss`etas`p5, d`f3`o2`qfb`uds`ud`\[Pi]ip`p3, 
   s`f3`o2`qfb`usd`us`\[CapitalKappa]ip`p3, u`f3`o2`qfb`dus`du`\[Pi]im`p3, 
   s`f3`o2`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f3`o2`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f3`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f3`o2`qfb`uds`ud`\[Pi]ip`p4, 
   s`f3`o2`qfb`usd`us`\[CapitalKappa]ip`p4, u`f3`o2`qfb`dus`du`\[Pi]im`p4, 
   s`f3`o2`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f3`o2`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f3`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f3`o2`qfb`uds`ud`\[Pi]ip`p5, 
   d`f3`o2`qfb`usd`us`\[CapitalKappa]ip`p5, s`f3`o2`qfb`dus`du`\[Pi]im`p5, 
   u`f3`o2`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f3`o2`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f3`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p5}, {u`f3`o3`qfa`uus`uu`\[Eta]`p3, 
   u`f3`o3`qfa`uus`uu`\[Pi]i0`p3, u`f3`o3`qfa`uus`uu`etas`p3, 
   d`f3`o3`qfa`uus`ud`\[Pi]ip`p3, s`f3`o3`qfa`uus`us`\[CapitalKappa]ip`p3, 
   u`f3`o3`qfa`suu`su`\[CapitalKappa]im`p3, 
   d`f3`o3`qfa`suu`sd`\[CapitalKappa]i0b`p3, s`f3`o3`qfa`suu`ss`\[Eta]`p3, 
   s`f3`o3`qfa`suu`ss`etas`p3, u`f3`o3`qfa`uus`uu`\[Eta]`p4, 
   u`f3`o3`qfa`uus`uu`\[Pi]i0`p4, u`f3`o3`qfa`uus`uu`etas`p4, 
   u`f3`o3`qfa`uus`ud`\[Pi]ip`p4, u`f3`o3`qfa`uus`us`\[CapitalKappa]ip`p4, 
   u`f3`o3`qfa`suu`su`\[CapitalKappa]im`p4, 
   u`f3`o3`qfa`suu`sd`\[CapitalKappa]i0b`p4, u`f3`o3`qfa`suu`ss`\[Eta]`p4, 
   u`f3`o3`qfa`suu`ss`etas`p4, s`f3`o3`qfa`uus`uu`\[Eta]`p5, 
   s`f3`o3`qfa`uus`uu`\[Pi]i0`p5, s`f3`o3`qfa`uus`uu`etas`p5, 
   s`f3`o3`qfa`uus`ud`\[Pi]ip`p5, s`f3`o3`qfa`uus`us`\[CapitalKappa]ip`p5, 
   u`f3`o3`qfa`suu`su`\[CapitalKappa]im`p5, 
   u`f3`o3`qfa`suu`sd`\[CapitalKappa]i0b`p5, u`f3`o3`qfa`suu`ss`\[Eta]`p5, 
   u`f3`o3`qfa`suu`ss`etas`p5, u`f3`o3`qfb`uus`uu`\[Eta]`p3, 
   u`f3`o3`qfb`uus`uu`\[Pi]i0`p3, u`f3`o3`qfb`uus`uu`etas`p3, 
   s`f3`o3`qfb`usu`us`\[CapitalKappa]ip`p3, 
   u`f3`o3`qfb`suu`su`\[CapitalKappa]im`p3, u`f3`o3`qfb`uus`uu`\[Eta]`p4, 
   u`f3`o3`qfb`uus`uu`\[Pi]i0`p4, u`f3`o3`qfb`uus`uu`etas`p4, 
   s`f3`o3`qfb`usu`us`\[CapitalKappa]ip`p4, 
   u`f3`o3`qfb`suu`su`\[CapitalKappa]im`p4, s`f3`o3`qfb`uus`uu`\[Eta]`p5, 
   s`f3`o3`qfb`uus`uu`\[Pi]i0`p5, s`f3`o3`qfb`uus`uu`etas`p5, 
   u`f3`o3`qfb`usu`us`\[CapitalKappa]ip`p5, 
   u`f3`o3`qfb`suu`su`\[CapitalKappa]im`p5}, {u`f3`o4`qfa`udu`uu`\[Eta]`p3, 
   u`f3`o4`qfa`udu`uu`\[Pi]i0`p3, u`f3`o4`qfa`udu`uu`etas`p3, 
   d`f3`o4`qfa`udu`ud`\[Pi]ip`p3, s`f3`o4`qfa`udu`us`\[CapitalKappa]ip`p3, 
   u`f3`o4`qfa`duu`du`\[Pi]im`p3, d`f3`o4`qfa`duu`dd`\[Eta]`p3, 
   d`f3`o4`qfa`duu`dd`\[Pi]i0`p3, d`f3`o4`qfa`duu`dd`etas`p3, 
   s`f3`o4`qfa`duu`ds`\[CapitalKappa]i0`p3, d`f3`o4`qfa`udu`uu`\[Eta]`p4, 
   d`f3`o4`qfa`udu`uu`\[Pi]i0`p4, d`f3`o4`qfa`udu`uu`etas`p4, 
   d`f3`o4`qfa`udu`ud`\[Pi]ip`p4, d`f3`o4`qfa`udu`us`\[CapitalKappa]ip`p4, 
   u`f3`o4`qfa`duu`du`\[Pi]im`p4, u`f3`o4`qfa`duu`dd`\[Eta]`p4, 
   u`f3`o4`qfa`duu`dd`\[Pi]i0`p4, u`f3`o4`qfa`duu`dd`etas`p4, 
   u`f3`o4`qfa`duu`ds`\[CapitalKappa]i0`p4, u`f3`o4`qfa`udu`uu`\[Eta]`p5, 
   u`f3`o4`qfa`udu`uu`\[Pi]i0`p5, u`f3`o4`qfa`udu`uu`etas`p5, 
   u`f3`o4`qfa`udu`ud`\[Pi]ip`p5, u`f3`o4`qfa`udu`us`\[CapitalKappa]ip`p5, 
   u`f3`o4`qfa`duu`du`\[Pi]im`p5, u`f3`o4`qfa`duu`dd`\[Eta]`p5, 
   u`f3`o4`qfa`duu`dd`\[Pi]i0`p5, u`f3`o4`qfa`duu`dd`etas`p5, 
   u`f3`o4`qfa`duu`ds`\[CapitalKappa]i0`p5, u`f3`o4`qfb`uud`uu`\[Eta]`p3, 
   u`f3`o4`qfb`uud`uu`\[Pi]i0`p3, u`f3`o4`qfb`uud`uu`etas`p3, 
   d`f3`o4`qfb`udu`ud`\[Pi]ip`p3, u`f3`o4`qfb`duu`du`\[Pi]im`p3, 
   u`f3`o4`qfb`uud`uu`\[Eta]`p4, u`f3`o4`qfb`uud`uu`\[Pi]i0`p4, 
   u`f3`o4`qfb`uud`uu`etas`p4, d`f3`o4`qfb`udu`ud`\[Pi]ip`p4, 
   u`f3`o4`qfb`duu`du`\[Pi]im`p4, d`f3`o4`qfb`uud`uu`\[Eta]`p5, 
   d`f3`o4`qfb`uud`uu`\[Pi]i0`p5, d`f3`o4`qfb`uud`uu`etas`p5, 
   u`f3`o4`qfb`udu`ud`\[Pi]ip`p5, u`f3`o4`qfb`duu`du`\[Pi]im`p5}, 
  {u`f3`o5`qfa`udd`uu`\[Eta]`p3, u`f3`o5`qfa`udd`uu`\[Pi]i0`p3, 
   u`f3`o5`qfa`udd`uu`etas`p3, d`f3`o5`qfa`udd`ud`\[Pi]ip`p3, 
   s`f3`o5`qfa`udd`us`\[CapitalKappa]ip`p3, u`f3`o5`qfa`ddu`du`\[Pi]im`p3, 
   d`f3`o5`qfa`ddu`dd`\[Eta]`p3, d`f3`o5`qfa`ddu`dd`\[Pi]i0`p3, 
   d`f3`o5`qfa`ddu`dd`etas`p3, s`f3`o5`qfa`ddu`ds`\[CapitalKappa]i0`p3, 
   d`f3`o5`qfa`udd`uu`\[Eta]`p4, d`f3`o5`qfa`udd`uu`\[Pi]i0`p4, 
   d`f3`o5`qfa`udd`uu`etas`p4, d`f3`o5`qfa`udd`ud`\[Pi]ip`p4, 
   d`f3`o5`qfa`udd`us`\[CapitalKappa]ip`p4, d`f3`o5`qfa`ddu`du`\[Pi]im`p4, 
   d`f3`o5`qfa`ddu`dd`\[Eta]`p4, d`f3`o5`qfa`ddu`dd`\[Pi]i0`p4, 
   d`f3`o5`qfa`ddu`dd`etas`p4, d`f3`o5`qfa`ddu`ds`\[CapitalKappa]i0`p4, 
   d`f3`o5`qfa`udd`uu`\[Eta]`p5, d`f3`o5`qfa`udd`uu`\[Pi]i0`p5, 
   d`f3`o5`qfa`udd`uu`etas`p5, d`f3`o5`qfa`udd`ud`\[Pi]ip`p5, 
   d`f3`o5`qfa`udd`us`\[CapitalKappa]ip`p5, u`f3`o5`qfa`ddu`du`\[Pi]im`p5, 
   u`f3`o5`qfa`ddu`dd`\[Eta]`p5, u`f3`o5`qfa`ddu`dd`\[Pi]i0`p5, 
   u`f3`o5`qfa`ddu`dd`etas`p5, u`f3`o5`qfa`ddu`ds`\[CapitalKappa]i0`p5, 
   d`f3`o5`qfb`udd`ud`\[Pi]ip`p3, u`f3`o5`qfb`dud`du`\[Pi]im`p3, 
   d`f3`o5`qfb`ddu`dd`\[Eta]`p3, d`f3`o5`qfb`ddu`dd`\[Pi]i0`p3, 
   d`f3`o5`qfb`ddu`dd`etas`p3, d`f3`o5`qfb`udd`ud`\[Pi]ip`p4, 
   u`f3`o5`qfb`dud`du`\[Pi]im`p4, d`f3`o5`qfb`ddu`dd`\[Eta]`p4, 
   d`f3`o5`qfb`ddu`dd`\[Pi]i0`p4, d`f3`o5`qfb`ddu`dd`etas`p4, 
   d`f3`o5`qfb`udd`ud`\[Pi]ip`p5, d`f3`o5`qfb`dud`du`\[Pi]im`p5, 
   u`f3`o5`qfb`ddu`dd`\[Eta]`p5, u`f3`o5`qfb`ddu`dd`\[Pi]i0`p5, 
   u`f3`o5`qfb`ddu`dd`etas`p5}, {u`f3`o6`qfa`dss`du`\[Pi]im`p3, 
   d`f3`o6`qfa`dss`dd`\[Eta]`p3, d`f3`o6`qfa`dss`dd`\[Pi]i0`p3, 
   d`f3`o6`qfa`dss`dd`etas`p3, s`f3`o6`qfa`dss`ds`\[CapitalKappa]i0`p3, 
   u`f3`o6`qfa`ssd`su`\[CapitalKappa]im`p3, 
   d`f3`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p3, s`f3`o6`qfa`ssd`ss`\[Eta]`p3, 
   s`f3`o6`qfa`ssd`ss`etas`p3, s`f3`o6`qfa`dss`du`\[Pi]im`p4, 
   s`f3`o6`qfa`dss`dd`\[Eta]`p4, s`f3`o6`qfa`dss`dd`\[Pi]i0`p4, 
   s`f3`o6`qfa`dss`dd`etas`p4, s`f3`o6`qfa`dss`ds`\[CapitalKappa]i0`p4, 
   s`f3`o6`qfa`ssd`su`\[CapitalKappa]im`p4, 
   s`f3`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p4, s`f3`o6`qfa`ssd`ss`\[Eta]`p4, 
   s`f3`o6`qfa`ssd`ss`etas`p4, s`f3`o6`qfa`dss`du`\[Pi]im`p5, 
   s`f3`o6`qfa`dss`dd`\[Eta]`p5, s`f3`o6`qfa`dss`dd`\[Pi]i0`p5, 
   s`f3`o6`qfa`dss`dd`etas`p5, s`f3`o6`qfa`dss`ds`\[CapitalKappa]i0`p5, 
   d`f3`o6`qfa`ssd`su`\[CapitalKappa]im`p5, 
   d`f3`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p5, d`f3`o6`qfa`ssd`ss`\[Eta]`p5, 
   d`f3`o6`qfa`ssd`ss`etas`p5, s`f3`o6`qfb`dss`ds`\[CapitalKappa]i0`p3, 
   d`f3`o6`qfb`sds`sd`\[CapitalKappa]i0b`p3, s`f3`o6`qfb`ssd`ss`\[Eta]`p3, 
   s`f3`o6`qfb`ssd`ss`etas`p3, s`f3`o6`qfb`dss`ds`\[CapitalKappa]i0`p4, 
   d`f3`o6`qfb`sds`sd`\[CapitalKappa]i0b`p4, s`f3`o6`qfb`ssd`ss`\[Eta]`p4, 
   s`f3`o6`qfb`ssd`ss`etas`p4, s`f3`o6`qfb`dss`ds`\[CapitalKappa]i0`p5, 
   s`f3`o6`qfb`sds`sd`\[CapitalKappa]i0b`p5, d`f3`o6`qfb`ssd`ss`\[Eta]`p5, 
   d`f3`o6`qfb`ssd`ss`etas`p5}, {u`f3`o7`qfa`uss`uu`\[Eta]`p3, 
   u`f3`o7`qfa`uss`uu`\[Pi]i0`p3, u`f3`o7`qfa`uss`uu`etas`p3, 
   d`f3`o7`qfa`uss`ud`\[Pi]ip`p3, s`f3`o7`qfa`uss`us`\[CapitalKappa]ip`p3, 
   u`f3`o7`qfa`sus`su`\[CapitalKappa]im`p3, 
   d`f3`o7`qfa`sus`sd`\[CapitalKappa]i0b`p3, s`f3`o7`qfa`sus`ss`\[Eta]`p3, 
   s`f3`o7`qfa`sus`ss`etas`p3, s`f3`o7`qfa`uss`uu`\[Eta]`p4, 
   s`f3`o7`qfa`uss`uu`\[Pi]i0`p4, s`f3`o7`qfa`uss`uu`etas`p4, 
   s`f3`o7`qfa`uss`ud`\[Pi]ip`p4, s`f3`o7`qfa`uss`us`\[CapitalKappa]ip`p4, 
   u`f3`o7`qfa`sus`su`\[CapitalKappa]im`p4, 
   u`f3`o7`qfa`sus`sd`\[CapitalKappa]i0b`p4, u`f3`o7`qfa`sus`ss`\[Eta]`p4, 
   u`f3`o7`qfa`sus`ss`etas`p4, s`f3`o7`qfa`uss`uu`\[Eta]`p5, 
   s`f3`o7`qfa`uss`uu`\[Pi]i0`p5, s`f3`o7`qfa`uss`uu`etas`p5, 
   s`f3`o7`qfa`uss`ud`\[Pi]ip`p5, s`f3`o7`qfa`uss`us`\[CapitalKappa]ip`p5, 
   s`f3`o7`qfa`sus`su`\[CapitalKappa]im`p5, 
   s`f3`o7`qfa`sus`sd`\[CapitalKappa]i0b`p5, s`f3`o7`qfa`sus`ss`\[Eta]`p5, 
   s`f3`o7`qfa`sus`ss`etas`p5, s`f3`o7`qfb`uss`us`\[CapitalKappa]ip`p3, 
   u`f3`o7`qfb`sus`su`\[CapitalKappa]im`p3, s`f3`o7`qfb`ssu`ss`\[Eta]`p3, 
   s`f3`o7`qfb`ssu`ss`etas`p3, s`f3`o7`qfb`uss`us`\[CapitalKappa]ip`p4, 
   u`f3`o7`qfb`sus`su`\[CapitalKappa]im`p4, s`f3`o7`qfb`ssu`ss`\[Eta]`p4, 
   s`f3`o7`qfb`ssu`ss`etas`p4, s`f3`o7`qfb`uss`us`\[CapitalKappa]ip`p5, 
   s`f3`o7`qfb`sus`su`\[CapitalKappa]im`p5, u`f3`o7`qfb`ssu`ss`\[Eta]`p5, 
   u`f3`o7`qfb`ssu`ss`etas`p5}, {u`f3`o8`qfa`uds`uu`\[Pi]i0`p3, 
   u`f3`o8`qfa`uds`uu`\[Eta]`p3, u`f3`o8`qfa`uds`uu`etas`p3, 
   d`f3`o8`qfa`uds`ud`\[Pi]ip`p3, s`f3`o8`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f3`o8`qfa`dus`du`\[Pi]im`p3, d`f3`o8`qfa`dus`dd`\[Pi]i0`p3, 
   d`f3`o8`qfa`dus`dd`\[Eta]`p3, d`f3`o8`qfa`dus`dd`etas`p3, 
   s`f3`o8`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f3`o8`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f3`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f3`o8`qfa`sdu`ss`\[Eta]`p3, 
   s`f3`o8`qfa`sdu`ss`etas`p3, d`f3`o8`qfa`uds`uu`\[Pi]i0`p4, 
   d`f3`o8`qfa`uds`uu`\[Eta]`p4, d`f3`o8`qfa`uds`uu`etas`p4, 
   d`f3`o8`qfa`uds`ud`\[Pi]ip`p4, d`f3`o8`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f3`o8`qfa`dus`du`\[Pi]im`p4, u`f3`o8`qfa`dus`dd`\[Pi]i0`p4, 
   u`f3`o8`qfa`dus`dd`\[Eta]`p4, u`f3`o8`qfa`dus`dd`etas`p4, 
   u`f3`o8`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f3`o8`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f3`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f3`o8`qfa`sdu`ss`\[Eta]`p4, 
   d`f3`o8`qfa`sdu`ss`etas`p4, s`f3`o8`qfa`uds`uu`\[Pi]i0`p5, 
   s`f3`o8`qfa`uds`uu`\[Eta]`p5, s`f3`o8`qfa`uds`uu`etas`p5, 
   s`f3`o8`qfa`uds`ud`\[Pi]ip`p5, s`f3`o8`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f3`o8`qfa`dus`du`\[Pi]im`p5, s`f3`o8`qfa`dus`dd`\[Pi]i0`p5, 
   s`f3`o8`qfa`dus`dd`\[Eta]`p5, s`f3`o8`qfa`dus`dd`etas`p5, 
   s`f3`o8`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f3`o8`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f3`o8`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f3`o8`qfa`sdu`ss`\[Eta]`p5, 
   u`f3`o8`qfa`sdu`ss`etas`p5, d`f3`o8`qfb`uds`ud`\[Pi]ip`p3, 
   s`f3`o8`qfb`usd`us`\[CapitalKappa]ip`p3, u`f3`o8`qfb`dus`du`\[Pi]im`p3, 
   s`f3`o8`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f3`o8`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f3`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f3`o8`qfb`uds`ud`\[Pi]ip`p4, 
   s`f3`o8`qfb`usd`us`\[CapitalKappa]ip`p4, u`f3`o8`qfb`dus`du`\[Pi]im`p4, 
   s`f3`o8`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f3`o8`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f3`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f3`o8`qfb`uds`ud`\[Pi]ip`p5, 
   d`f3`o8`qfb`usd`us`\[CapitalKappa]ip`p5, s`f3`o8`qfb`dus`du`\[Pi]im`p5, 
   u`f3`o8`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f3`o8`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f3`o8`qfb`sdu`sd`\[CapitalKappa]i0b`p5}}, 
 {{d`f4`o1`qfa`dsd`du`\[Pi]im`p1, d`f4`o1`qfa`dsd`dd`\[Eta]`p1, 
   d`f4`o1`qfa`dsd`dd`\[Pi]i0`p1, d`f4`o1`qfa`dsd`dd`etas`p1, 
   d`f4`o1`qfa`dsd`ds`\[CapitalKappa]i0`p1, 
   s`f4`o1`qfa`sdd`su`\[CapitalKappa]im`p1, 
   s`f4`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p1, s`f4`o1`qfa`sdd`ss`\[Eta]`p1, 
   s`f4`o1`qfa`sdd`ss`etas`p1, u`f4`o1`qfa`dsd`du`\[Pi]im`p2, 
   d`f4`o1`qfa`dsd`dd`\[Eta]`p2, d`f4`o1`qfa`dsd`dd`\[Pi]i0`p2, 
   d`f4`o1`qfa`dsd`dd`etas`p2, s`f4`o1`qfa`dsd`ds`\[CapitalKappa]i0`p2, 
   u`f4`o1`qfa`sdd`su`\[CapitalKappa]im`p2, 
   d`f4`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p2, s`f4`o1`qfa`sdd`ss`\[Eta]`p2, 
   s`f4`o1`qfa`sdd`ss`etas`p2, d`f4`o1`qfb`dds`dd`\[Eta]`p1, 
   d`f4`o1`qfb`dds`dd`\[Pi]i0`p1, d`f4`o1`qfb`dds`dd`etas`p1, 
   d`f4`o1`qfb`dsd`ds`\[CapitalKappa]i0`p1, 
   s`f4`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p1, d`f4`o1`qfb`dds`dd`\[Eta]`p2, 
   d`f4`o1`qfb`dds`dd`\[Pi]i0`p2, d`f4`o1`qfb`dds`dd`etas`p2, 
   s`f4`o1`qfb`dsd`ds`\[CapitalKappa]i0`p2, 
   d`f4`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p2}, {u`f4`o2`qfa`uds`uu`\[Eta]`p1, 
   u`f4`o2`qfa`uds`uu`etas`p1, u`f4`o2`qfa`uds`ud`\[Pi]ip`p1, 
   u`f4`o2`qfa`uds`us`\[CapitalKappa]ip`p1, d`f4`o2`qfa`dus`du`\[Pi]im`p1, 
   d`f4`o2`qfa`dus`dd`\[Eta]`p1, d`f4`o2`qfa`dus`dd`etas`p1, 
   d`f4`o2`qfa`dus`ds`\[CapitalKappa]i0`p1, 
   s`f4`o2`qfa`sdu`su`\[CapitalKappa]im`p1, 
   s`f4`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p1, s`f4`o2`qfa`sdu`ss`\[Eta]`p1, 
   s`f4`o2`qfa`sdu`ss`etas`p1, u`f4`o2`qfa`uds`uu`\[Eta]`p2, 
   u`f4`o2`qfa`uds`uu`etas`p2, d`f4`o2`qfa`uds`ud`\[Pi]ip`p2, 
   s`f4`o2`qfa`uds`us`\[CapitalKappa]ip`p2, u`f4`o2`qfa`dus`du`\[Pi]im`p2, 
   d`f4`o2`qfa`dus`dd`\[Eta]`p2, d`f4`o2`qfa`dus`dd`etas`p2, 
   s`f4`o2`qfa`dus`ds`\[CapitalKappa]i0`p2, 
   u`f4`o2`qfa`sdu`su`\[CapitalKappa]im`p2, 
   d`f4`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p2, s`f4`o2`qfa`sdu`ss`\[Eta]`p2, 
   s`f4`o2`qfa`sdu`ss`etas`p2, u`f4`o2`qfb`uds`ud`\[Pi]ip`p1, 
   u`f4`o2`qfb`usd`us`\[CapitalKappa]ip`p1, d`f4`o2`qfb`dus`du`\[Pi]im`p1, 
   d`f4`o2`qfb`dsu`ds`\[CapitalKappa]i0`p1, 
   s`f4`o2`qfb`sud`su`\[CapitalKappa]im`p1, 
   s`f4`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p1, d`f4`o2`qfb`uds`ud`\[Pi]ip`p2, 
   s`f4`o2`qfb`usd`us`\[CapitalKappa]ip`p2, u`f4`o2`qfb`dus`du`\[Pi]im`p2, 
   s`f4`o2`qfb`dsu`ds`\[CapitalKappa]i0`p2, 
   u`f4`o2`qfb`sud`su`\[CapitalKappa]im`p2, 
   d`f4`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p2}, {u`f4`o3`qfa`uus`uu`\[Eta]`p1, 
   u`f4`o3`qfa`uus`uu`\[Pi]i0`p1, u`f4`o3`qfa`uus`uu`etas`p1, 
   u`f4`o3`qfa`uus`ud`\[Pi]ip`p1, u`f4`o3`qfa`uus`us`\[CapitalKappa]ip`p1, 
   s`f4`o3`qfa`suu`su`\[CapitalKappa]im`p1, 
   s`f4`o3`qfa`suu`sd`\[CapitalKappa]i0b`p1, s`f4`o3`qfa`suu`ss`\[Eta]`p1, 
   s`f4`o3`qfa`suu`ss`etas`p1, u`f4`o3`qfa`uus`uu`\[Eta]`p2, 
   u`f4`o3`qfa`uus`uu`\[Pi]i0`p2, u`f4`o3`qfa`uus`uu`etas`p2, 
   d`f4`o3`qfa`uus`ud`\[Pi]ip`p2, s`f4`o3`qfa`uus`us`\[CapitalKappa]ip`p2, 
   u`f4`o3`qfa`suu`su`\[CapitalKappa]im`p2, 
   d`f4`o3`qfa`suu`sd`\[CapitalKappa]i0b`p2, s`f4`o3`qfa`suu`ss`\[Eta]`p2, 
   s`f4`o3`qfa`suu`ss`etas`p2, u`f4`o3`qfb`uus`uu`\[Eta]`p1, 
   u`f4`o3`qfb`uus`uu`\[Pi]i0`p1, u`f4`o3`qfb`uus`uu`etas`p1, 
   u`f4`o3`qfb`usu`us`\[CapitalKappa]ip`p1, 
   s`f4`o3`qfb`suu`su`\[CapitalKappa]im`p1, u`f4`o3`qfb`uus`uu`\[Eta]`p2, 
   u`f4`o3`qfb`uus`uu`\[Pi]i0`p2, u`f4`o3`qfb`uus`uu`etas`p2, 
   s`f4`o3`qfb`usu`us`\[CapitalKappa]ip`p2, 
   u`f4`o3`qfb`suu`su`\[CapitalKappa]im`p2}, {u`f4`o4`qfa`udu`uu`\[Pi]i0`p1, 
   u`f4`o4`qfa`udu`ud`\[Pi]ip`p1, u`f4`o4`qfa`udu`us`\[CapitalKappa]ip`p1, 
   d`f4`o4`qfa`duu`du`\[Pi]im`p1, d`f4`o4`qfa`duu`dd`\[Pi]i0`p1, 
   d`f4`o4`qfa`duu`ds`\[CapitalKappa]i0`p1, u`f4`o4`qfa`udu`uu`\[Pi]i0`p2, 
   d`f4`o4`qfa`udu`ud`\[Pi]ip`p2, s`f4`o4`qfa`udu`us`\[CapitalKappa]ip`p2, 
   u`f4`o4`qfa`duu`du`\[Pi]im`p2, d`f4`o4`qfa`duu`dd`\[Pi]i0`p2, 
   s`f4`o4`qfa`duu`ds`\[CapitalKappa]i0`p2, u`f4`o4`qfb`uud`uu`\[Pi]i0`p1, 
   u`f4`o4`qfb`udu`ud`\[Pi]ip`p1, d`f4`o4`qfb`duu`du`\[Pi]im`p1, 
   u`f4`o4`qfb`uud`uu`\[Pi]i0`p2, d`f4`o4`qfb`udu`ud`\[Pi]ip`p2, 
   u`f4`o4`qfb`duu`du`\[Pi]im`p2}, {u`f4`o5`qfa`udd`uu`\[Pi]i0`p1, 
   u`f4`o5`qfa`udd`ud`\[Pi]ip`p1, u`f4`o5`qfa`udd`us`\[CapitalKappa]ip`p1, 
   d`f4`o5`qfa`ddu`du`\[Pi]im`p1, d`f4`o5`qfa`ddu`dd`\[Pi]i0`p1, 
   d`f4`o5`qfa`ddu`ds`\[CapitalKappa]i0`p1, u`f4`o5`qfa`udd`uu`\[Pi]i0`p2, 
   d`f4`o5`qfa`udd`ud`\[Pi]ip`p2, s`f4`o5`qfa`udd`us`\[CapitalKappa]ip`p2, 
   u`f4`o5`qfa`ddu`du`\[Pi]im`p2, d`f4`o5`qfa`ddu`dd`\[Pi]i0`p2, 
   s`f4`o5`qfa`ddu`ds`\[CapitalKappa]i0`p2, u`f4`o5`qfb`udd`ud`\[Pi]ip`p1, 
   d`f4`o5`qfb`dud`du`\[Pi]im`p1, d`f4`o5`qfb`ddu`dd`\[Pi]i0`p1, 
   d`f4`o5`qfb`udd`ud`\[Pi]ip`p2, u`f4`o5`qfb`dud`du`\[Pi]im`p2, 
   d`f4`o5`qfb`ddu`dd`\[Pi]i0`p2}, {d`f4`o6`qfa`dss`du`\[Pi]im`p1, 
   d`f4`o6`qfa`dss`dd`\[Eta]`p1, d`f4`o6`qfa`dss`dd`\[Pi]i0`p1, 
   d`f4`o6`qfa`dss`dd`etas`p1, d`f4`o6`qfa`dss`ds`\[CapitalKappa]i0`p1, 
   s`f4`o6`qfa`ssd`su`\[CapitalKappa]im`p1, 
   s`f4`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p1, s`f4`o6`qfa`ssd`ss`\[Eta]`p1, 
   s`f4`o6`qfa`ssd`ss`etas`p1, u`f4`o6`qfa`dss`du`\[Pi]im`p2, 
   d`f4`o6`qfa`dss`dd`\[Eta]`p2, d`f4`o6`qfa`dss`dd`\[Pi]i0`p2, 
   d`f4`o6`qfa`dss`dd`etas`p2, s`f4`o6`qfa`dss`ds`\[CapitalKappa]i0`p2, 
   u`f4`o6`qfa`ssd`su`\[CapitalKappa]im`p2, 
   d`f4`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p2, s`f4`o6`qfa`ssd`ss`\[Eta]`p2, 
   s`f4`o6`qfa`ssd`ss`etas`p2, d`f4`o6`qfb`dss`ds`\[CapitalKappa]i0`p1, 
   s`f4`o6`qfb`sds`sd`\[CapitalKappa]i0b`p1, s`f4`o6`qfb`ssd`ss`\[Eta]`p1, 
   s`f4`o6`qfb`ssd`ss`etas`p1, s`f4`o6`qfb`dss`ds`\[CapitalKappa]i0`p2, 
   d`f4`o6`qfb`sds`sd`\[CapitalKappa]i0b`p2, s`f4`o6`qfb`ssd`ss`\[Eta]`p2, 
   s`f4`o6`qfb`ssd`ss`etas`p2}, {u`f4`o7`qfa`uss`uu`\[Eta]`p1, 
   u`f4`o7`qfa`uss`uu`\[Pi]i0`p1, u`f4`o7`qfa`uss`uu`etas`p1, 
   u`f4`o7`qfa`uss`ud`\[Pi]ip`p1, u`f4`o7`qfa`uss`us`\[CapitalKappa]ip`p1, 
   s`f4`o7`qfa`sus`su`\[CapitalKappa]im`p1, 
   s`f4`o7`qfa`sus`sd`\[CapitalKappa]i0b`p1, s`f4`o7`qfa`sus`ss`\[Eta]`p1, 
   s`f4`o7`qfa`sus`ss`etas`p1, u`f4`o7`qfa`uss`uu`\[Eta]`p2, 
   u`f4`o7`qfa`uss`uu`\[Pi]i0`p2, u`f4`o7`qfa`uss`uu`etas`p2, 
   d`f4`o7`qfa`uss`ud`\[Pi]ip`p2, s`f4`o7`qfa`uss`us`\[CapitalKappa]ip`p2, 
   u`f4`o7`qfa`sus`su`\[CapitalKappa]im`p2, 
   d`f4`o7`qfa`sus`sd`\[CapitalKappa]i0b`p2, s`f4`o7`qfa`sus`ss`\[Eta]`p2, 
   s`f4`o7`qfa`sus`ss`etas`p2, u`f4`o7`qfb`uss`us`\[CapitalKappa]ip`p1, 
   s`f4`o7`qfb`sus`su`\[CapitalKappa]im`p1, s`f4`o7`qfb`ssu`ss`\[Eta]`p1, 
   s`f4`o7`qfb`ssu`ss`etas`p1, s`f4`o7`qfb`uss`us`\[CapitalKappa]ip`p2, 
   u`f4`o7`qfb`sus`su`\[CapitalKappa]im`p2, s`f4`o7`qfb`ssu`ss`\[Eta]`p2, 
   s`f4`o7`qfb`ssu`ss`etas`p2}, {u`f4`o8`qfa`uds`uu`\[Pi]i0`p1, 
   u`f4`o8`qfa`uds`ud`\[Pi]ip`p1, u`f4`o8`qfa`uds`us`\[CapitalKappa]ip`p1, 
   d`f4`o8`qfa`dus`du`\[Pi]im`p1, d`f4`o8`qfa`dus`dd`\[Pi]i0`p1, 
   d`f4`o8`qfa`dus`ds`\[CapitalKappa]i0`p1, u`f4`o8`qfa`uds`uu`\[Pi]i0`p2, 
   d`f4`o8`qfa`uds`ud`\[Pi]ip`p2, s`f4`o8`qfa`uds`us`\[CapitalKappa]ip`p2, 
   u`f4`o8`qfa`dus`du`\[Pi]im`p2, d`f4`o8`qfa`dus`dd`\[Pi]i0`p2, 
   s`f4`o8`qfa`dus`ds`\[CapitalKappa]i0`p2, u`f4`o8`qfb`uds`ud`\[Pi]ip`p1, 
   u`f4`o8`qfb`usd`us`\[CapitalKappa]ip`p1, d`f4`o8`qfb`dus`du`\[Pi]im`p1, 
   d`f4`o8`qfb`dsu`ds`\[CapitalKappa]i0`p1, d`f4`o8`qfb`uds`ud`\[Pi]ip`p2, 
   s`f4`o8`qfb`usd`us`\[CapitalKappa]ip`p2, u`f4`o8`qfb`dus`du`\[Pi]im`p2, 
   s`f4`o8`qfb`dsu`ds`\[CapitalKappa]i0`p2}}, 
 {{u`f5`o1`qfa`dsd`du`\[Pi]im`p3, d`f5`o1`qfa`dsd`dd`\[Eta]`p3, 
   d`f5`o1`qfa`dsd`dd`\[Pi]i0`p3, d`f5`o1`qfa`dsd`dd`etas`p3, 
   s`f5`o1`qfa`dsd`ds`\[CapitalKappa]i0`p3, 
   u`f5`o1`qfa`sdd`su`\[CapitalKappa]im`p3, 
   d`f5`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p3, s`f5`o1`qfa`sdd`ss`\[Eta]`p3, 
   s`f5`o1`qfa`sdd`ss`etas`p3, s`f5`o1`qfa`dsd`du`\[Pi]im`p4, 
   s`f5`o1`qfa`dsd`dd`\[Eta]`p4, s`f5`o1`qfa`dsd`dd`\[Pi]i0`p4, 
   s`f5`o1`qfa`dsd`dd`etas`p4, s`f5`o1`qfa`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f5`o1`qfa`sdd`su`\[CapitalKappa]im`p4, 
   d`f5`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p4, d`f5`o1`qfa`sdd`ss`\[Eta]`p4, 
   d`f5`o1`qfa`sdd`ss`etas`p4, d`f5`o1`qfa`dsd`du`\[Pi]im`p5, 
   d`f5`o1`qfa`dsd`dd`\[Eta]`p5, d`f5`o1`qfa`dsd`dd`\[Pi]i0`p5, 
   d`f5`o1`qfa`dsd`dd`etas`p5, d`f5`o1`qfa`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f5`o1`qfa`sdd`su`\[CapitalKappa]im`p5, 
   d`f5`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p5, d`f5`o1`qfa`sdd`ss`\[Eta]`p5, 
   d`f5`o1`qfa`sdd`ss`etas`p5, d`f5`o1`qfb`dds`dd`\[Eta]`p3, 
   d`f5`o1`qfb`dds`dd`\[Pi]i0`p3, d`f5`o1`qfb`dds`dd`etas`p3, 
   s`f5`o1`qfb`dsd`ds`\[CapitalKappa]i0`p3, 
   d`f5`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p3, d`f5`o1`qfb`dds`dd`\[Eta]`p4, 
   d`f5`o1`qfb`dds`dd`\[Pi]i0`p4, d`f5`o1`qfb`dds`dd`etas`p4, 
   s`f5`o1`qfb`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f5`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p4, s`f5`o1`qfb`dds`dd`\[Eta]`p5, 
   s`f5`o1`qfb`dds`dd`\[Pi]i0`p5, s`f5`o1`qfb`dds`dd`etas`p5, 
   d`f5`o1`qfb`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f5`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p5}, {u`f5`o2`qfa`uds`uu`\[Eta]`p3, 
   u`f5`o2`qfa`uds`uu`etas`p3, d`f5`o2`qfa`uds`ud`\[Pi]ip`p3, 
   s`f5`o2`qfa`uds`us`\[CapitalKappa]ip`p3, u`f5`o2`qfa`dus`du`\[Pi]im`p3, 
   d`f5`o2`qfa`dus`dd`\[Eta]`p3, d`f5`o2`qfa`dus`dd`etas`p3, 
   s`f5`o2`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f5`o2`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f5`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f5`o2`qfa`sdu`ss`\[Eta]`p3, 
   s`f5`o2`qfa`sdu`ss`etas`p3, d`f5`o2`qfa`uds`uu`\[Eta]`p4, 
   d`f5`o2`qfa`uds`uu`etas`p4, d`f5`o2`qfa`uds`ud`\[Pi]ip`p4, 
   d`f5`o2`qfa`uds`us`\[CapitalKappa]ip`p4, u`f5`o2`qfa`dus`du`\[Pi]im`p4, 
   u`f5`o2`qfa`dus`dd`\[Eta]`p4, u`f5`o2`qfa`dus`dd`etas`p4, 
   u`f5`o2`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f5`o2`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f5`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f5`o2`qfa`sdu`ss`\[Eta]`p4, 
   d`f5`o2`qfa`sdu`ss`etas`p4, s`f5`o2`qfa`uds`uu`\[Eta]`p5, 
   s`f5`o2`qfa`uds`uu`etas`p5, s`f5`o2`qfa`uds`ud`\[Pi]ip`p5, 
   s`f5`o2`qfa`uds`us`\[CapitalKappa]ip`p5, s`f5`o2`qfa`dus`du`\[Pi]im`p5, 
   s`f5`o2`qfa`dus`dd`\[Eta]`p5, s`f5`o2`qfa`dus`dd`etas`p5, 
   s`f5`o2`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f5`o2`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f5`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f5`o2`qfa`sdu`ss`\[Eta]`p5, 
   u`f5`o2`qfa`sdu`ss`etas`p5, d`f5`o2`qfb`uds`ud`\[Pi]ip`p3, 
   s`f5`o2`qfb`usd`us`\[CapitalKappa]ip`p3, u`f5`o2`qfb`dus`du`\[Pi]im`p3, 
   s`f5`o2`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f5`o2`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f5`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f5`o2`qfb`uds`ud`\[Pi]ip`p4, 
   s`f5`o2`qfb`usd`us`\[CapitalKappa]ip`p4, u`f5`o2`qfb`dus`du`\[Pi]im`p4, 
   s`f5`o2`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f5`o2`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f5`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f5`o2`qfb`uds`ud`\[Pi]ip`p5, 
   d`f5`o2`qfb`usd`us`\[CapitalKappa]ip`p5, s`f5`o2`qfb`dus`du`\[Pi]im`p5, 
   u`f5`o2`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f5`o2`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f5`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p5}, {u`f5`o3`qfa`uus`uu`\[Eta]`p3, 
   u`f5`o3`qfa`uus`uu`\[Pi]i0`p3, u`f5`o3`qfa`uus`uu`etas`p3, 
   d`f5`o3`qfa`uus`ud`\[Pi]ip`p3, s`f5`o3`qfa`uus`us`\[CapitalKappa]ip`p3, 
   u`f5`o3`qfa`suu`su`\[CapitalKappa]im`p3, 
   d`f5`o3`qfa`suu`sd`\[CapitalKappa]i0b`p3, s`f5`o3`qfa`suu`ss`\[Eta]`p3, 
   s`f5`o3`qfa`suu`ss`etas`p3, u`f5`o3`qfa`uus`uu`\[Eta]`p4, 
   u`f5`o3`qfa`uus`uu`\[Pi]i0`p4, u`f5`o3`qfa`uus`uu`etas`p4, 
   u`f5`o3`qfa`uus`ud`\[Pi]ip`p4, u`f5`o3`qfa`uus`us`\[CapitalKappa]ip`p4, 
   u`f5`o3`qfa`suu`su`\[CapitalKappa]im`p4, 
   u`f5`o3`qfa`suu`sd`\[CapitalKappa]i0b`p4, u`f5`o3`qfa`suu`ss`\[Eta]`p4, 
   u`f5`o3`qfa`suu`ss`etas`p4, s`f5`o3`qfa`uus`uu`\[Eta]`p5, 
   s`f5`o3`qfa`uus`uu`\[Pi]i0`p5, s`f5`o3`qfa`uus`uu`etas`p5, 
   s`f5`o3`qfa`uus`ud`\[Pi]ip`p5, s`f5`o3`qfa`uus`us`\[CapitalKappa]ip`p5, 
   u`f5`o3`qfa`suu`su`\[CapitalKappa]im`p5, 
   u`f5`o3`qfa`suu`sd`\[CapitalKappa]i0b`p5, u`f5`o3`qfa`suu`ss`\[Eta]`p5, 
   u`f5`o3`qfa`suu`ss`etas`p5, u`f5`o3`qfb`uus`uu`\[Eta]`p3, 
   u`f5`o3`qfb`uus`uu`\[Pi]i0`p3, u`f5`o3`qfb`uus`uu`etas`p3, 
   s`f5`o3`qfb`usu`us`\[CapitalKappa]ip`p3, 
   u`f5`o3`qfb`suu`su`\[CapitalKappa]im`p3, u`f5`o3`qfb`uus`uu`\[Eta]`p4, 
   u`f5`o3`qfb`uus`uu`\[Pi]i0`p4, u`f5`o3`qfb`uus`uu`etas`p4, 
   s`f5`o3`qfb`usu`us`\[CapitalKappa]ip`p4, 
   u`f5`o3`qfb`suu`su`\[CapitalKappa]im`p4, s`f5`o3`qfb`uus`uu`\[Eta]`p5, 
   s`f5`o3`qfb`uus`uu`\[Pi]i0`p5, s`f5`o3`qfb`uus`uu`etas`p5, 
   u`f5`o3`qfb`usu`us`\[CapitalKappa]ip`p5, 
   u`f5`o3`qfb`suu`su`\[CapitalKappa]im`p5}, {u`f5`o4`qfa`udu`uu`\[Pi]i0`p3, 
   d`f5`o4`qfa`udu`ud`\[Pi]ip`p3, s`f5`o4`qfa`udu`us`\[CapitalKappa]ip`p3, 
   u`f5`o4`qfa`duu`du`\[Pi]im`p3, d`f5`o4`qfa`duu`dd`\[Pi]i0`p3, 
   s`f5`o4`qfa`duu`ds`\[CapitalKappa]i0`p3, d`f5`o4`qfa`udu`uu`\[Pi]i0`p4, 
   d`f5`o4`qfa`udu`ud`\[Pi]ip`p4, d`f5`o4`qfa`udu`us`\[CapitalKappa]ip`p4, 
   u`f5`o4`qfa`duu`du`\[Pi]im`p4, u`f5`o4`qfa`duu`dd`\[Pi]i0`p4, 
   u`f5`o4`qfa`duu`ds`\[CapitalKappa]i0`p4, u`f5`o4`qfa`udu`uu`\[Pi]i0`p5, 
   u`f5`o4`qfa`udu`ud`\[Pi]ip`p5, u`f5`o4`qfa`udu`us`\[CapitalKappa]ip`p5, 
   u`f5`o4`qfa`duu`du`\[Pi]im`p5, u`f5`o4`qfa`duu`dd`\[Pi]i0`p5, 
   u`f5`o4`qfa`duu`ds`\[CapitalKappa]i0`p5, u`f5`o4`qfb`uud`uu`\[Pi]i0`p3, 
   d`f5`o4`qfb`udu`ud`\[Pi]ip`p3, u`f5`o4`qfb`duu`du`\[Pi]im`p3, 
   u`f5`o4`qfb`uud`uu`\[Pi]i0`p4, d`f5`o4`qfb`udu`ud`\[Pi]ip`p4, 
   u`f5`o4`qfb`duu`du`\[Pi]im`p4, d`f5`o4`qfb`uud`uu`\[Pi]i0`p5, 
   u`f5`o4`qfb`udu`ud`\[Pi]ip`p5, u`f5`o4`qfb`duu`du`\[Pi]im`p5}, 
  {u`f5`o5`qfa`udd`uu`\[Pi]i0`p3, d`f5`o5`qfa`udd`ud`\[Pi]ip`p3, 
   s`f5`o5`qfa`udd`us`\[CapitalKappa]ip`p3, u`f5`o5`qfa`ddu`du`\[Pi]im`p3, 
   d`f5`o5`qfa`ddu`dd`\[Pi]i0`p3, s`f5`o5`qfa`ddu`ds`\[CapitalKappa]i0`p3, 
   d`f5`o5`qfa`udd`uu`\[Pi]i0`p4, d`f5`o5`qfa`udd`ud`\[Pi]ip`p4, 
   d`f5`o5`qfa`udd`us`\[CapitalKappa]ip`p4, d`f5`o5`qfa`ddu`du`\[Pi]im`p4, 
   d`f5`o5`qfa`ddu`dd`\[Pi]i0`p4, d`f5`o5`qfa`ddu`ds`\[CapitalKappa]i0`p4, 
   d`f5`o5`qfa`udd`uu`\[Pi]i0`p5, d`f5`o5`qfa`udd`ud`\[Pi]ip`p5, 
   d`f5`o5`qfa`udd`us`\[CapitalKappa]ip`p5, u`f5`o5`qfa`ddu`du`\[Pi]im`p5, 
   u`f5`o5`qfa`ddu`dd`\[Pi]i0`p5, u`f5`o5`qfa`ddu`ds`\[CapitalKappa]i0`p5, 
   d`f5`o5`qfb`udd`ud`\[Pi]ip`p3, u`f5`o5`qfb`dud`du`\[Pi]im`p3, 
   d`f5`o5`qfb`ddu`dd`\[Pi]i0`p3, d`f5`o5`qfb`udd`ud`\[Pi]ip`p4, 
   u`f5`o5`qfb`dud`du`\[Pi]im`p4, d`f5`o5`qfb`ddu`dd`\[Pi]i0`p4, 
   d`f5`o5`qfb`udd`ud`\[Pi]ip`p5, d`f5`o5`qfb`dud`du`\[Pi]im`p5, 
   u`f5`o5`qfb`ddu`dd`\[Pi]i0`p5}, {u`f5`o6`qfa`dss`du`\[Pi]im`p3, 
   d`f5`o6`qfa`dss`dd`\[Eta]`p3, d`f5`o6`qfa`dss`dd`\[Pi]i0`p3, 
   d`f5`o6`qfa`dss`dd`etas`p3, s`f5`o6`qfa`dss`ds`\[CapitalKappa]i0`p3, 
   u`f5`o6`qfa`ssd`su`\[CapitalKappa]im`p3, 
   d`f5`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p3, s`f5`o6`qfa`ssd`ss`\[Eta]`p3, 
   s`f5`o6`qfa`ssd`ss`etas`p3, s`f5`o6`qfa`dss`du`\[Pi]im`p4, 
   s`f5`o6`qfa`dss`dd`\[Eta]`p4, s`f5`o6`qfa`dss`dd`\[Pi]i0`p4, 
   s`f5`o6`qfa`dss`dd`etas`p4, s`f5`o6`qfa`dss`ds`\[CapitalKappa]i0`p4, 
   s`f5`o6`qfa`ssd`su`\[CapitalKappa]im`p4, 
   s`f5`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p4, s`f5`o6`qfa`ssd`ss`\[Eta]`p4, 
   s`f5`o6`qfa`ssd`ss`etas`p4, s`f5`o6`qfa`dss`du`\[Pi]im`p5, 
   s`f5`o6`qfa`dss`dd`\[Eta]`p5, s`f5`o6`qfa`dss`dd`\[Pi]i0`p5, 
   s`f5`o6`qfa`dss`dd`etas`p5, s`f5`o6`qfa`dss`ds`\[CapitalKappa]i0`p5, 
   d`f5`o6`qfa`ssd`su`\[CapitalKappa]im`p5, 
   d`f5`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p5, d`f5`o6`qfa`ssd`ss`\[Eta]`p5, 
   d`f5`o6`qfa`ssd`ss`etas`p5, s`f5`o6`qfb`dss`ds`\[CapitalKappa]i0`p3, 
   d`f5`o6`qfb`sds`sd`\[CapitalKappa]i0b`p3, s`f5`o6`qfb`ssd`ss`\[Eta]`p3, 
   s`f5`o6`qfb`ssd`ss`etas`p3, s`f5`o6`qfb`dss`ds`\[CapitalKappa]i0`p4, 
   d`f5`o6`qfb`sds`sd`\[CapitalKappa]i0b`p4, s`f5`o6`qfb`ssd`ss`\[Eta]`p4, 
   s`f5`o6`qfb`ssd`ss`etas`p4, s`f5`o6`qfb`dss`ds`\[CapitalKappa]i0`p5, 
   s`f5`o6`qfb`sds`sd`\[CapitalKappa]i0b`p5, d`f5`o6`qfb`ssd`ss`\[Eta]`p5, 
   d`f5`o6`qfb`ssd`ss`etas`p5}, {u`f5`o7`qfa`uss`uu`\[Eta]`p3, 
   u`f5`o7`qfa`uss`uu`\[Pi]i0`p3, u`f5`o7`qfa`uss`uu`etas`p3, 
   d`f5`o7`qfa`uss`ud`\[Pi]ip`p3, s`f5`o7`qfa`uss`us`\[CapitalKappa]ip`p3, 
   u`f5`o7`qfa`sus`su`\[CapitalKappa]im`p3, 
   d`f5`o7`qfa`sus`sd`\[CapitalKappa]i0b`p3, s`f5`o7`qfa`sus`ss`\[Eta]`p3, 
   s`f5`o7`qfa`sus`ss`etas`p3, s`f5`o7`qfa`uss`uu`\[Eta]`p4, 
   s`f5`o7`qfa`uss`uu`\[Pi]i0`p4, s`f5`o7`qfa`uss`uu`etas`p4, 
   s`f5`o7`qfa`uss`ud`\[Pi]ip`p4, s`f5`o7`qfa`uss`us`\[CapitalKappa]ip`p4, 
   u`f5`o7`qfa`sus`su`\[CapitalKappa]im`p4, 
   u`f5`o7`qfa`sus`sd`\[CapitalKappa]i0b`p4, u`f5`o7`qfa`sus`ss`\[Eta]`p4, 
   u`f5`o7`qfa`sus`ss`etas`p4, s`f5`o7`qfa`uss`uu`\[Eta]`p5, 
   s`f5`o7`qfa`uss`uu`\[Pi]i0`p5, s`f5`o7`qfa`uss`uu`etas`p5, 
   s`f5`o7`qfa`uss`ud`\[Pi]ip`p5, s`f5`o7`qfa`uss`us`\[CapitalKappa]ip`p5, 
   s`f5`o7`qfa`sus`su`\[CapitalKappa]im`p5, 
   s`f5`o7`qfa`sus`sd`\[CapitalKappa]i0b`p5, s`f5`o7`qfa`sus`ss`\[Eta]`p5, 
   s`f5`o7`qfa`sus`ss`etas`p5, s`f5`o7`qfb`uss`us`\[CapitalKappa]ip`p3, 
   u`f5`o7`qfb`sus`su`\[CapitalKappa]im`p3, s`f5`o7`qfb`ssu`ss`\[Eta]`p3, 
   s`f5`o7`qfb`ssu`ss`etas`p3, s`f5`o7`qfb`uss`us`\[CapitalKappa]ip`p4, 
   u`f5`o7`qfb`sus`su`\[CapitalKappa]im`p4, s`f5`o7`qfb`ssu`ss`\[Eta]`p4, 
   s`f5`o7`qfb`ssu`ss`etas`p4, s`f5`o7`qfb`uss`us`\[CapitalKappa]ip`p5, 
   s`f5`o7`qfb`sus`su`\[CapitalKappa]im`p5, u`f5`o7`qfb`ssu`ss`\[Eta]`p5, 
   u`f5`o7`qfb`ssu`ss`etas`p5}, {u`f5`o8`qfa`uds`uu`\[Pi]i0`p3, 
   d`f5`o8`qfa`uds`ud`\[Pi]ip`p3, s`f5`o8`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f5`o8`qfa`dus`du`\[Pi]im`p3, d`f5`o8`qfa`dus`dd`\[Pi]i0`p3, 
   s`f5`o8`qfa`dus`ds`\[CapitalKappa]i0`p3, d`f5`o8`qfa`uds`uu`\[Pi]i0`p4, 
   d`f5`o8`qfa`uds`ud`\[Pi]ip`p4, d`f5`o8`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f5`o8`qfa`dus`du`\[Pi]im`p4, u`f5`o8`qfa`dus`dd`\[Pi]i0`p4, 
   u`f5`o8`qfa`dus`ds`\[CapitalKappa]i0`p4, s`f5`o8`qfa`uds`uu`\[Pi]i0`p5, 
   s`f5`o8`qfa`uds`ud`\[Pi]ip`p5, s`f5`o8`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f5`o8`qfa`dus`du`\[Pi]im`p5, s`f5`o8`qfa`dus`dd`\[Pi]i0`p5, 
   s`f5`o8`qfa`dus`ds`\[CapitalKappa]i0`p5, d`f5`o8`qfb`uds`ud`\[Pi]ip`p3, 
   s`f5`o8`qfb`usd`us`\[CapitalKappa]ip`p3, u`f5`o8`qfb`dus`du`\[Pi]im`p3, 
   s`f5`o8`qfb`dsu`ds`\[CapitalKappa]i0`p3, d`f5`o8`qfb`uds`ud`\[Pi]ip`p4, 
   s`f5`o8`qfb`usd`us`\[CapitalKappa]ip`p4, u`f5`o8`qfb`dus`du`\[Pi]im`p4, 
   s`f5`o8`qfb`dsu`ds`\[CapitalKappa]i0`p4, s`f5`o8`qfb`uds`ud`\[Pi]ip`p5, 
   d`f5`o8`qfb`usd`us`\[CapitalKappa]ip`p5, s`f5`o8`qfb`dus`du`\[Pi]im`p5, 
   u`f5`o8`qfb`dsu`ds`\[CapitalKappa]i0`p5}}, 
 {{u`f6`o1`qfa`dsd`du`\[Pi]im`p3, d`f6`o1`qfa`dsd`dd`\[Eta]`p3, 
   d`f6`o1`qfa`dsd`dd`\[Pi]i0`p3, d`f6`o1`qfa`dsd`dd`etas`p3, 
   s`f6`o1`qfa`dsd`ds`\[CapitalKappa]i0`p3, 
   u`f6`o1`qfa`sdd`su`\[CapitalKappa]im`p3, 
   d`f6`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p3, s`f6`o1`qfa`sdd`ss`\[Eta]`p3, 
   s`f6`o1`qfa`sdd`ss`etas`p3, s`f6`o1`qfa`dsd`du`\[Pi]im`p4, 
   s`f6`o1`qfa`dsd`dd`\[Eta]`p4, s`f6`o1`qfa`dsd`dd`\[Pi]i0`p4, 
   s`f6`o1`qfa`dsd`dd`etas`p4, s`f6`o1`qfa`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f6`o1`qfa`sdd`su`\[CapitalKappa]im`p4, 
   d`f6`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p4, d`f6`o1`qfa`sdd`ss`\[Eta]`p4, 
   d`f6`o1`qfa`sdd`ss`etas`p4, d`f6`o1`qfa`dsd`du`\[Pi]im`p5, 
   d`f6`o1`qfa`dsd`dd`\[Eta]`p5, d`f6`o1`qfa`dsd`dd`\[Pi]i0`p5, 
   d`f6`o1`qfa`dsd`dd`etas`p5, d`f6`o1`qfa`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f6`o1`qfa`sdd`su`\[CapitalKappa]im`p5, 
   d`f6`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p5, d`f6`o1`qfa`sdd`ss`\[Eta]`p5, 
   d`f6`o1`qfa`sdd`ss`etas`p5, d`f6`o1`qfb`dds`dd`\[Eta]`p3, 
   d`f6`o1`qfb`dds`dd`\[Pi]i0`p3, d`f6`o1`qfb`dds`dd`etas`p3, 
   s`f6`o1`qfb`dsd`ds`\[CapitalKappa]i0`p3, 
   d`f6`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p3, d`f6`o1`qfb`dds`dd`\[Eta]`p4, 
   d`f6`o1`qfb`dds`dd`\[Pi]i0`p4, d`f6`o1`qfb`dds`dd`etas`p4, 
   s`f6`o1`qfb`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f6`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p4, s`f6`o1`qfb`dds`dd`\[Eta]`p5, 
   s`f6`o1`qfb`dds`dd`\[Pi]i0`p5, s`f6`o1`qfb`dds`dd`etas`p5, 
   d`f6`o1`qfb`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f6`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p5}, {u`f6`o2`qfa`uds`uu`\[Eta]`p3, 
   u`f6`o2`qfa`uds`uu`etas`p3, d`f6`o2`qfa`uds`ud`\[Pi]ip`p3, 
   s`f6`o2`qfa`uds`us`\[CapitalKappa]ip`p3, u`f6`o2`qfa`dus`du`\[Pi]im`p3, 
   d`f6`o2`qfa`dus`dd`\[Eta]`p3, d`f6`o2`qfa`dus`dd`etas`p3, 
   s`f6`o2`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f6`o2`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f6`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f6`o2`qfa`sdu`ss`\[Eta]`p3, 
   s`f6`o2`qfa`sdu`ss`etas`p3, d`f6`o2`qfa`uds`uu`\[Eta]`p4, 
   d`f6`o2`qfa`uds`uu`etas`p4, d`f6`o2`qfa`uds`ud`\[Pi]ip`p4, 
   d`f6`o2`qfa`uds`us`\[CapitalKappa]ip`p4, u`f6`o2`qfa`dus`du`\[Pi]im`p4, 
   u`f6`o2`qfa`dus`dd`\[Eta]`p4, u`f6`o2`qfa`dus`dd`etas`p4, 
   u`f6`o2`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f6`o2`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f6`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f6`o2`qfa`sdu`ss`\[Eta]`p4, 
   d`f6`o2`qfa`sdu`ss`etas`p4, s`f6`o2`qfa`uds`uu`\[Eta]`p5, 
   s`f6`o2`qfa`uds`uu`etas`p5, s`f6`o2`qfa`uds`ud`\[Pi]ip`p5, 
   s`f6`o2`qfa`uds`us`\[CapitalKappa]ip`p5, s`f6`o2`qfa`dus`du`\[Pi]im`p5, 
   s`f6`o2`qfa`dus`dd`\[Eta]`p5, s`f6`o2`qfa`dus`dd`etas`p5, 
   s`f6`o2`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f6`o2`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f6`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f6`o2`qfa`sdu`ss`\[Eta]`p5, 
   u`f6`o2`qfa`sdu`ss`etas`p5, d`f6`o2`qfb`uds`ud`\[Pi]ip`p3, 
   s`f6`o2`qfb`usd`us`\[CapitalKappa]ip`p3, u`f6`o2`qfb`dus`du`\[Pi]im`p3, 
   s`f6`o2`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f6`o2`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f6`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f6`o2`qfb`uds`ud`\[Pi]ip`p4, 
   s`f6`o2`qfb`usd`us`\[CapitalKappa]ip`p4, u`f6`o2`qfb`dus`du`\[Pi]im`p4, 
   s`f6`o2`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f6`o2`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f6`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f6`o2`qfb`uds`ud`\[Pi]ip`p5, 
   d`f6`o2`qfb`usd`us`\[CapitalKappa]ip`p5, s`f6`o2`qfb`dus`du`\[Pi]im`p5, 
   u`f6`o2`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f6`o2`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f6`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p5}, {u`f6`o3`qfa`uus`uu`\[Eta]`p3, 
   u`f6`o3`qfa`uus`uu`\[Pi]i0`p3, u`f6`o3`qfa`uus`uu`etas`p3, 
   d`f6`o3`qfa`uus`ud`\[Pi]ip`p3, s`f6`o3`qfa`uus`us`\[CapitalKappa]ip`p3, 
   u`f6`o3`qfa`suu`su`\[CapitalKappa]im`p3, 
   d`f6`o3`qfa`suu`sd`\[CapitalKappa]i0b`p3, s`f6`o3`qfa`suu`ss`\[Eta]`p3, 
   s`f6`o3`qfa`suu`ss`etas`p3, u`f6`o3`qfa`uus`uu`\[Eta]`p4, 
   u`f6`o3`qfa`uus`uu`\[Pi]i0`p4, u`f6`o3`qfa`uus`uu`etas`p4, 
   u`f6`o3`qfa`uus`ud`\[Pi]ip`p4, u`f6`o3`qfa`uus`us`\[CapitalKappa]ip`p4, 
   u`f6`o3`qfa`suu`su`\[CapitalKappa]im`p4, 
   u`f6`o3`qfa`suu`sd`\[CapitalKappa]i0b`p4, u`f6`o3`qfa`suu`ss`\[Eta]`p4, 
   u`f6`o3`qfa`suu`ss`etas`p4, s`f6`o3`qfa`uus`uu`\[Eta]`p5, 
   s`f6`o3`qfa`uus`uu`\[Pi]i0`p5, s`f6`o3`qfa`uus`uu`etas`p5, 
   s`f6`o3`qfa`uus`ud`\[Pi]ip`p5, s`f6`o3`qfa`uus`us`\[CapitalKappa]ip`p5, 
   u`f6`o3`qfa`suu`su`\[CapitalKappa]im`p5, 
   u`f6`o3`qfa`suu`sd`\[CapitalKappa]i0b`p5, u`f6`o3`qfa`suu`ss`\[Eta]`p5, 
   u`f6`o3`qfa`suu`ss`etas`p5, u`f6`o3`qfb`uus`uu`\[Eta]`p3, 
   u`f6`o3`qfb`uus`uu`\[Pi]i0`p3, u`f6`o3`qfb`uus`uu`etas`p3, 
   s`f6`o3`qfb`usu`us`\[CapitalKappa]ip`p3, 
   u`f6`o3`qfb`suu`su`\[CapitalKappa]im`p3, u`f6`o3`qfb`uus`uu`\[Eta]`p4, 
   u`f6`o3`qfb`uus`uu`\[Pi]i0`p4, u`f6`o3`qfb`uus`uu`etas`p4, 
   s`f6`o3`qfb`usu`us`\[CapitalKappa]ip`p4, 
   u`f6`o3`qfb`suu`su`\[CapitalKappa]im`p4, s`f6`o3`qfb`uus`uu`\[Eta]`p5, 
   s`f6`o3`qfb`uus`uu`\[Pi]i0`p5, s`f6`o3`qfb`uus`uu`etas`p5, 
   u`f6`o3`qfb`usu`us`\[CapitalKappa]ip`p5, 
   u`f6`o3`qfb`suu`su`\[CapitalKappa]im`p5}, {u`f6`o4`qfa`udu`uu`\[Pi]i0`p3, 
   d`f6`o4`qfa`udu`ud`\[Pi]ip`p3, s`f6`o4`qfa`udu`us`\[CapitalKappa]ip`p3, 
   u`f6`o4`qfa`duu`du`\[Pi]im`p3, d`f6`o4`qfa`duu`dd`\[Pi]i0`p3, 
   s`f6`o4`qfa`duu`ds`\[CapitalKappa]i0`p3, d`f6`o4`qfa`udu`uu`\[Pi]i0`p4, 
   d`f6`o4`qfa`udu`ud`\[Pi]ip`p4, d`f6`o4`qfa`udu`us`\[CapitalKappa]ip`p4, 
   u`f6`o4`qfa`duu`du`\[Pi]im`p4, u`f6`o4`qfa`duu`dd`\[Pi]i0`p4, 
   u`f6`o4`qfa`duu`ds`\[CapitalKappa]i0`p4, u`f6`o4`qfa`udu`uu`\[Pi]i0`p5, 
   u`f6`o4`qfa`udu`ud`\[Pi]ip`p5, u`f6`o4`qfa`udu`us`\[CapitalKappa]ip`p5, 
   u`f6`o4`qfa`duu`du`\[Pi]im`p5, u`f6`o4`qfa`duu`dd`\[Pi]i0`p5, 
   u`f6`o4`qfa`duu`ds`\[CapitalKappa]i0`p5, u`f6`o4`qfb`uud`uu`\[Pi]i0`p3, 
   d`f6`o4`qfb`udu`ud`\[Pi]ip`p3, u`f6`o4`qfb`duu`du`\[Pi]im`p3, 
   u`f6`o4`qfb`uud`uu`\[Pi]i0`p4, d`f6`o4`qfb`udu`ud`\[Pi]ip`p4, 
   u`f6`o4`qfb`duu`du`\[Pi]im`p4, d`f6`o4`qfb`uud`uu`\[Pi]i0`p5, 
   u`f6`o4`qfb`udu`ud`\[Pi]ip`p5, u`f6`o4`qfb`duu`du`\[Pi]im`p5}, 
  {u`f6`o5`qfa`udd`uu`\[Pi]i0`p3, d`f6`o5`qfa`udd`ud`\[Pi]ip`p3, 
   s`f6`o5`qfa`udd`us`\[CapitalKappa]ip`p3, u`f6`o5`qfa`ddu`du`\[Pi]im`p3, 
   d`f6`o5`qfa`ddu`dd`\[Pi]i0`p3, s`f6`o5`qfa`ddu`ds`\[CapitalKappa]i0`p3, 
   d`f6`o5`qfa`udd`uu`\[Pi]i0`p4, d`f6`o5`qfa`udd`ud`\[Pi]ip`p4, 
   d`f6`o5`qfa`udd`us`\[CapitalKappa]ip`p4, d`f6`o5`qfa`ddu`du`\[Pi]im`p4, 
   d`f6`o5`qfa`ddu`dd`\[Pi]i0`p4, d`f6`o5`qfa`ddu`ds`\[CapitalKappa]i0`p4, 
   d`f6`o5`qfa`udd`uu`\[Pi]i0`p5, d`f6`o5`qfa`udd`ud`\[Pi]ip`p5, 
   d`f6`o5`qfa`udd`us`\[CapitalKappa]ip`p5, u`f6`o5`qfa`ddu`du`\[Pi]im`p5, 
   u`f6`o5`qfa`ddu`dd`\[Pi]i0`p5, u`f6`o5`qfa`ddu`ds`\[CapitalKappa]i0`p5, 
   d`f6`o5`qfb`udd`ud`\[Pi]ip`p3, u`f6`o5`qfb`dud`du`\[Pi]im`p3, 
   d`f6`o5`qfb`ddu`dd`\[Pi]i0`p3, d`f6`o5`qfb`udd`ud`\[Pi]ip`p4, 
   u`f6`o5`qfb`dud`du`\[Pi]im`p4, d`f6`o5`qfb`ddu`dd`\[Pi]i0`p4, 
   d`f6`o5`qfb`udd`ud`\[Pi]ip`p5, d`f6`o5`qfb`dud`du`\[Pi]im`p5, 
   u`f6`o5`qfb`ddu`dd`\[Pi]i0`p5}, {u`f6`o6`qfa`dss`du`\[Pi]im`p3, 
   d`f6`o6`qfa`dss`dd`\[Eta]`p3, d`f6`o6`qfa`dss`dd`\[Pi]i0`p3, 
   d`f6`o6`qfa`dss`dd`etas`p3, s`f6`o6`qfa`dss`ds`\[CapitalKappa]i0`p3, 
   u`f6`o6`qfa`ssd`su`\[CapitalKappa]im`p3, 
   d`f6`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p3, s`f6`o6`qfa`ssd`ss`\[Eta]`p3, 
   s`f6`o6`qfa`ssd`ss`etas`p3, s`f6`o6`qfa`dss`du`\[Pi]im`p4, 
   s`f6`o6`qfa`dss`dd`\[Eta]`p4, s`f6`o6`qfa`dss`dd`\[Pi]i0`p4, 
   s`f6`o6`qfa`dss`dd`etas`p4, s`f6`o6`qfa`dss`ds`\[CapitalKappa]i0`p4, 
   s`f6`o6`qfa`ssd`su`\[CapitalKappa]im`p4, 
   s`f6`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p4, s`f6`o6`qfa`ssd`ss`\[Eta]`p4, 
   s`f6`o6`qfa`ssd`ss`etas`p4, s`f6`o6`qfa`dss`du`\[Pi]im`p5, 
   s`f6`o6`qfa`dss`dd`\[Eta]`p5, s`f6`o6`qfa`dss`dd`\[Pi]i0`p5, 
   s`f6`o6`qfa`dss`dd`etas`p5, s`f6`o6`qfa`dss`ds`\[CapitalKappa]i0`p5, 
   d`f6`o6`qfa`ssd`su`\[CapitalKappa]im`p5, 
   d`f6`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p5, d`f6`o6`qfa`ssd`ss`\[Eta]`p5, 
   d`f6`o6`qfa`ssd`ss`etas`p5, s`f6`o6`qfb`dss`ds`\[CapitalKappa]i0`p3, 
   d`f6`o6`qfb`sds`sd`\[CapitalKappa]i0b`p3, s`f6`o6`qfb`ssd`ss`\[Eta]`p3, 
   s`f6`o6`qfb`ssd`ss`etas`p3, s`f6`o6`qfb`dss`ds`\[CapitalKappa]i0`p4, 
   d`f6`o6`qfb`sds`sd`\[CapitalKappa]i0b`p4, s`f6`o6`qfb`ssd`ss`\[Eta]`p4, 
   s`f6`o6`qfb`ssd`ss`etas`p4, s`f6`o6`qfb`dss`ds`\[CapitalKappa]i0`p5, 
   s`f6`o6`qfb`sds`sd`\[CapitalKappa]i0b`p5, d`f6`o6`qfb`ssd`ss`\[Eta]`p5, 
   d`f6`o6`qfb`ssd`ss`etas`p5}, {u`f6`o7`qfa`uss`uu`\[Eta]`p3, 
   u`f6`o7`qfa`uss`uu`\[Pi]i0`p3, u`f6`o7`qfa`uss`uu`etas`p3, 
   d`f6`o7`qfa`uss`ud`\[Pi]ip`p3, s`f6`o7`qfa`uss`us`\[CapitalKappa]ip`p3, 
   u`f6`o7`qfa`sus`su`\[CapitalKappa]im`p3, 
   d`f6`o7`qfa`sus`sd`\[CapitalKappa]i0b`p3, s`f6`o7`qfa`sus`ss`\[Eta]`p3, 
   s`f6`o7`qfa`sus`ss`etas`p3, s`f6`o7`qfa`uss`uu`\[Eta]`p4, 
   s`f6`o7`qfa`uss`uu`\[Pi]i0`p4, s`f6`o7`qfa`uss`uu`etas`p4, 
   s`f6`o7`qfa`uss`ud`\[Pi]ip`p4, s`f6`o7`qfa`uss`us`\[CapitalKappa]ip`p4, 
   u`f6`o7`qfa`sus`su`\[CapitalKappa]im`p4, 
   u`f6`o7`qfa`sus`sd`\[CapitalKappa]i0b`p4, u`f6`o7`qfa`sus`ss`\[Eta]`p4, 
   u`f6`o7`qfa`sus`ss`etas`p4, s`f6`o7`qfa`uss`uu`\[Eta]`p5, 
   s`f6`o7`qfa`uss`uu`\[Pi]i0`p5, s`f6`o7`qfa`uss`uu`etas`p5, 
   s`f6`o7`qfa`uss`ud`\[Pi]ip`p5, s`f6`o7`qfa`uss`us`\[CapitalKappa]ip`p5, 
   s`f6`o7`qfa`sus`su`\[CapitalKappa]im`p5, 
   s`f6`o7`qfa`sus`sd`\[CapitalKappa]i0b`p5, s`f6`o7`qfa`sus`ss`\[Eta]`p5, 
   s`f6`o7`qfa`sus`ss`etas`p5, s`f6`o7`qfb`uss`us`\[CapitalKappa]ip`p3, 
   u`f6`o7`qfb`sus`su`\[CapitalKappa]im`p3, s`f6`o7`qfb`ssu`ss`\[Eta]`p3, 
   s`f6`o7`qfb`ssu`ss`etas`p3, s`f6`o7`qfb`uss`us`\[CapitalKappa]ip`p4, 
   u`f6`o7`qfb`sus`su`\[CapitalKappa]im`p4, s`f6`o7`qfb`ssu`ss`\[Eta]`p4, 
   s`f6`o7`qfb`ssu`ss`etas`p4, s`f6`o7`qfb`uss`us`\[CapitalKappa]ip`p5, 
   s`f6`o7`qfb`sus`su`\[CapitalKappa]im`p5, u`f6`o7`qfb`ssu`ss`\[Eta]`p5, 
   u`f6`o7`qfb`ssu`ss`etas`p5}, {u`f6`o8`qfa`uds`uu`\[Pi]i0`p3, 
   d`f6`o8`qfa`uds`ud`\[Pi]ip`p3, s`f6`o8`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f6`o8`qfa`dus`du`\[Pi]im`p3, d`f6`o8`qfa`dus`dd`\[Pi]i0`p3, 
   s`f6`o8`qfa`dus`ds`\[CapitalKappa]i0`p3, d`f6`o8`qfa`uds`uu`\[Pi]i0`p4, 
   d`f6`o8`qfa`uds`ud`\[Pi]ip`p4, d`f6`o8`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f6`o8`qfa`dus`du`\[Pi]im`p4, u`f6`o8`qfa`dus`dd`\[Pi]i0`p4, 
   u`f6`o8`qfa`dus`ds`\[CapitalKappa]i0`p4, s`f6`o8`qfa`uds`uu`\[Pi]i0`p5, 
   s`f6`o8`qfa`uds`ud`\[Pi]ip`p5, s`f6`o8`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f6`o8`qfa`dus`du`\[Pi]im`p5, s`f6`o8`qfa`dus`dd`\[Pi]i0`p5, 
   s`f6`o8`qfa`dus`ds`\[CapitalKappa]i0`p5, d`f6`o8`qfb`uds`ud`\[Pi]ip`p3, 
   s`f6`o8`qfb`usd`us`\[CapitalKappa]ip`p3, u`f6`o8`qfb`dus`du`\[Pi]im`p3, 
   s`f6`o8`qfb`dsu`ds`\[CapitalKappa]i0`p3, d`f6`o8`qfb`uds`ud`\[Pi]ip`p4, 
   s`f6`o8`qfb`usd`us`\[CapitalKappa]ip`p4, u`f6`o8`qfb`dus`du`\[Pi]im`p4, 
   s`f6`o8`qfb`dsu`ds`\[CapitalKappa]i0`p4, s`f6`o8`qfb`uds`ud`\[Pi]ip`p5, 
   d`f6`o8`qfb`usd`us`\[CapitalKappa]ip`p5, s`f6`o8`qfb`dus`du`\[Pi]im`p5, 
   u`f6`o8`qfb`dsu`ds`\[CapitalKappa]i0`p5}}, 
 {{u`f7`o1`qfa`dsd`du`\[Pi]im`p3, d`f7`o1`qfa`dsd`dd`\[Eta]`p3, 
   d`f7`o1`qfa`dsd`dd`\[Pi]i0`p3, d`f7`o1`qfa`dsd`dd`etas`p3, 
   s`f7`o1`qfa`dsd`ds`\[CapitalKappa]i0`p3, 
   u`f7`o1`qfa`sdd`su`\[CapitalKappa]im`p3, 
   d`f7`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p3, s`f7`o1`qfa`sdd`ss`\[Eta]`p3, 
   s`f7`o1`qfa`sdd`ss`etas`p3, s`f7`o1`qfa`dsd`du`\[Pi]im`p4, 
   s`f7`o1`qfa`dsd`dd`\[Eta]`p4, s`f7`o1`qfa`dsd`dd`\[Pi]i0`p4, 
   s`f7`o1`qfa`dsd`dd`etas`p4, s`f7`o1`qfa`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f7`o1`qfa`sdd`su`\[CapitalKappa]im`p4, 
   d`f7`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p4, d`f7`o1`qfa`sdd`ss`\[Eta]`p4, 
   d`f7`o1`qfa`sdd`ss`etas`p4, d`f7`o1`qfa`dsd`du`\[Pi]im`p5, 
   d`f7`o1`qfa`dsd`dd`\[Eta]`p5, d`f7`o1`qfa`dsd`dd`\[Pi]i0`p5, 
   d`f7`o1`qfa`dsd`dd`etas`p5, d`f7`o1`qfa`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f7`o1`qfa`sdd`su`\[CapitalKappa]im`p5, 
   d`f7`o1`qfa`sdd`sd`\[CapitalKappa]i0b`p5, d`f7`o1`qfa`sdd`ss`\[Eta]`p5, 
   d`f7`o1`qfa`sdd`ss`etas`p5, d`f7`o1`qfb`dds`dd`\[Eta]`p3, 
   d`f7`o1`qfb`dds`dd`\[Pi]i0`p3, d`f7`o1`qfb`dds`dd`etas`p3, 
   s`f7`o1`qfb`dsd`ds`\[CapitalKappa]i0`p3, 
   d`f7`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p3, d`f7`o1`qfb`dds`dd`\[Eta]`p4, 
   d`f7`o1`qfb`dds`dd`\[Pi]i0`p4, d`f7`o1`qfb`dds`dd`etas`p4, 
   s`f7`o1`qfb`dsd`ds`\[CapitalKappa]i0`p4, 
   d`f7`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p4, s`f7`o1`qfb`dds`dd`\[Eta]`p5, 
   s`f7`o1`qfb`dds`dd`\[Pi]i0`p5, s`f7`o1`qfb`dds`dd`etas`p5, 
   d`f7`o1`qfb`dsd`ds`\[CapitalKappa]i0`p5, 
   d`f7`o1`qfb`sdd`sd`\[CapitalKappa]i0b`p5}, {u`f7`o2`qfa`uds`uu`\[Eta]`p3, 
   u`f7`o2`qfa`uds`uu`etas`p3, d`f7`o2`qfa`uds`ud`\[Pi]ip`p3, 
   s`f7`o2`qfa`uds`us`\[CapitalKappa]ip`p3, u`f7`o2`qfa`dus`du`\[Pi]im`p3, 
   d`f7`o2`qfa`dus`dd`\[Eta]`p3, d`f7`o2`qfa`dus`dd`etas`p3, 
   s`f7`o2`qfa`dus`ds`\[CapitalKappa]i0`p3, 
   u`f7`o2`qfa`sdu`su`\[CapitalKappa]im`p3, 
   d`f7`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p3, s`f7`o2`qfa`sdu`ss`\[Eta]`p3, 
   s`f7`o2`qfa`sdu`ss`etas`p3, d`f7`o2`qfa`uds`uu`\[Eta]`p4, 
   d`f7`o2`qfa`uds`uu`etas`p4, d`f7`o2`qfa`uds`ud`\[Pi]ip`p4, 
   d`f7`o2`qfa`uds`us`\[CapitalKappa]ip`p4, u`f7`o2`qfa`dus`du`\[Pi]im`p4, 
   u`f7`o2`qfa`dus`dd`\[Eta]`p4, u`f7`o2`qfa`dus`dd`etas`p4, 
   u`f7`o2`qfa`dus`ds`\[CapitalKappa]i0`p4, 
   d`f7`o2`qfa`sdu`su`\[CapitalKappa]im`p4, 
   d`f7`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p4, d`f7`o2`qfa`sdu`ss`\[Eta]`p4, 
   d`f7`o2`qfa`sdu`ss`etas`p4, s`f7`o2`qfa`uds`uu`\[Eta]`p5, 
   s`f7`o2`qfa`uds`uu`etas`p5, s`f7`o2`qfa`uds`ud`\[Pi]ip`p5, 
   s`f7`o2`qfa`uds`us`\[CapitalKappa]ip`p5, s`f7`o2`qfa`dus`du`\[Pi]im`p5, 
   s`f7`o2`qfa`dus`dd`\[Eta]`p5, s`f7`o2`qfa`dus`dd`etas`p5, 
   s`f7`o2`qfa`dus`ds`\[CapitalKappa]i0`p5, 
   u`f7`o2`qfa`sdu`su`\[CapitalKappa]im`p5, 
   u`f7`o2`qfa`sdu`sd`\[CapitalKappa]i0b`p5, u`f7`o2`qfa`sdu`ss`\[Eta]`p5, 
   u`f7`o2`qfa`sdu`ss`etas`p5, d`f7`o2`qfb`uds`ud`\[Pi]ip`p3, 
   s`f7`o2`qfb`usd`us`\[CapitalKappa]ip`p3, u`f7`o2`qfb`dus`du`\[Pi]im`p3, 
   s`f7`o2`qfb`dsu`ds`\[CapitalKappa]i0`p3, 
   u`f7`o2`qfb`sud`su`\[CapitalKappa]im`p3, 
   d`f7`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p3, d`f7`o2`qfb`uds`ud`\[Pi]ip`p4, 
   s`f7`o2`qfb`usd`us`\[CapitalKappa]ip`p4, u`f7`o2`qfb`dus`du`\[Pi]im`p4, 
   s`f7`o2`qfb`dsu`ds`\[CapitalKappa]i0`p4, 
   u`f7`o2`qfb`sud`su`\[CapitalKappa]im`p4, 
   d`f7`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p4, s`f7`o2`qfb`uds`ud`\[Pi]ip`p5, 
   d`f7`o2`qfb`usd`us`\[CapitalKappa]ip`p5, s`f7`o2`qfb`dus`du`\[Pi]im`p5, 
   u`f7`o2`qfb`dsu`ds`\[CapitalKappa]i0`p5, 
   d`f7`o2`qfb`sud`su`\[CapitalKappa]im`p5, 
   u`f7`o2`qfb`sdu`sd`\[CapitalKappa]i0b`p5}, {u`f7`o3`qfa`uus`uu`\[Eta]`p3, 
   u`f7`o3`qfa`uus`uu`\[Pi]i0`p3, u`f7`o3`qfa`uus`uu`etas`p3, 
   d`f7`o3`qfa`uus`ud`\[Pi]ip`p3, s`f7`o3`qfa`uus`us`\[CapitalKappa]ip`p3, 
   u`f7`o3`qfa`suu`su`\[CapitalKappa]im`p3, 
   d`f7`o3`qfa`suu`sd`\[CapitalKappa]i0b`p3, s`f7`o3`qfa`suu`ss`\[Eta]`p3, 
   s`f7`o3`qfa`suu`ss`etas`p3, u`f7`o3`qfa`uus`uu`\[Eta]`p4, 
   u`f7`o3`qfa`uus`uu`\[Pi]i0`p4, u`f7`o3`qfa`uus`uu`etas`p4, 
   u`f7`o3`qfa`uus`ud`\[Pi]ip`p4, u`f7`o3`qfa`uus`us`\[CapitalKappa]ip`p4, 
   u`f7`o3`qfa`suu`su`\[CapitalKappa]im`p4, 
   u`f7`o3`qfa`suu`sd`\[CapitalKappa]i0b`p4, u`f7`o3`qfa`suu`ss`\[Eta]`p4, 
   u`f7`o3`qfa`suu`ss`etas`p4, s`f7`o3`qfa`uus`uu`\[Eta]`p5, 
   s`f7`o3`qfa`uus`uu`\[Pi]i0`p5, s`f7`o3`qfa`uus`uu`etas`p5, 
   s`f7`o3`qfa`uus`ud`\[Pi]ip`p5, s`f7`o3`qfa`uus`us`\[CapitalKappa]ip`p5, 
   u`f7`o3`qfa`suu`su`\[CapitalKappa]im`p5, 
   u`f7`o3`qfa`suu`sd`\[CapitalKappa]i0b`p5, u`f7`o3`qfa`suu`ss`\[Eta]`p5, 
   u`f7`o3`qfa`suu`ss`etas`p5, u`f7`o3`qfb`uus`uu`\[Eta]`p3, 
   u`f7`o3`qfb`uus`uu`\[Pi]i0`p3, u`f7`o3`qfb`uus`uu`etas`p3, 
   s`f7`o3`qfb`usu`us`\[CapitalKappa]ip`p3, 
   u`f7`o3`qfb`suu`su`\[CapitalKappa]im`p3, u`f7`o3`qfb`uus`uu`\[Eta]`p4, 
   u`f7`o3`qfb`uus`uu`\[Pi]i0`p4, u`f7`o3`qfb`uus`uu`etas`p4, 
   s`f7`o3`qfb`usu`us`\[CapitalKappa]ip`p4, 
   u`f7`o3`qfb`suu`su`\[CapitalKappa]im`p4, s`f7`o3`qfb`uus`uu`\[Eta]`p5, 
   s`f7`o3`qfb`uus`uu`\[Pi]i0`p5, s`f7`o3`qfb`uus`uu`etas`p5, 
   u`f7`o3`qfb`usu`us`\[CapitalKappa]ip`p5, 
   u`f7`o3`qfb`suu`su`\[CapitalKappa]im`p5}, {u`f7`o4`qfa`udu`uu`\[Pi]i0`p3, 
   d`f7`o4`qfa`udu`ud`\[Pi]ip`p3, s`f7`o4`qfa`udu`us`\[CapitalKappa]ip`p3, 
   u`f7`o4`qfa`duu`du`\[Pi]im`p3, d`f7`o4`qfa`duu`dd`\[Pi]i0`p3, 
   s`f7`o4`qfa`duu`ds`\[CapitalKappa]i0`p3, d`f7`o4`qfa`udu`uu`\[Pi]i0`p4, 
   d`f7`o4`qfa`udu`ud`\[Pi]ip`p4, d`f7`o4`qfa`udu`us`\[CapitalKappa]ip`p4, 
   u`f7`o4`qfa`duu`du`\[Pi]im`p4, u`f7`o4`qfa`duu`dd`\[Pi]i0`p4, 
   u`f7`o4`qfa`duu`ds`\[CapitalKappa]i0`p4, u`f7`o4`qfa`udu`uu`\[Pi]i0`p5, 
   u`f7`o4`qfa`udu`ud`\[Pi]ip`p5, u`f7`o4`qfa`udu`us`\[CapitalKappa]ip`p5, 
   u`f7`o4`qfa`duu`du`\[Pi]im`p5, u`f7`o4`qfa`duu`dd`\[Pi]i0`p5, 
   u`f7`o4`qfa`duu`ds`\[CapitalKappa]i0`p5, u`f7`o4`qfb`uud`uu`\[Pi]i0`p3, 
   d`f7`o4`qfb`udu`ud`\[Pi]ip`p3, u`f7`o4`qfb`duu`du`\[Pi]im`p3, 
   u`f7`o4`qfb`uud`uu`\[Pi]i0`p4, d`f7`o4`qfb`udu`ud`\[Pi]ip`p4, 
   u`f7`o4`qfb`duu`du`\[Pi]im`p4, d`f7`o4`qfb`uud`uu`\[Pi]i0`p5, 
   u`f7`o4`qfb`udu`ud`\[Pi]ip`p5, u`f7`o4`qfb`duu`du`\[Pi]im`p5}, 
  {u`f7`o5`qfa`udd`uu`\[Pi]i0`p3, d`f7`o5`qfa`udd`ud`\[Pi]ip`p3, 
   s`f7`o5`qfa`udd`us`\[CapitalKappa]ip`p3, u`f7`o5`qfa`ddu`du`\[Pi]im`p3, 
   d`f7`o5`qfa`ddu`dd`\[Pi]i0`p3, s`f7`o5`qfa`ddu`ds`\[CapitalKappa]i0`p3, 
   d`f7`o5`qfa`udd`uu`\[Pi]i0`p4, d`f7`o5`qfa`udd`ud`\[Pi]ip`p4, 
   d`f7`o5`qfa`udd`us`\[CapitalKappa]ip`p4, d`f7`o5`qfa`ddu`du`\[Pi]im`p4, 
   d`f7`o5`qfa`ddu`dd`\[Pi]i0`p4, d`f7`o5`qfa`ddu`ds`\[CapitalKappa]i0`p4, 
   d`f7`o5`qfa`udd`uu`\[Pi]i0`p5, d`f7`o5`qfa`udd`ud`\[Pi]ip`p5, 
   d`f7`o5`qfa`udd`us`\[CapitalKappa]ip`p5, u`f7`o5`qfa`ddu`du`\[Pi]im`p5, 
   u`f7`o5`qfa`ddu`dd`\[Pi]i0`p5, u`f7`o5`qfa`ddu`ds`\[CapitalKappa]i0`p5, 
   d`f7`o5`qfb`udd`ud`\[Pi]ip`p3, u`f7`o5`qfb`dud`du`\[Pi]im`p3, 
   d`f7`o5`qfb`ddu`dd`\[Pi]i0`p3, d`f7`o5`qfb`udd`ud`\[Pi]ip`p4, 
   u`f7`o5`qfb`dud`du`\[Pi]im`p4, d`f7`o5`qfb`ddu`dd`\[Pi]i0`p4, 
   d`f7`o5`qfb`udd`ud`\[Pi]ip`p5, d`f7`o5`qfb`dud`du`\[Pi]im`p5, 
   u`f7`o5`qfb`ddu`dd`\[Pi]i0`p5}, {u`f7`o6`qfa`dss`du`\[Pi]im`p3, 
   d`f7`o6`qfa`dss`dd`\[Eta]`p3, d`f7`o6`qfa`dss`dd`\[Pi]i0`p3, 
   d`f7`o6`qfa`dss`dd`etas`p3, s`f7`o6`qfa`dss`ds`\[CapitalKappa]i0`p3, 
   u`f7`o6`qfa`ssd`su`\[CapitalKappa]im`p3, 
   d`f7`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p3, s`f7`o6`qfa`ssd`ss`\[Eta]`p3, 
   s`f7`o6`qfa`ssd`ss`etas`p3, s`f7`o6`qfa`dss`du`\[Pi]im`p4, 
   s`f7`o6`qfa`dss`dd`\[Eta]`p4, s`f7`o6`qfa`dss`dd`\[Pi]i0`p4, 
   s`f7`o6`qfa`dss`dd`etas`p4, s`f7`o6`qfa`dss`ds`\[CapitalKappa]i0`p4, 
   s`f7`o6`qfa`ssd`su`\[CapitalKappa]im`p4, 
   s`f7`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p4, s`f7`o6`qfa`ssd`ss`\[Eta]`p4, 
   s`f7`o6`qfa`ssd`ss`etas`p4, s`f7`o6`qfa`dss`du`\[Pi]im`p5, 
   s`f7`o6`qfa`dss`dd`\[Eta]`p5, s`f7`o6`qfa`dss`dd`\[Pi]i0`p5, 
   s`f7`o6`qfa`dss`dd`etas`p5, s`f7`o6`qfa`dss`ds`\[CapitalKappa]i0`p5, 
   d`f7`o6`qfa`ssd`su`\[CapitalKappa]im`p5, 
   d`f7`o6`qfa`ssd`sd`\[CapitalKappa]i0b`p5, d`f7`o6`qfa`ssd`ss`\[Eta]`p5, 
   d`f7`o6`qfa`ssd`ss`etas`p5, s`f7`o6`qfb`dss`ds`\[CapitalKappa]i0`p3, 
   d`f7`o6`qfb`sds`sd`\[CapitalKappa]i0b`p3, s`f7`o6`qfb`ssd`ss`\[Eta]`p3, 
   s`f7`o6`qfb`ssd`ss`etas`p3, s`f7`o6`qfb`dss`ds`\[CapitalKappa]i0`p4, 
   d`f7`o6`qfb`sds`sd`\[CapitalKappa]i0b`p4, s`f7`o6`qfb`ssd`ss`\[Eta]`p4, 
   s`f7`o6`qfb`ssd`ss`etas`p4, s`f7`o6`qfb`dss`ds`\[CapitalKappa]i0`p5, 
   s`f7`o6`qfb`sds`sd`\[CapitalKappa]i0b`p5, d`f7`o6`qfb`ssd`ss`\[Eta]`p5, 
   d`f7`o6`qfb`ssd`ss`etas`p5}, {u`f7`o7`qfa`uss`uu`\[Eta]`p3, 
   u`f7`o7`qfa`uss`uu`\[Pi]i0`p3, u`f7`o7`qfa`uss`uu`etas`p3, 
   d`f7`o7`qfa`uss`ud`\[Pi]ip`p3, s`f7`o7`qfa`uss`us`\[CapitalKappa]ip`p3, 
   u`f7`o7`qfa`sus`su`\[CapitalKappa]im`p3, 
   d`f7`o7`qfa`sus`sd`\[CapitalKappa]i0b`p3, s`f7`o7`qfa`sus`ss`\[Eta]`p3, 
   s`f7`o7`qfa`sus`ss`etas`p3, s`f7`o7`qfa`uss`uu`\[Eta]`p4, 
   s`f7`o7`qfa`uss`uu`\[Pi]i0`p4, s`f7`o7`qfa`uss`uu`etas`p4, 
   s`f7`o7`qfa`uss`ud`\[Pi]ip`p4, s`f7`o7`qfa`uss`us`\[CapitalKappa]ip`p4, 
   u`f7`o7`qfa`sus`su`\[CapitalKappa]im`p4, 
   u`f7`o7`qfa`sus`sd`\[CapitalKappa]i0b`p4, u`f7`o7`qfa`sus`ss`\[Eta]`p4, 
   u`f7`o7`qfa`sus`ss`etas`p4, s`f7`o7`qfa`uss`uu`\[Eta]`p5, 
   s`f7`o7`qfa`uss`uu`\[Pi]i0`p5, s`f7`o7`qfa`uss`uu`etas`p5, 
   s`f7`o7`qfa`uss`ud`\[Pi]ip`p5, s`f7`o7`qfa`uss`us`\[CapitalKappa]ip`p5, 
   s`f7`o7`qfa`sus`su`\[CapitalKappa]im`p5, 
   s`f7`o7`qfa`sus`sd`\[CapitalKappa]i0b`p5, s`f7`o7`qfa`sus`ss`\[Eta]`p5, 
   s`f7`o7`qfa`sus`ss`etas`p5, s`f7`o7`qfb`uss`us`\[CapitalKappa]ip`p3, 
   u`f7`o7`qfb`sus`su`\[CapitalKappa]im`p3, s`f7`o7`qfb`ssu`ss`\[Eta]`p3, 
   s`f7`o7`qfb`ssu`ss`etas`p3, s`f7`o7`qfb`uss`us`\[CapitalKappa]ip`p4, 
   u`f7`o7`qfb`sus`su`\[CapitalKappa]im`p4, s`f7`o7`qfb`ssu`ss`\[Eta]`p4, 
   s`f7`o7`qfb`ssu`ss`etas`p4, s`f7`o7`qfb`uss`us`\[CapitalKappa]ip`p5, 
   s`f7`o7`qfb`sus`su`\[CapitalKappa]im`p5, u`f7`o7`qfb`ssu`ss`\[Eta]`p5, 
   u`f7`o7`qfb`ssu`ss`etas`p5}, {u`f7`o8`qfa`uds`uu`\[Pi]i0`p3, 
   d`f7`o8`qfa`uds`ud`\[Pi]ip`p3, s`f7`o8`qfa`uds`us`\[CapitalKappa]ip`p3, 
   u`f7`o8`qfa`dus`du`\[Pi]im`p3, d`f7`o8`qfa`dus`dd`\[Pi]i0`p3, 
   s`f7`o8`qfa`dus`ds`\[CapitalKappa]i0`p3, d`f7`o8`qfa`uds`uu`\[Pi]i0`p4, 
   d`f7`o8`qfa`uds`ud`\[Pi]ip`p4, d`f7`o8`qfa`uds`us`\[CapitalKappa]ip`p4, 
   u`f7`o8`qfa`dus`du`\[Pi]im`p4, u`f7`o8`qfa`dus`dd`\[Pi]i0`p4, 
   u`f7`o8`qfa`dus`ds`\[CapitalKappa]i0`p4, s`f7`o8`qfa`uds`uu`\[Pi]i0`p5, 
   s`f7`o8`qfa`uds`ud`\[Pi]ip`p5, s`f7`o8`qfa`uds`us`\[CapitalKappa]ip`p5, 
   s`f7`o8`qfa`dus`du`\[Pi]im`p5, s`f7`o8`qfa`dus`dd`\[Pi]i0`p5, 
   s`f7`o8`qfa`dus`ds`\[CapitalKappa]i0`p5, d`f7`o8`qfb`uds`ud`\[Pi]ip`p3, 
   s`f7`o8`qfb`usd`us`\[CapitalKappa]ip`p3, u`f7`o8`qfb`dus`du`\[Pi]im`p3, 
   s`f7`o8`qfb`dsu`ds`\[CapitalKappa]i0`p3, d`f7`o8`qfb`uds`ud`\[Pi]ip`p4, 
   s`f7`o8`qfb`usd`us`\[CapitalKappa]ip`p4, u`f7`o8`qfb`dus`du`\[Pi]im`p4, 
   s`f7`o8`qfb`dsu`ds`\[CapitalKappa]i0`p4, s`f7`o8`qfb`uds`ud`\[Pi]ip`p5, 
   d`f7`o8`qfb`usd`us`\[CapitalKappa]ip`p5, s`f7`o8`qfb`dus`du`\[Pi]im`p5, 
   u`f7`o8`qfb`dsu`ds`\[CapitalKappa]i0`p5}}}
