{{{{}, {q1`f1`o2`qfb`uds`udbar`\[Pi]ip, 
    q1`f1`o2`qfb`usd`usbar`\[CapitalKappa]ip, q1`f1`o2`qfb`dus`dubar`\[Pi]im, 
    q1`f1`o2`qfb`sud`subar`\[CapitalKappa]im}, 
   {q1`f1`o3`qfb`uus`uubar`\[Eta], q1`f1`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f1`o3`qfb`uus`uubar`etas, q1`f1`o3`qfb`usu`usbar`\[CapitalKappa]ip, 
    q1`f1`o3`qfb`uus`uubar`\[Eta], q1`f1`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f1`o3`qfb`uus`uubar`etas, q1`f1`o3`qfb`suu`subar`\[CapitalKappa]im}, 
   {q1`f1`o4`qfb`uud`uubar`\[Eta], q1`f1`o4`qfb`uud`uubar`\[Pi]i0, 
    q1`f1`o4`qfb`uud`uubar`etas, q1`f1`o4`qfb`udu`udbar`\[Pi]ip, 
    q1`f1`o4`qfb`uud`uubar`\[Eta], q1`f1`o4`qfb`uud`uubar`\[Pi]i0, 
    q1`f1`o4`qfb`uud`uubar`etas, q1`f1`o4`qfb`duu`dubar`\[Pi]im}, 
   {q1`f1`o5`qfb`udd`udbar`\[Pi]ip, q1`f1`o5`qfb`dud`dubar`\[Pi]im}, {}, 
   {q1`f1`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q1`f1`o7`qfb`sus`subar`\[CapitalKappa]im}, 
   {q1`f1`o8`qfb`uds`udbar`\[Pi]ip, q1`f1`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q1`f1`o8`qfb`dus`dubar`\[Pi]im, 
    q1`f1`o8`qfb`sud`subar`\[CapitalKappa]im}}, 
  {{}, {q1`f2`o2`qfb`dus`dubar`\[Pi]im, 
    q1`f2`o2`qfb`sud`subar`\[CapitalKappa]im, 
    q1`f2`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q1`f2`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q1`f2`o3`qfb`uus`uubar`\[Eta], q1`f2`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f2`o3`qfb`uus`uubar`etas, q1`f2`o3`qfb`suu`subar`\[CapitalKappa]im, 
    q1`f2`o3`qfb`usu`usbar`\[CapitalKappa]ip, 
    q1`f2`o3`qfb`suu`subar`\[CapitalKappa]im}, 
   {q1`f2`o4`qfb`uud`uubar`\[Eta], q1`f2`o4`qfb`uud`uubar`\[Pi]i0, 
    q1`f2`o4`qfb`uud`uubar`etas, q1`f2`o4`qfb`duu`dubar`\[Pi]im, 
    q1`f2`o4`qfb`udu`udbar`\[Pi]ip, q1`f2`o4`qfb`duu`dubar`\[Pi]im}, 
   {q1`f2`o5`qfb`dud`dubar`\[Pi]im, q1`f2`o5`qfb`ddu`ddbar`\[Eta], 
    q1`f2`o5`qfb`ddu`ddbar`\[Pi]i0, q1`f2`o5`qfb`ddu`ddbar`etas}, {}, 
   {q1`f2`o7`qfb`sus`subar`\[CapitalKappa]im, q1`f2`o7`qfb`ssu`ssbar`\[Eta], 
    q1`f2`o7`qfb`ssu`ssbar`etas}, {q1`f2`o8`qfb`dus`dubar`\[Pi]im, 
    q1`f2`o8`qfb`sud`subar`\[CapitalKappa]im, 
    q1`f2`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q1`f2`o8`qfb`sdu`sdbar`\[CapitalKappa]i0b}}, 
  {{}, {q1`f3`o2`qfb`dus`dubar`\[Pi]im, 
    q1`f3`o2`qfb`sud`subar`\[CapitalKappa]im, 
    q1`f3`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q1`f3`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q1`f3`o3`qfb`uus`uubar`\[Eta], q1`f3`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f3`o3`qfb`uus`uubar`etas, q1`f3`o3`qfb`suu`subar`\[CapitalKappa]im, 
    q1`f3`o3`qfb`usu`usbar`\[CapitalKappa]ip, 
    q1`f3`o3`qfb`suu`subar`\[CapitalKappa]im}, 
   {q1`f3`o4`qfb`uud`uubar`\[Eta], q1`f3`o4`qfb`uud`uubar`\[Pi]i0, 
    q1`f3`o4`qfb`uud`uubar`etas, q1`f3`o4`qfb`duu`dubar`\[Pi]im, 
    q1`f3`o4`qfb`udu`udbar`\[Pi]ip, q1`f3`o4`qfb`duu`dubar`\[Pi]im}, 
   {q1`f3`o5`qfb`dud`dubar`\[Pi]im, q1`f3`o5`qfb`ddu`ddbar`\[Eta], 
    q1`f3`o5`qfb`ddu`ddbar`\[Pi]i0, q1`f3`o5`qfb`ddu`ddbar`etas}, {}, 
   {q1`f3`o7`qfb`sus`subar`\[CapitalKappa]im, q1`f3`o7`qfb`ssu`ssbar`\[Eta], 
    q1`f3`o7`qfb`ssu`ssbar`etas}, {q1`f3`o8`qfb`dus`dubar`\[Pi]im, 
    q1`f3`o8`qfb`sud`subar`\[CapitalKappa]im, 
    q1`f3`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q1`f3`o8`qfb`sdu`sdbar`\[CapitalKappa]i0b}}, 
  {{}, {q1`f4`o2`qfb`uds`udbar`\[Pi]ip, 
    q1`f4`o2`qfb`usd`usbar`\[CapitalKappa]ip, q1`f4`o2`qfb`dus`dubar`\[Pi]im, 
    q1`f4`o2`qfb`sud`subar`\[CapitalKappa]im}, 
   {q1`f4`o3`qfb`uus`uubar`\[Eta], q1`f4`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f4`o3`qfb`uus`uubar`etas, q1`f4`o3`qfb`usu`usbar`\[CapitalKappa]ip, 
    q1`f4`o3`qfb`uus`uubar`\[Eta], q1`f4`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f4`o3`qfb`uus`uubar`etas, q1`f4`o3`qfb`suu`subar`\[CapitalKappa]im}, 
   {q1`f4`o4`qfb`uud`uubar`\[Pi]i0, q1`f4`o4`qfb`udu`udbar`\[Pi]ip, 
    q1`f4`o4`qfb`uud`uubar`\[Pi]i0, q1`f4`o4`qfb`duu`dubar`\[Pi]im}, 
   {q1`f4`o5`qfb`udd`udbar`\[Pi]ip, q1`f4`o5`qfb`dud`dubar`\[Pi]im}, {}, 
   {q1`f4`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q1`f4`o7`qfb`sus`subar`\[CapitalKappa]im}, 
   {q1`f4`o8`qfb`uds`udbar`\[Pi]ip, q1`f4`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q1`f4`o8`qfb`dus`dubar`\[Pi]im}}, 
  {{}, {q1`f4`o2`qfb`dus`dubar`\[Pi]im, 
    q1`f4`o2`qfb`sud`subar`\[CapitalKappa]im, 
    q1`f4`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q1`f4`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q1`f4`o3`qfb`uus`uubar`\[Eta], q1`f4`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f4`o3`qfb`uus`uubar`etas, q1`f4`o3`qfb`suu`subar`\[CapitalKappa]im, 
    q1`f4`o3`qfb`usu`usbar`\[CapitalKappa]ip, 
    q1`f4`o3`qfb`suu`subar`\[CapitalKappa]im}, 
   {q1`f4`o4`qfb`uud`uubar`\[Pi]i0, q1`f4`o4`qfb`duu`dubar`\[Pi]im, 
    q1`f4`o4`qfb`udu`udbar`\[Pi]ip, q1`f4`o4`qfb`duu`dubar`\[Pi]im}, 
   {q1`f4`o5`qfb`dud`dubar`\[Pi]im, q1`f4`o5`qfb`ddu`ddbar`\[Pi]i0}, {}, 
   {q1`f4`o7`qfb`sus`subar`\[CapitalKappa]im, q1`f4`o7`qfb`ssu`ssbar`\[Eta], 
    q1`f4`o7`qfb`ssu`ssbar`etas}, {q1`f4`o8`qfb`dus`dubar`\[Pi]im, 
    q1`f4`o8`qfb`dsu`dsbar`\[CapitalKappa]i0}}, 
  {{}, {q1`f5`o2`qfb`dus`dubar`\[Pi]im, 
    q1`f5`o2`qfb`sud`subar`\[CapitalKappa]im, 
    q1`f5`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q1`f5`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q1`f5`o3`qfb`uus`uubar`\[Eta], q1`f5`o3`qfb`uus`uubar`\[Pi]i0, 
    q1`f5`o3`qfb`uus`uubar`etas, q1`f5`o3`qfb`suu`subar`\[CapitalKappa]im, 
    q1`f5`o3`qfb`usu`usbar`\[CapitalKappa]ip, 
    q1`f5`o3`qfb`suu`subar`\[CapitalKappa]im}, 
   {q1`f5`o4`qfb`uud`uubar`\[Pi]i0, q1`f5`o4`qfb`duu`dubar`\[Pi]im, 
    q1`f5`o4`qfb`udu`udbar`\[Pi]ip, q1`f5`o4`qfb`duu`dubar`\[Pi]im}, 
   {q1`f5`o5`qfb`dud`dubar`\[Pi]im, q1`f5`o5`qfb`ddu`ddbar`\[Pi]i0}, {}, 
   {q1`f5`o7`qfb`sus`subar`\[CapitalKappa]im, q1`f5`o7`qfb`ssu`ssbar`\[Eta], 
    q1`f5`o7`qfb`ssu`ssbar`etas}, {q1`f5`o8`qfb`dus`dubar`\[Pi]im, 
    q1`f5`o8`qfb`dsu`dsbar`\[CapitalKappa]i0}}}, 
 {{{q2`f1`o1`qfb`dds`ddbar`\[Eta], q2`f1`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f1`o1`qfb`dds`ddbar`etas, q2`f1`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, 
    q2`f1`o1`qfb`dds`ddbar`\[Eta], q2`f1`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f1`o1`qfb`dds`ddbar`etas, q2`f1`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f1`o2`qfb`dus`dubar`\[Pi]im, q2`f1`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q2`f1`o2`qfb`uds`udbar`\[Pi]ip, 
    q2`f1`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b}, {}, 
   {q2`f1`o4`qfb`duu`dubar`\[Pi]im, q2`f1`o4`qfb`udu`udbar`\[Pi]ip}, 
   {q2`f1`o5`qfb`dud`dubar`\[Pi]im, q2`f1`o5`qfb`ddu`ddbar`\[Eta], 
    q2`f1`o5`qfb`ddu`ddbar`\[Pi]i0, q2`f1`o5`qfb`ddu`ddbar`etas, 
    q2`f1`o5`qfb`udd`udbar`\[Pi]ip, q2`f1`o5`qfb`ddu`ddbar`\[Eta], 
    q2`f1`o5`qfb`ddu`ddbar`\[Pi]i0, q2`f1`o5`qfb`ddu`ddbar`etas}, 
   {q2`f1`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q2`f1`o6`qfb`sds`sdbar`\[CapitalKappa]i0b}, {}, 
   {q2`f1`o8`qfb`dus`dubar`\[Pi]im, q2`f1`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q2`f1`o8`qfb`uds`udbar`\[Pi]ip, 
    q2`f1`o8`qfb`sdu`sdbar`\[CapitalKappa]i0b}}, 
  {{q2`f2`o1`qfb`dds`ddbar`\[Eta], q2`f2`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f2`o1`qfb`dds`ddbar`etas, q2`f2`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b, 
    q2`f2`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, 
    q2`f2`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f2`o2`qfb`uds`udbar`\[Pi]ip, 
    q2`f2`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q2`f2`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q2`f2`o2`qfb`sud`subar`\[CapitalKappa]im}, {}, 
   {q2`f2`o4`qfb`udu`udbar`\[Pi]ip, q2`f2`o4`qfb`uud`uubar`\[Eta], 
    q2`f2`o4`qfb`uud`uubar`\[Pi]i0, q2`f2`o4`qfb`uud`uubar`etas}, 
   {q2`f2`o5`qfb`udd`udbar`\[Pi]ip, q2`f2`o5`qfb`ddu`ddbar`\[Eta], 
    q2`f2`o5`qfb`ddu`ddbar`\[Pi]i0, q2`f2`o5`qfb`ddu`ddbar`etas, 
    q2`f2`o5`qfb`udd`udbar`\[Pi]ip, q2`f2`o5`qfb`dud`dubar`\[Pi]im}, 
   {q2`f2`o6`qfb`sds`sdbar`\[CapitalKappa]i0b, q2`f2`o6`qfb`ssd`ssbar`\[Eta], 
    q2`f2`o6`qfb`ssd`ssbar`etas}, {}, {q2`f2`o8`qfb`uds`udbar`\[Pi]ip, 
    q2`f2`o8`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q2`f2`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q2`f2`o8`qfb`sud`subar`\[CapitalKappa]im}}, 
  {{q2`f3`o1`qfb`dds`ddbar`\[Eta], q2`f3`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f3`o1`qfb`dds`ddbar`etas, q2`f3`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b, 
    q2`f3`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, 
    q2`f3`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f3`o2`qfb`uds`udbar`\[Pi]ip, 
    q2`f3`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q2`f3`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q2`f3`o2`qfb`sud`subar`\[CapitalKappa]im}, {}, 
   {q2`f3`o4`qfb`udu`udbar`\[Pi]ip, q2`f3`o4`qfb`uud`uubar`\[Eta], 
    q2`f3`o4`qfb`uud`uubar`\[Pi]i0, q2`f3`o4`qfb`uud`uubar`etas}, 
   {q2`f3`o5`qfb`udd`udbar`\[Pi]ip, q2`f3`o5`qfb`ddu`ddbar`\[Eta], 
    q2`f3`o5`qfb`ddu`ddbar`\[Pi]i0, q2`f3`o5`qfb`ddu`ddbar`etas, 
    q2`f3`o5`qfb`udd`udbar`\[Pi]ip, q2`f3`o5`qfb`dud`dubar`\[Pi]im}, 
   {q2`f3`o6`qfb`sds`sdbar`\[CapitalKappa]i0b, q2`f3`o6`qfb`ssd`ssbar`\[Eta], 
    q2`f3`o6`qfb`ssd`ssbar`etas}, {}, {q2`f3`o8`qfb`uds`udbar`\[Pi]ip, 
    q2`f3`o8`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q2`f3`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q2`f3`o8`qfb`sud`subar`\[CapitalKappa]im}}, 
  {{q2`f4`o1`qfb`dds`ddbar`\[Eta], q2`f4`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f4`o1`qfb`dds`ddbar`etas, q2`f4`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, 
    q2`f4`o1`qfb`dds`ddbar`\[Eta], q2`f4`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f4`o1`qfb`dds`ddbar`etas, q2`f4`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o2`qfb`dus`dubar`\[Pi]im, q2`f4`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q2`f4`o2`qfb`uds`udbar`\[Pi]ip, 
    q2`f4`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b}, {}, 
   {q2`f4`o4`qfb`duu`dubar`\[Pi]im, q2`f4`o4`qfb`udu`udbar`\[Pi]ip}, 
   {q2`f4`o5`qfb`dud`dubar`\[Pi]im, q2`f4`o5`qfb`ddu`ddbar`\[Pi]i0, 
    q2`f4`o5`qfb`udd`udbar`\[Pi]ip, q2`f4`o5`qfb`ddu`ddbar`\[Pi]i0}, 
   {q2`f4`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q2`f4`o6`qfb`sds`sdbar`\[CapitalKappa]i0b}, {}, 
   {q2`f4`o8`qfb`dus`dubar`\[Pi]im, q2`f4`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, 
    q2`f4`o8`qfb`uds`udbar`\[Pi]ip}}, 
  {{q2`f4`o1`qfb`dds`ddbar`\[Eta], q2`f4`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f4`o1`qfb`dds`ddbar`etas, q2`f4`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b, 
    q2`f4`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, 
    q2`f4`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o2`qfb`uds`udbar`\[Pi]ip, 
    q2`f4`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q2`f4`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q2`f4`o2`qfb`sud`subar`\[CapitalKappa]im}, {}, 
   {q2`f4`o4`qfb`udu`udbar`\[Pi]ip, q2`f4`o4`qfb`uud`uubar`\[Pi]i0}, 
   {q2`f4`o5`qfb`udd`udbar`\[Pi]ip, q2`f4`o5`qfb`ddu`ddbar`\[Pi]i0, 
    q2`f4`o5`qfb`udd`udbar`\[Pi]ip, q2`f4`o5`qfb`dud`dubar`\[Pi]im}, 
   {q2`f4`o6`qfb`sds`sdbar`\[CapitalKappa]i0b, q2`f4`o6`qfb`ssd`ssbar`\[Eta], 
    q2`f4`o6`qfb`ssd`ssbar`etas}, {}, {q2`f4`o8`qfb`uds`udbar`\[Pi]ip, 
    q2`f4`o8`qfb`usd`usbar`\[CapitalKappa]ip}}, 
  {{q2`f5`o1`qfb`dds`ddbar`\[Eta], q2`f5`o1`qfb`dds`ddbar`\[Pi]i0, 
    q2`f5`o1`qfb`dds`ddbar`etas, q2`f5`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b, 
    q2`f5`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, 
    q2`f5`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f5`o2`qfb`uds`udbar`\[Pi]ip, 
    q2`f5`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q2`f5`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q2`f5`o2`qfb`sud`subar`\[CapitalKappa]im}, {}, 
   {q2`f5`o4`qfb`udu`udbar`\[Pi]ip, q2`f5`o4`qfb`uud`uubar`\[Pi]i0}, 
   {q2`f5`o5`qfb`udd`udbar`\[Pi]ip, q2`f5`o5`qfb`ddu`ddbar`\[Pi]i0, 
    q2`f5`o5`qfb`udd`udbar`\[Pi]ip, q2`f5`o5`qfb`dud`dubar`\[Pi]im}, 
   {q2`f5`o6`qfb`sds`sdbar`\[CapitalKappa]i0b, q2`f5`o6`qfb`ssd`ssbar`\[Eta], 
    q2`f5`o6`qfb`ssd`ssbar`etas}, {}, {q2`f5`o8`qfb`uds`udbar`\[Pi]ip, 
    q2`f5`o8`qfb`usd`usbar`\[CapitalKappa]ip}}}, 
 {{{q3`f1`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b, 
    q3`f1`o1`qfb`dsd`dsbar`\[CapitalKappa]i0}, 
   {q3`f1`o2`qfb`sud`subar`\[CapitalKappa]im, 
    q3`f1`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q3`f1`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f1`o2`qfb`dsu`dsbar`\[CapitalKappa]i0}, 
   {q3`f1`o3`qfb`suu`subar`\[CapitalKappa]im, 
    q3`f1`o3`qfb`usu`usbar`\[CapitalKappa]ip}, {}, {}, 
   {q3`f1`o6`qfb`sds`sdbar`\[CapitalKappa]i0b, q3`f1`o6`qfb`ssd`ssbar`\[Eta], 
    q3`f1`o6`qfb`ssd`ssbar`etas, q3`f1`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q3`f1`o6`qfb`ssd`ssbar`\[Eta], q3`f1`o6`qfb`ssd`ssbar`etas}, 
   {q3`f1`o7`qfb`sus`subar`\[CapitalKappa]im, q3`f1`o7`qfb`ssu`ssbar`\[Eta], 
    q3`f1`o7`qfb`ssu`ssbar`etas, q3`f1`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q3`f1`o7`qfb`ssu`ssbar`\[Eta], q3`f1`o7`qfb`ssu`ssbar`etas}, 
   {q3`f1`o8`qfb`sud`subar`\[CapitalKappa]im, 
    q3`f1`o8`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q3`f1`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f1`o8`qfb`dsu`dsbar`\[CapitalKappa]i0}}, 
  {{q3`f2`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, q3`f2`o1`qfb`dds`ddbar`\[Eta], 
    q3`f2`o1`qfb`dds`ddbar`\[Pi]i0, q3`f2`o1`qfb`dds`ddbar`etas}, 
   {q3`f2`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f2`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f2`o2`qfb`uds`udbar`\[Pi]ip, 
    q3`f2`o2`qfb`dus`dubar`\[Pi]im}, 
   {q3`f2`o3`qfb`usu`usbar`\[CapitalKappa]ip, q3`f2`o3`qfb`uus`uubar`\[Eta], 
    q3`f2`o3`qfb`uus`uubar`\[Pi]i0, q3`f2`o3`qfb`uus`uubar`etas}, {}, {}, 
   {q3`f2`o6`qfb`dss`dsbar`\[CapitalKappa]i0, q3`f2`o6`qfb`ssd`ssbar`\[Eta], 
    q3`f2`o6`qfb`ssd`ssbar`etas, q3`f2`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q3`f2`o6`qfb`sds`sdbar`\[CapitalKappa]i0b}, 
   {q3`f2`o7`qfb`uss`usbar`\[CapitalKappa]ip, q3`f2`o7`qfb`ssu`ssbar`\[Eta], 
    q3`f2`o7`qfb`ssu`ssbar`etas, q3`f2`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q3`f2`o7`qfb`sus`subar`\[CapitalKappa]im}, 
   {q3`f2`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f2`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f2`o8`qfb`uds`udbar`\[Pi]ip, 
    q3`f2`o8`qfb`dus`dubar`\[Pi]im}}, 
  {{q3`f3`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, q3`f3`o1`qfb`dds`ddbar`\[Eta], 
    q3`f3`o1`qfb`dds`ddbar`\[Pi]i0, q3`f3`o1`qfb`dds`ddbar`etas}, 
   {q3`f3`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f3`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f3`o2`qfb`uds`udbar`\[Pi]ip, 
    q3`f3`o2`qfb`dus`dubar`\[Pi]im}, 
   {q3`f3`o3`qfb`usu`usbar`\[CapitalKappa]ip, q3`f3`o3`qfb`uus`uubar`\[Eta], 
    q3`f3`o3`qfb`uus`uubar`\[Pi]i0, q3`f3`o3`qfb`uus`uubar`etas}, {}, {}, 
   {q3`f3`o6`qfb`dss`dsbar`\[CapitalKappa]i0, q3`f3`o6`qfb`ssd`ssbar`\[Eta], 
    q3`f3`o6`qfb`ssd`ssbar`etas, q3`f3`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q3`f3`o6`qfb`sds`sdbar`\[CapitalKappa]i0b}, 
   {q3`f3`o7`qfb`uss`usbar`\[CapitalKappa]ip, q3`f3`o7`qfb`ssu`ssbar`\[Eta], 
    q3`f3`o7`qfb`ssu`ssbar`etas, q3`f3`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q3`f3`o7`qfb`sus`subar`\[CapitalKappa]im}, 
   {q3`f3`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f3`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f3`o8`qfb`uds`udbar`\[Pi]ip, 
    q3`f3`o8`qfb`dus`dubar`\[Pi]im}}, 
  {{q3`f4`o1`qfb`sdd`sdbar`\[CapitalKappa]i0b, 
    q3`f4`o1`qfb`dsd`dsbar`\[CapitalKappa]i0}, 
   {q3`f4`o2`qfb`sud`subar`\[CapitalKappa]im, 
    q3`f4`o2`qfb`sdu`sdbar`\[CapitalKappa]i0b, 
    q3`f4`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f4`o2`qfb`dsu`dsbar`\[CapitalKappa]i0}, 
   {q3`f4`o3`qfb`suu`subar`\[CapitalKappa]im, 
    q3`f4`o3`qfb`usu`usbar`\[CapitalKappa]ip}, {}, {}, 
   {q3`f4`o6`qfb`sds`sdbar`\[CapitalKappa]i0b, q3`f4`o6`qfb`ssd`ssbar`\[Eta], 
    q3`f4`o6`qfb`ssd`ssbar`etas, q3`f4`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q3`f4`o6`qfb`ssd`ssbar`\[Eta], q3`f4`o6`qfb`ssd`ssbar`etas}, 
   {q3`f4`o7`qfb`sus`subar`\[CapitalKappa]im, q3`f4`o7`qfb`ssu`ssbar`\[Eta], 
    q3`f4`o7`qfb`ssu`ssbar`etas, q3`f4`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q3`f4`o7`qfb`ssu`ssbar`\[Eta], q3`f4`o7`qfb`ssu`ssbar`etas}, 
   {q3`f4`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f4`o8`qfb`dsu`dsbar`\[CapitalKappa]i0}}, 
  {{q3`f4`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, q3`f4`o1`qfb`dds`ddbar`\[Eta], 
    q3`f4`o1`qfb`dds`ddbar`\[Pi]i0, q3`f4`o1`qfb`dds`ddbar`etas}, 
   {q3`f4`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f4`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f4`o2`qfb`uds`udbar`\[Pi]ip, 
    q3`f4`o2`qfb`dus`dubar`\[Pi]im}, 
   {q3`f4`o3`qfb`usu`usbar`\[CapitalKappa]ip, q3`f4`o3`qfb`uus`uubar`\[Eta], 
    q3`f4`o3`qfb`uus`uubar`\[Pi]i0, q3`f4`o3`qfb`uus`uubar`etas}, {}, {}, 
   {q3`f4`o6`qfb`dss`dsbar`\[CapitalKappa]i0, q3`f4`o6`qfb`ssd`ssbar`\[Eta], 
    q3`f4`o6`qfb`ssd`ssbar`etas, q3`f4`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q3`f4`o6`qfb`sds`sdbar`\[CapitalKappa]i0b}, 
   {q3`f4`o7`qfb`uss`usbar`\[CapitalKappa]ip, q3`f4`o7`qfb`ssu`ssbar`\[Eta], 
    q3`f4`o7`qfb`ssu`ssbar`etas, q3`f4`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q3`f4`o7`qfb`sus`subar`\[CapitalKappa]im}, 
   {q3`f4`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f4`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f4`o8`qfb`uds`udbar`\[Pi]ip, 
    q3`f4`o8`qfb`dus`dubar`\[Pi]im}}, 
  {{q3`f5`o1`qfb`dsd`dsbar`\[CapitalKappa]i0, q3`f5`o1`qfb`dds`ddbar`\[Eta], 
    q3`f5`o1`qfb`dds`ddbar`\[Pi]i0, q3`f5`o1`qfb`dds`ddbar`etas}, 
   {q3`f5`o2`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f5`o2`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f5`o2`qfb`uds`udbar`\[Pi]ip, 
    q3`f5`o2`qfb`dus`dubar`\[Pi]im}, 
   {q3`f5`o3`qfb`usu`usbar`\[CapitalKappa]ip, q3`f5`o3`qfb`uus`uubar`\[Eta], 
    q3`f5`o3`qfb`uus`uubar`\[Pi]i0, q3`f5`o3`qfb`uus`uubar`etas}, {}, {}, 
   {q3`f5`o6`qfb`dss`dsbar`\[CapitalKappa]i0, q3`f5`o6`qfb`ssd`ssbar`\[Eta], 
    q3`f5`o6`qfb`ssd`ssbar`etas, q3`f5`o6`qfb`dss`dsbar`\[CapitalKappa]i0, 
    q3`f5`o6`qfb`sds`sdbar`\[CapitalKappa]i0b}, 
   {q3`f5`o7`qfb`uss`usbar`\[CapitalKappa]ip, q3`f5`o7`qfb`ssu`ssbar`\[Eta], 
    q3`f5`o7`qfb`ssu`ssbar`etas, q3`f5`o7`qfb`uss`usbar`\[CapitalKappa]ip, 
    q3`f5`o7`qfb`sus`subar`\[CapitalKappa]im}, 
   {q3`f5`o8`qfb`usd`usbar`\[CapitalKappa]ip, 
    q3`f5`o8`qfb`dsu`dsbar`\[CapitalKappa]i0, q3`f5`o8`qfb`uds`udbar`\[Pi]ip, 
    q3`f5`o8`qfb`dus`dubar`\[Pi]im}}}}
