{{{{q1`f1`o1`qfa`dsd`dubar`\[Pi]im, 
    q1`f1`o1`qfa`sdd`subar`\[CapitalKappa]im}, 
   {q1`f1`o2`qfa`uds`uubar`\[Eta], q1`f1`o2`qfa`uds`uubar`etas, 
    q1`f1`o2`qfa`uds`uubar`\[Pi]i0, q1`f1`o2`qfa`dus`dubar`\[Pi]im, 
    q1`f1`o2`qfa`sdu`subar`\[CapitalKappa]im}, 
   {q1`f1`o3`qfa`uus`uubar`\[Eta], q1`f1`o3`qfa`uus`uubar`\[Pi]i0, 
    q1`f1`o3`qfa`uus`uubar`etas, q1`f1`o3`qfa`suu`subar`\[CapitalKappa]im}, 
   {q1`f1`o4`qfa`udu`uubar`\[Eta], q1`f1`o4`qfa`udu`uubar`\[Pi]i0, 
    q1`f1`o4`qfa`udu`uubar`etas, q1`f1`o4`qfa`duu`dubar`\[Pi]im}, 
   {q1`f1`o5`qfa`udd`uubar`\[Eta], q1`f1`o5`qfa`udd`uubar`\[Pi]i0, 
    q1`f1`o5`qfa`udd`uubar`etas, q1`f1`o5`qfa`ddu`dubar`\[Pi]im}, 
   {q1`f1`o6`qfa`dss`dubar`\[Pi]im, 
    q1`f1`o6`qfa`ssd`subar`\[CapitalKappa]im}, 
   {q1`f1`o7`qfa`uss`uubar`\[Eta], q1`f1`o7`qfa`uss`uubar`\[Pi]i0, 
    q1`f1`o7`qfa`uss`uubar`etas, q1`f1`o7`qfa`sus`subar`\[CapitalKappa]im}, 
   {q1`f1`o8`qfa`uds`uubar`\[Pi]i0, q1`f1`o8`qfa`uds`uubar`\[Eta], 
    q1`f1`o8`qfa`uds`uubar`etas, q1`f1`o8`qfa`dus`dubar`\[Pi]im, 
    q1`f1`o8`qfa`sdu`subar`\[CapitalKappa]im}}, 
  {{q1`f2`o1`qfa`dsd`dubar`\[Pi]im, 
    q1`f2`o1`qfa`sdd`subar`\[CapitalKappa]im}, 
   {q1`f2`o2`qfa`uds`uubar`\[Eta], q1`f2`o2`qfa`uds`uubar`etas, 
    q1`f2`o2`qfa`uds`uubar`\[Pi]i0, q1`f2`o2`qfa`dus`dubar`\[Pi]im, 
    q1`f2`o2`qfa`sdu`subar`\[CapitalKappa]im}, 
   {q1`f2`o3`qfa`uus`uubar`\[Eta], q1`f2`o3`qfa`uus`uubar`\[Pi]i0, 
    q1`f2`o3`qfa`uus`uubar`etas, q1`f2`o3`qfa`suu`subar`\[CapitalKappa]im}, 
   {q1`f2`o4`qfa`udu`uubar`\[Eta], q1`f2`o4`qfa`udu`uubar`\[Pi]i0, 
    q1`f2`o4`qfa`udu`uubar`etas, q1`f2`o4`qfa`duu`dubar`\[Pi]im}, 
   {q1`f2`o5`qfa`udd`uubar`\[Eta], q1`f2`o5`qfa`udd`uubar`\[Pi]i0, 
    q1`f2`o5`qfa`udd`uubar`etas, q1`f2`o5`qfa`ddu`dubar`\[Pi]im}, 
   {q1`f2`o6`qfa`dss`dubar`\[Pi]im, 
    q1`f2`o6`qfa`ssd`subar`\[CapitalKappa]im}, 
   {q1`f2`o7`qfa`uss`uubar`\[Eta], q1`f2`o7`qfa`uss`uubar`\[Pi]i0, 
    q1`f2`o7`qfa`uss`uubar`etas, q1`f2`o7`qfa`sus`subar`\[CapitalKappa]im}, 
   {q1`f2`o8`qfa`uds`uubar`\[Pi]i0, q1`f2`o8`qfa`uds`uubar`\[Eta], 
    q1`f2`o8`qfa`uds`uubar`etas, q1`f2`o8`qfa`dus`dubar`\[Pi]im, 
    q1`f2`o8`qfa`sdu`subar`\[CapitalKappa]im}}, 
  {{q1`f3`o1`qfa`dsd`dubar`\[Pi]im, 
    q1`f3`o1`qfa`sdd`subar`\[CapitalKappa]im}, 
   {q1`f3`o2`qfa`uds`uubar`\[Eta], q1`f3`o2`qfa`uds`uubar`etas, 
    q1`f3`o2`qfa`uds`uubar`\[Pi]i0, q1`f3`o2`qfa`dus`dubar`\[Pi]im, 
    q1`f3`o2`qfa`sdu`subar`\[CapitalKappa]im}, 
   {q1`f3`o3`qfa`uus`uubar`\[Eta], q1`f3`o3`qfa`uus`uubar`\[Pi]i0, 
    q1`f3`o3`qfa`uus`uubar`etas, q1`f3`o3`qfa`suu`subar`\[CapitalKappa]im}, 
   {q1`f3`o4`qfa`udu`uubar`\[Eta], q1`f3`o4`qfa`udu`uubar`\[Pi]i0, 
    q1`f3`o4`qfa`udu`uubar`etas, q1`f3`o4`qfa`duu`dubar`\[Pi]im}, 
   {q1`f3`o5`qfa`udd`uubar`\[Eta], q1`f3`o5`qfa`udd`uubar`\[Pi]i0, 
    q1`f3`o5`qfa`udd`uubar`etas, q1`f3`o5`qfa`ddu`dubar`\[Pi]im}, 
   {q1`f3`o6`qfa`dss`dubar`\[Pi]im, 
    q1`f3`o6`qfa`ssd`subar`\[CapitalKappa]im}, 
   {q1`f3`o7`qfa`uss`uubar`\[Eta], q1`f3`o7`qfa`uss`uubar`\[Pi]i0, 
    q1`f3`o7`qfa`uss`uubar`etas, q1`f3`o7`qfa`sus`subar`\[CapitalKappa]im}, 
   {q1`f3`o8`qfa`uds`uubar`\[Pi]i0, q1`f3`o8`qfa`uds`uubar`\[Eta], 
    q1`f3`o8`qfa`uds`uubar`etas, q1`f3`o8`qfa`dus`dubar`\[Pi]im, 
    q1`f3`o8`qfa`sdu`subar`\[CapitalKappa]im}}, 
  {{q1`f4`o1`qfa`dsd`dubar`\[Pi]im, 
    q1`f4`o1`qfa`sdd`subar`\[CapitalKappa]im}, 
   {q1`f4`o2`qfa`uds`uubar`\[Eta], q1`f4`o2`qfa`uds`uubar`etas, 
    q1`f4`o2`qfa`dus`dubar`\[Pi]im, 
    q1`f4`o2`qfa`sdu`subar`\[CapitalKappa]im}, 
   {q1`f4`o3`qfa`uus`uubar`\[Eta], q1`f4`o3`qfa`uus`uubar`\[Pi]i0, 
    q1`f4`o3`qfa`uus`uubar`etas, q1`f4`o3`qfa`suu`subar`\[CapitalKappa]im}, 
   {q1`f4`o4`qfa`udu`uubar`\[Pi]i0, q1`f4`o4`qfa`duu`dubar`\[Pi]im}, 
   {q1`f4`o5`qfa`udd`uubar`\[Pi]i0, q1`f4`o5`qfa`ddu`dubar`\[Pi]im}, 
   {q1`f4`o6`qfa`dss`dubar`\[Pi]im, 
    q1`f4`o6`qfa`ssd`subar`\[CapitalKappa]im}, 
   {q1`f4`o7`qfa`uss`uubar`\[Eta], q1`f4`o7`qfa`uss`uubar`\[Pi]i0, 
    q1`f4`o7`qfa`uss`uubar`etas, q1`f4`o7`qfa`sus`subar`\[CapitalKappa]im}, 
   {q1`f4`o8`qfa`uds`uubar`\[Pi]i0, q1`f4`o8`qfa`dus`dubar`\[Pi]im}}, 
  {{q1`f4`o1`qfa`dsd`dubar`\[Pi]im, 
    q1`f4`o1`qfa`sdd`subar`\[CapitalKappa]im}, 
   {q1`f4`o2`qfa`uds`uubar`\[Eta], q1`f4`o2`qfa`uds`uubar`etas, 
    q1`f4`o2`qfa`dus`dubar`\[Pi]im, 
    q1`f4`o2`qfa`sdu`subar`\[CapitalKappa]im}, 
   {q1`f4`o3`qfa`uus`uubar`\[Eta], q1`f4`o3`qfa`uus`uubar`\[Pi]i0, 
    q1`f4`o3`qfa`uus`uubar`etas, q1`f4`o3`qfa`suu`subar`\[CapitalKappa]im}, 
   {q1`f4`o4`qfa`udu`uubar`\[Pi]i0, q1`f4`o4`qfa`duu`dubar`\[Pi]im}, 
   {q1`f4`o5`qfa`udd`uubar`\[Pi]i0, q1`f4`o5`qfa`ddu`dubar`\[Pi]im}, 
   {q1`f4`o6`qfa`dss`dubar`\[Pi]im, 
    q1`f4`o6`qfa`ssd`subar`\[CapitalKappa]im}, 
   {q1`f4`o7`qfa`uss`uubar`\[Eta], q1`f4`o7`qfa`uss`uubar`\[Pi]i0, 
    q1`f4`o7`qfa`uss`uubar`etas, q1`f4`o7`qfa`sus`subar`\[CapitalKappa]im}, 
   {q1`f4`o8`qfa`uds`uubar`\[Pi]i0, q1`f4`o8`qfa`dus`dubar`\[Pi]im}}, 
  {{q1`f5`o1`qfa`dsd`dubar`\[Pi]im, 
    q1`f5`o1`qfa`sdd`subar`\[CapitalKappa]im}, 
   {q1`f5`o2`qfa`uds`uubar`\[Eta], q1`f5`o2`qfa`uds`uubar`etas, 
    q1`f5`o2`qfa`dus`dubar`\[Pi]im, 
    q1`f5`o2`qfa`sdu`subar`\[CapitalKappa]im}, 
   {q1`f5`o3`qfa`uus`uubar`\[Eta], q1`f5`o3`qfa`uus`uubar`\[Pi]i0, 
    q1`f5`o3`qfa`uus`uubar`etas, q1`f5`o3`qfa`suu`subar`\[CapitalKappa]im}, 
   {q1`f5`o4`qfa`udu`uubar`\[Pi]i0, q1`f5`o4`qfa`duu`dubar`\[Pi]im}, 
   {q1`f5`o5`qfa`udd`uubar`\[Pi]i0, q1`f5`o5`qfa`ddu`dubar`\[Pi]im}, 
   {q1`f5`o6`qfa`dss`dubar`\[Pi]im, 
    q1`f5`o6`qfa`ssd`subar`\[CapitalKappa]im}, 
   {q1`f5`o7`qfa`uss`uubar`\[Eta], q1`f5`o7`qfa`uss`uubar`\[Pi]i0, 
    q1`f5`o7`qfa`uss`uubar`etas, q1`f5`o7`qfa`sus`subar`\[CapitalKappa]im}, 
   {q1`f5`o8`qfa`uds`uubar`\[Pi]i0, q1`f5`o8`qfa`dus`dubar`\[Pi]im}}}, 
 {{{q2`f1`o1`qfa`dsd`ddbar`\[Eta], q2`f1`o1`qfa`dsd`ddbar`\[Pi]i0, 
    q2`f1`o1`qfa`dsd`ddbar`etas, q2`f1`o1`qfa`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f1`o2`qfa`uds`udbar`\[Pi]ip, q2`f1`o2`qfa`dus`ddbar`\[Eta], 
    q2`f1`o2`qfa`dus`ddbar`etas, q2`f1`o2`qfa`dus`ddbar`\[Pi]i0, 
    q2`f1`o2`qfa`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f1`o3`qfa`uus`udbar`\[Pi]ip, 
    q2`f1`o3`qfa`suu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f1`o4`qfa`udu`udbar`\[Pi]ip, q2`f1`o4`qfa`duu`ddbar`\[Eta], 
    q2`f1`o4`qfa`duu`ddbar`\[Pi]i0, q2`f1`o4`qfa`duu`ddbar`etas}, 
   {q2`f1`o5`qfa`udd`udbar`\[Pi]ip, q2`f1`o5`qfa`ddu`ddbar`\[Eta], 
    q2`f1`o5`qfa`ddu`ddbar`\[Pi]i0, q2`f1`o5`qfa`ddu`ddbar`etas}, 
   {q2`f1`o6`qfa`dss`ddbar`\[Eta], q2`f1`o6`qfa`dss`ddbar`\[Pi]i0, 
    q2`f1`o6`qfa`dss`ddbar`etas, q2`f1`o6`qfa`ssd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f1`o7`qfa`uss`udbar`\[Pi]ip, 
    q2`f1`o7`qfa`sus`sdbar`\[CapitalKappa]i0b}, 
   {q2`f1`o8`qfa`uds`udbar`\[Pi]ip, q2`f1`o8`qfa`dus`ddbar`\[Pi]i0, 
    q2`f1`o8`qfa`dus`ddbar`\[Eta], q2`f1`o8`qfa`dus`ddbar`etas, 
    q2`f1`o8`qfa`sdu`sdbar`\[CapitalKappa]i0b}}, 
  {{q2`f2`o1`qfa`dsd`ddbar`\[Eta], q2`f2`o1`qfa`dsd`ddbar`\[Pi]i0, 
    q2`f2`o1`qfa`dsd`ddbar`etas, q2`f2`o1`qfa`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f2`o2`qfa`uds`udbar`\[Pi]ip, q2`f2`o2`qfa`dus`ddbar`\[Eta], 
    q2`f2`o2`qfa`dus`ddbar`etas, q2`f2`o2`qfa`dus`ddbar`\[Pi]i0, 
    q2`f2`o2`qfa`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f2`o3`qfa`uus`udbar`\[Pi]ip, 
    q2`f2`o3`qfa`suu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f2`o4`qfa`udu`udbar`\[Pi]ip, q2`f2`o4`qfa`duu`ddbar`\[Eta], 
    q2`f2`o4`qfa`duu`ddbar`\[Pi]i0, q2`f2`o4`qfa`duu`ddbar`etas}, 
   {q2`f2`o5`qfa`udd`udbar`\[Pi]ip, q2`f2`o5`qfa`ddu`ddbar`\[Eta], 
    q2`f2`o5`qfa`ddu`ddbar`\[Pi]i0, q2`f2`o5`qfa`ddu`ddbar`etas}, 
   {q2`f2`o6`qfa`dss`ddbar`\[Eta], q2`f2`o6`qfa`dss`ddbar`\[Pi]i0, 
    q2`f2`o6`qfa`dss`ddbar`etas, q2`f2`o6`qfa`ssd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f2`o7`qfa`uss`udbar`\[Pi]ip, 
    q2`f2`o7`qfa`sus`sdbar`\[CapitalKappa]i0b}, 
   {q2`f2`o8`qfa`uds`udbar`\[Pi]ip, q2`f2`o8`qfa`dus`ddbar`\[Pi]i0, 
    q2`f2`o8`qfa`dus`ddbar`\[Eta], q2`f2`o8`qfa`dus`ddbar`etas, 
    q2`f2`o8`qfa`sdu`sdbar`\[CapitalKappa]i0b}}, 
  {{q2`f3`o1`qfa`dsd`ddbar`\[Eta], q2`f3`o1`qfa`dsd`ddbar`\[Pi]i0, 
    q2`f3`o1`qfa`dsd`ddbar`etas, q2`f3`o1`qfa`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f3`o2`qfa`uds`udbar`\[Pi]ip, q2`f3`o2`qfa`dus`ddbar`\[Eta], 
    q2`f3`o2`qfa`dus`ddbar`etas, q2`f3`o2`qfa`dus`ddbar`\[Pi]i0, 
    q2`f3`o2`qfa`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f3`o3`qfa`uus`udbar`\[Pi]ip, 
    q2`f3`o3`qfa`suu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f3`o4`qfa`udu`udbar`\[Pi]ip, q2`f3`o4`qfa`duu`ddbar`\[Eta], 
    q2`f3`o4`qfa`duu`ddbar`\[Pi]i0, q2`f3`o4`qfa`duu`ddbar`etas}, 
   {q2`f3`o5`qfa`udd`udbar`\[Pi]ip, q2`f3`o5`qfa`ddu`ddbar`\[Eta], 
    q2`f3`o5`qfa`ddu`ddbar`\[Pi]i0, q2`f3`o5`qfa`ddu`ddbar`etas}, 
   {q2`f3`o6`qfa`dss`ddbar`\[Eta], q2`f3`o6`qfa`dss`ddbar`\[Pi]i0, 
    q2`f3`o6`qfa`dss`ddbar`etas, q2`f3`o6`qfa`ssd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f3`o7`qfa`uss`udbar`\[Pi]ip, 
    q2`f3`o7`qfa`sus`sdbar`\[CapitalKappa]i0b}, 
   {q2`f3`o8`qfa`uds`udbar`\[Pi]ip, q2`f3`o8`qfa`dus`ddbar`\[Pi]i0, 
    q2`f3`o8`qfa`dus`ddbar`\[Eta], q2`f3`o8`qfa`dus`ddbar`etas, 
    q2`f3`o8`qfa`sdu`sdbar`\[CapitalKappa]i0b}}, 
  {{q2`f4`o1`qfa`dsd`ddbar`\[Eta], q2`f4`o1`qfa`dsd`ddbar`\[Pi]i0, 
    q2`f4`o1`qfa`dsd`ddbar`etas, q2`f4`o1`qfa`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o2`qfa`uds`udbar`\[Pi]ip, q2`f4`o2`qfa`dus`ddbar`\[Eta], 
    q2`f4`o2`qfa`dus`ddbar`etas, q2`f4`o2`qfa`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o3`qfa`uus`udbar`\[Pi]ip, 
    q2`f4`o3`qfa`suu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o4`qfa`udu`udbar`\[Pi]ip, q2`f4`o4`qfa`duu`ddbar`\[Pi]i0}, 
   {q2`f4`o5`qfa`udd`udbar`\[Pi]ip, q2`f4`o5`qfa`ddu`ddbar`\[Pi]i0}, 
   {q2`f4`o6`qfa`dss`ddbar`\[Eta], q2`f4`o6`qfa`dss`ddbar`\[Pi]i0, 
    q2`f4`o6`qfa`dss`ddbar`etas, q2`f4`o6`qfa`ssd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o7`qfa`uss`udbar`\[Pi]ip, 
    q2`f4`o7`qfa`sus`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o8`qfa`uds`udbar`\[Pi]ip, q2`f4`o8`qfa`dus`ddbar`\[Pi]i0}}, 
  {{q2`f4`o1`qfa`dsd`ddbar`\[Eta], q2`f4`o1`qfa`dsd`ddbar`\[Pi]i0, 
    q2`f4`o1`qfa`dsd`ddbar`etas, q2`f4`o1`qfa`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o2`qfa`uds`udbar`\[Pi]ip, q2`f4`o2`qfa`dus`ddbar`\[Eta], 
    q2`f4`o2`qfa`dus`ddbar`etas, q2`f4`o2`qfa`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o3`qfa`uus`udbar`\[Pi]ip, 
    q2`f4`o3`qfa`suu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o4`qfa`udu`udbar`\[Pi]ip, q2`f4`o4`qfa`duu`ddbar`\[Pi]i0}, 
   {q2`f4`o5`qfa`udd`udbar`\[Pi]ip, q2`f4`o5`qfa`ddu`ddbar`\[Pi]i0}, 
   {q2`f4`o6`qfa`dss`ddbar`\[Eta], q2`f4`o6`qfa`dss`ddbar`\[Pi]i0, 
    q2`f4`o6`qfa`dss`ddbar`etas, q2`f4`o6`qfa`ssd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o7`qfa`uss`udbar`\[Pi]ip, 
    q2`f4`o7`qfa`sus`sdbar`\[CapitalKappa]i0b}, 
   {q2`f4`o8`qfa`uds`udbar`\[Pi]ip, q2`f4`o8`qfa`dus`ddbar`\[Pi]i0}}, 
  {{q2`f5`o1`qfa`dsd`ddbar`\[Eta], q2`f5`o1`qfa`dsd`ddbar`\[Pi]i0, 
    q2`f5`o1`qfa`dsd`ddbar`etas, q2`f5`o1`qfa`sdd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f5`o2`qfa`uds`udbar`\[Pi]ip, q2`f5`o2`qfa`dus`ddbar`\[Eta], 
    q2`f5`o2`qfa`dus`ddbar`etas, q2`f5`o2`qfa`sdu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f5`o3`qfa`uus`udbar`\[Pi]ip, 
    q2`f5`o3`qfa`suu`sdbar`\[CapitalKappa]i0b}, 
   {q2`f5`o4`qfa`udu`udbar`\[Pi]ip, q2`f5`o4`qfa`duu`ddbar`\[Pi]i0}, 
   {q2`f5`o5`qfa`udd`udbar`\[Pi]ip, q2`f5`o5`qfa`ddu`ddbar`\[Pi]i0}, 
   {q2`f5`o6`qfa`dss`ddbar`\[Eta], q2`f5`o6`qfa`dss`ddbar`\[Pi]i0, 
    q2`f5`o6`qfa`dss`ddbar`etas, q2`f5`o6`qfa`ssd`sdbar`\[CapitalKappa]i0b}, 
   {q2`f5`o7`qfa`uss`udbar`\[Pi]ip, 
    q2`f5`o7`qfa`sus`sdbar`\[CapitalKappa]i0b}, 
   {q2`f5`o8`qfa`uds`udbar`\[Pi]ip, q2`f5`o8`qfa`dus`ddbar`\[Pi]i0}}}, 
 {{{q3`f1`o1`qfa`dsd`dsbar`\[CapitalKappa]i0, q3`f1`o1`qfa`sdd`ssbar`\[Eta], 
    q3`f1`o1`qfa`sdd`ssbar`etas}, {q3`f1`o2`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f1`o2`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f1`o2`qfa`sdu`ssbar`\[Eta], 
    q3`f1`o2`qfa`sdu`ssbar`etas}, {q3`f1`o3`qfa`uus`usbar`\[CapitalKappa]ip, 
    q3`f1`o3`qfa`suu`ssbar`\[Eta], q3`f1`o3`qfa`suu`ssbar`etas}, 
   {q3`f1`o4`qfa`udu`usbar`\[CapitalKappa]ip, 
    q3`f1`o4`qfa`duu`dsbar`\[CapitalKappa]i0}, 
   {q3`f1`o5`qfa`udd`usbar`\[CapitalKappa]ip, 
    q3`f1`o5`qfa`ddu`dsbar`\[CapitalKappa]i0}, 
   {q3`f1`o6`qfa`dss`dsbar`\[CapitalKappa]i0, q3`f1`o6`qfa`ssd`ssbar`\[Eta], 
    q3`f1`o6`qfa`ssd`ssbar`etas}, {q3`f1`o7`qfa`uss`usbar`\[CapitalKappa]ip, 
    q3`f1`o7`qfa`sus`ssbar`\[Eta], q3`f1`o7`qfa`sus`ssbar`etas}, 
   {q3`f1`o8`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f1`o8`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f1`o8`qfa`sdu`ssbar`\[Eta], 
    q3`f1`o8`qfa`sdu`ssbar`etas}}, 
  {{q3`f2`o1`qfa`dsd`dsbar`\[CapitalKappa]i0, q3`f2`o1`qfa`sdd`ssbar`\[Eta], 
    q3`f2`o1`qfa`sdd`ssbar`etas}, {q3`f2`o2`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f2`o2`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f2`o2`qfa`sdu`ssbar`\[Eta], 
    q3`f2`o2`qfa`sdu`ssbar`etas}, {q3`f2`o3`qfa`uus`usbar`\[CapitalKappa]ip, 
    q3`f2`o3`qfa`suu`ssbar`\[Eta], q3`f2`o3`qfa`suu`ssbar`etas}, 
   {q3`f2`o4`qfa`udu`usbar`\[CapitalKappa]ip, 
    q3`f2`o4`qfa`duu`dsbar`\[CapitalKappa]i0}, 
   {q3`f2`o5`qfa`udd`usbar`\[CapitalKappa]ip, 
    q3`f2`o5`qfa`ddu`dsbar`\[CapitalKappa]i0}, 
   {q3`f2`o6`qfa`dss`dsbar`\[CapitalKappa]i0, q3`f2`o6`qfa`ssd`ssbar`\[Eta], 
    q3`f2`o6`qfa`ssd`ssbar`etas}, {q3`f2`o7`qfa`uss`usbar`\[CapitalKappa]ip, 
    q3`f2`o7`qfa`sus`ssbar`\[Eta], q3`f2`o7`qfa`sus`ssbar`etas}, 
   {q3`f2`o8`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f2`o8`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f2`o8`qfa`sdu`ssbar`\[Eta], 
    q3`f2`o8`qfa`sdu`ssbar`etas}}, 
  {{q3`f3`o1`qfa`dsd`dsbar`\[CapitalKappa]i0, q3`f3`o1`qfa`sdd`ssbar`\[Eta], 
    q3`f3`o1`qfa`sdd`ssbar`etas}, {q3`f3`o2`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f3`o2`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f3`o2`qfa`sdu`ssbar`\[Eta], 
    q3`f3`o2`qfa`sdu`ssbar`etas}, {q3`f3`o3`qfa`uus`usbar`\[CapitalKappa]ip, 
    q3`f3`o3`qfa`suu`ssbar`\[Eta], q3`f3`o3`qfa`suu`ssbar`etas}, 
   {q3`f3`o4`qfa`udu`usbar`\[CapitalKappa]ip, 
    q3`f3`o4`qfa`duu`dsbar`\[CapitalKappa]i0}, 
   {q3`f3`o5`qfa`udd`usbar`\[CapitalKappa]ip, 
    q3`f3`o5`qfa`ddu`dsbar`\[CapitalKappa]i0}, 
   {q3`f3`o6`qfa`dss`dsbar`\[CapitalKappa]i0, q3`f3`o6`qfa`ssd`ssbar`\[Eta], 
    q3`f3`o6`qfa`ssd`ssbar`etas}, {q3`f3`o7`qfa`uss`usbar`\[CapitalKappa]ip, 
    q3`f3`o7`qfa`sus`ssbar`\[Eta], q3`f3`o7`qfa`sus`ssbar`etas}, 
   {q3`f3`o8`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f3`o8`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f3`o8`qfa`sdu`ssbar`\[Eta], 
    q3`f3`o8`qfa`sdu`ssbar`etas}}, 
  {{q3`f4`o1`qfa`dsd`dsbar`\[CapitalKappa]i0, q3`f4`o1`qfa`sdd`ssbar`\[Eta], 
    q3`f4`o1`qfa`sdd`ssbar`etas}, {q3`f4`o2`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f4`o2`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f4`o2`qfa`sdu`ssbar`\[Eta], 
    q3`f4`o2`qfa`sdu`ssbar`etas}, {q3`f4`o3`qfa`uus`usbar`\[CapitalKappa]ip, 
    q3`f4`o3`qfa`suu`ssbar`\[Eta], q3`f4`o3`qfa`suu`ssbar`etas}, 
   {q3`f4`o4`qfa`udu`usbar`\[CapitalKappa]ip, 
    q3`f4`o4`qfa`duu`dsbar`\[CapitalKappa]i0}, 
   {q3`f4`o5`qfa`udd`usbar`\[CapitalKappa]ip, 
    q3`f4`o5`qfa`ddu`dsbar`\[CapitalKappa]i0}, 
   {q3`f4`o6`qfa`dss`dsbar`\[CapitalKappa]i0, q3`f4`o6`qfa`ssd`ssbar`\[Eta], 
    q3`f4`o6`qfa`ssd`ssbar`etas}, {q3`f4`o7`qfa`uss`usbar`\[CapitalKappa]ip, 
    q3`f4`o7`qfa`sus`ssbar`\[Eta], q3`f4`o7`qfa`sus`ssbar`etas}, 
   {q3`f4`o8`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f4`o8`qfa`dus`dsbar`\[CapitalKappa]i0}}, 
  {{q3`f4`o1`qfa`dsd`dsbar`\[CapitalKappa]i0, q3`f4`o1`qfa`sdd`ssbar`\[Eta], 
    q3`f4`o1`qfa`sdd`ssbar`etas}, {q3`f4`o2`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f4`o2`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f4`o2`qfa`sdu`ssbar`\[Eta], 
    q3`f4`o2`qfa`sdu`ssbar`etas}, {q3`f4`o3`qfa`uus`usbar`\[CapitalKappa]ip, 
    q3`f4`o3`qfa`suu`ssbar`\[Eta], q3`f4`o3`qfa`suu`ssbar`etas}, 
   {q3`f4`o4`qfa`udu`usbar`\[CapitalKappa]ip, 
    q3`f4`o4`qfa`duu`dsbar`\[CapitalKappa]i0}, 
   {q3`f4`o5`qfa`udd`usbar`\[CapitalKappa]ip, 
    q3`f4`o5`qfa`ddu`dsbar`\[CapitalKappa]i0}, 
   {q3`f4`o6`qfa`dss`dsbar`\[CapitalKappa]i0, q3`f4`o6`qfa`ssd`ssbar`\[Eta], 
    q3`f4`o6`qfa`ssd`ssbar`etas}, {q3`f4`o7`qfa`uss`usbar`\[CapitalKappa]ip, 
    q3`f4`o7`qfa`sus`ssbar`\[Eta], q3`f4`o7`qfa`sus`ssbar`etas}, 
   {q3`f4`o8`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f4`o8`qfa`dus`dsbar`\[CapitalKappa]i0}}, 
  {{q3`f5`o1`qfa`dsd`dsbar`\[CapitalKappa]i0, q3`f5`o1`qfa`sdd`ssbar`\[Eta], 
    q3`f5`o1`qfa`sdd`ssbar`etas}, {q3`f5`o2`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f5`o2`qfa`dus`dsbar`\[CapitalKappa]i0, q3`f5`o2`qfa`sdu`ssbar`\[Eta], 
    q3`f5`o2`qfa`sdu`ssbar`etas}, {q3`f5`o3`qfa`uus`usbar`\[CapitalKappa]ip, 
    q3`f5`o3`qfa`suu`ssbar`\[Eta], q3`f5`o3`qfa`suu`ssbar`etas}, 
   {q3`f5`o4`qfa`udu`usbar`\[CapitalKappa]ip, 
    q3`f5`o4`qfa`duu`dsbar`\[CapitalKappa]i0}, 
   {q3`f5`o5`qfa`udd`usbar`\[CapitalKappa]ip, 
    q3`f5`o5`qfa`ddu`dsbar`\[CapitalKappa]i0}, 
   {q3`f5`o6`qfa`dss`dsbar`\[CapitalKappa]i0, q3`f5`o6`qfa`ssd`ssbar`\[Eta], 
    q3`f5`o6`qfa`ssd`ssbar`etas}, {q3`f5`o7`qfa`uss`usbar`\[CapitalKappa]ip, 
    q3`f5`o7`qfa`sus`ssbar`\[Eta], q3`f5`o7`qfa`sus`ssbar`etas}, 
   {q3`f5`o8`qfa`uds`usbar`\[CapitalKappa]ip, 
    q3`f5`o8`qfa`dus`dsbar`\[CapitalKappa]i0}}}}
