{{{{}, {d`f1`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f1`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f1`o1`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f1`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    d`f1`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f1`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f1`o1`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f1`o1`\[CapitalSigma]m`ddd`\[CapitalKappa]i0b}, 
   {s`f1`o1`\[CapitalSigma]m`ddd`\[CapitalKappa]i0b, 
    s`f1`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalKappa]i0}}, 
  {{u`f1`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[Pi]ip, 
    u`f1`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalKappa]ip, 
    u`f1`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[Pi]im, 
    u`f1`o2`\[CapitalSigma]0`Np`\[CapitalKappa]im}, 
   {d`f1`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[Pi]im, 
    d`f1`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    d`f1`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[Pi]ip, 
    d`f1`o2`\[CapitalSigma]0`Nn`\[CapitalKappa]i0b}, 
   {s`f1`o2`\[CapitalSigma]0`Np`\[CapitalKappa]im, 
    s`f1`o2`\[CapitalSigma]0`Nn`\[CapitalKappa]i0b, 
    s`f1`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f1`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalKappa]i0}}, 
  {{u`f1`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f1`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f1`o3`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f1`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalKappa]ip, 
    u`f1`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f1`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f1`o3`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f1`o3`\[CapitalSigma]p`uuu`\[CapitalKappa]im}, {}, 
   {s`f1`o3`\[CapitalSigma]p`uuu`\[CapitalKappa]im, 
    s`f1`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalKappa]ip}}, 
  {{u`f1`o4`Np`Np`\[Eta], u`f1`o4`Np`Np`\[Pi]i0, u`f1`o4`Np`Np`etas, 
    u`f1`o4`Np`Nn`\[Pi]ip, u`f1`o4`Np`Np`\[Eta], u`f1`o4`Np`Np`\[Pi]i0, 
    u`f1`o4`Np`Np`etas, u`f1`o4`Np`uuu`\[Pi]im}, 
   {d`f1`o4`Np`uuu`\[Pi]im, d`f1`o4`Np`Nn`\[Pi]ip}, {}}, 
  {{u`f1`o5`Nn`ddd`\[Pi]ip, u`f1`o5`Nn`Np`\[Pi]im}, 
   {d`f1`o5`Nn`Np`\[Pi]im, d`f1`o5`Nn`Nn`\[Eta], d`f1`o5`Nn`Nn`\[Pi]i0, 
    d`f1`o5`Nn`Nn`etas, d`f1`o5`Nn`ddd`\[Pi]ip, d`f1`o5`Nn`Nn`\[Eta], 
    d`f1`o5`Nn`Nn`\[Pi]i0, d`f1`o5`Nn`Nn`etas}, {}}, 
  {{}, {d`f1`o6`\[CapitalXi]m`sss`\[CapitalKappa]i0, 
    d`f1`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalKappa]i0b}, 
   {s`f1`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalKappa]i0b, 
    s`f1`o6`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f1`o6`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f1`o6`\[CapitalXi]m`sss`\[CapitalKappa]i0, 
    s`f1`o6`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f1`o6`\[CapitalXi]m`\[CapitalXi]m`etas}}, 
  {{u`f1`o7`\[CapitalXi]0`sss`\[CapitalKappa]ip, 
    u`f1`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalKappa]im}, {}, 
   {s`f1`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalKappa]im, 
    s`f1`o7`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f1`o7`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f1`o7`\[CapitalXi]0`sss`\[CapitalKappa]ip, 
    s`f1`o7`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f1`o7`\[CapitalXi]0`\[CapitalXi]0`etas}}, 
  {{u`f1`o8`\[CapitalLambda]`\[CapitalSigma]m`\[Pi]ip, 
    u`f1`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalKappa]ip, 
    u`f1`o8`\[CapitalLambda]`\[CapitalSigma]p`\[Pi]im, 
    u`f1`o8`\[CapitalLambda]`Np`\[CapitalKappa]im}, 
   {d`f1`o8`\[CapitalLambda]`\[CapitalSigma]p`\[Pi]im, 
    d`f1`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalKappa]i0, 
    d`f1`o8`\[CapitalLambda]`\[CapitalSigma]m`\[Pi]ip, 
    d`f1`o8`\[CapitalLambda]`Nn`\[CapitalKappa]i0b}, 
   {s`f1`o8`\[CapitalLambda]`Np`\[CapitalKappa]im, 
    s`f1`o8`\[CapitalLambda]`Nn`\[CapitalKappa]i0b, 
    s`f1`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f1`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalKappa]i0}}}, 
 {{{}, {d`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f2`o1`\[CapitalSigma]m`ddd`ddd`\[CapitalKappa]i0b, 
    d`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f2`o1`\[CapitalSigma]m`ddd`ddd`\[CapitalKappa]i0b, 
    d`f2`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    d`f2`o1`\[CapitalSigma]m`ddd`ddd`\[CapitalKappa]i0b}, 
   {s`f2`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    s`f2`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    s`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    s`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    s`f2`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`etas}}, 
  {{u`f2`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f2`o2`\[CapitalSigma]0`Np`Np`\[CapitalKappa]im, 
    u`f2`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f2`o2`\[CapitalSigma]0`Np`Np`\[CapitalKappa]im, 
    u`f2`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    u`f2`o2`\[CapitalSigma]0`Nn`Nn`\[CapitalKappa]i0b}, 
   {d`f2`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f2`o2`\[CapitalSigma]0`Nn`Nn`\[CapitalKappa]i0b, 
    d`f2`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f2`o2`\[CapitalSigma]0`Nn`Nn`\[CapitalKappa]i0b, 
    d`f2`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    d`f2`o2`\[CapitalSigma]0`Np`Np`\[CapitalKappa]im}, 
   {s`f2`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f2`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f2`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f2`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f2`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    s`f2`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im}}, 
  {{u`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f2`o3`\[CapitalSigma]p`uuu`uuu`\[CapitalKappa]im, 
    u`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f2`o3`\[CapitalSigma]p`uuu`uuu`\[CapitalKappa]im, 
    u`f2`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]ip, 
    u`f2`o3`\[CapitalSigma]p`uuu`uuu`\[CapitalKappa]im}, {}, 
   {s`f2`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]ip, 
    s`f2`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]ip, 
    s`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    s`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    s`f2`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`etas}}, 
  {{u`f2`o4`Np`Np`Np`\[Eta], u`f2`o4`Np`Np`Np`\[Pi]i0, u`f2`o4`Np`Np`Np`etas, 
    u`f2`o4`Np`uuu`uuu`\[Pi]im, u`f2`o4`Np`Np`Np`\[Eta], 
    u`f2`o4`Np`Np`Np`\[Pi]i0, u`f2`o4`Np`Np`Np`etas, 
    u`f2`o4`Np`uuu`uuu`\[Pi]im, u`f2`o4`Np`Nn`Nn`\[Pi]ip, 
    u`f2`o4`Np`uuu`uuu`\[Pi]im}, {d`f2`o4`Np`Nn`Nn`\[Pi]ip, 
    d`f2`o4`Np`Nn`Nn`\[Pi]ip, d`f2`o4`Np`Np`Np`\[Eta], 
    d`f2`o4`Np`Np`Np`\[Pi]i0, d`f2`o4`Np`Np`Np`etas}, {}}, 
  {{u`f2`o5`Nn`Np`Np`\[Pi]im, u`f2`o5`Nn`Np`Np`\[Pi]im, 
    u`f2`o5`Nn`Nn`Nn`\[Eta], u`f2`o5`Nn`Nn`Nn`\[Pi]i0, 
    u`f2`o5`Nn`Nn`Nn`etas}, {d`f2`o5`Nn`ddd`ddd`\[Pi]ip, 
    d`f2`o5`Nn`Nn`Nn`\[Eta], d`f2`o5`Nn`Nn`Nn`\[Pi]i0, d`f2`o5`Nn`Nn`Nn`etas, 
    d`f2`o5`Nn`ddd`ddd`\[Pi]ip, d`f2`o5`Nn`Nn`Nn`\[Eta], 
    d`f2`o5`Nn`Nn`Nn`\[Pi]i0, d`f2`o5`Nn`Nn`Nn`etas, 
    d`f2`o5`Nn`ddd`ddd`\[Pi]ip, d`f2`o5`Nn`Np`Np`\[Pi]im}, {}}, 
  {{}, 
   {d`f2`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalKappa]i0\
b, 
    d`f2`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalKappa]i0b\
, d`f2`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    d`f2`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`etas}, 
   {s`f2`o6`\[CapitalXi]m`sss`sss`\[CapitalKappa]i0, 
    s`f2`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f2`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f2`o6`\[CapitalXi]m`sss`sss`\[CapitalKappa]i0, 
    s`f2`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f2`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f2`o6`\[CapitalXi]m`sss`sss`\[CapitalKappa]i0, s`f2`o6`\[CapitalXi]m`\
\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalKappa]i0b}}, 
  {
   {
    u`f2`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalKappa]im\
, u`f2`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalKappa]im, 
    u`f2`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    u`f2`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`etas}, {}, 
   {s`f2`o7`\[CapitalXi]0`sss`sss`\[CapitalKappa]ip, 
    s`f2`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f2`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f2`o7`\[CapitalXi]0`sss`sss`\[CapitalKappa]ip, 
    s`f2`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f2`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f2`o7`\[CapitalXi]0`sss`sss`\[CapitalKappa]ip, 
    s`f2`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalKappa]im}\
}, {{u`f2`o8`\[CapitalLambda]`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f2`o8`\[CapitalLambda]`Np`Np`\[CapitalKappa]im, 
    u`f2`o8`\[CapitalLambda]`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f2`o8`\[CapitalLambda]`Np`Np`\[CapitalKappa]im, 
    u`f2`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    u`f2`o8`\[CapitalLambda]`Nn`Nn`\[CapitalKappa]i0b}, 
   {d`f2`o8`\[CapitalLambda]`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f2`o8`\[CapitalLambda]`Nn`Nn`\[CapitalKappa]i0b, 
    d`f2`o8`\[CapitalLambda]`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f2`o8`\[CapitalLambda]`Nn`Nn`\[CapitalKappa]i0b, 
    d`f2`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    d`f2`o8`\[CapitalLambda]`Np`Np`\[CapitalKappa]im}, 
   {s`f2`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f2`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f2`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f2`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f2`o8`\[CapitalLambda]`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    s`f2`o8`\[CapitalLambda]`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im}}}, 
 {{{}, {d`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f3`o1`\[CapitalSigma]m`ddd`ddd`\[CapitalKappa]i0b, 
    d`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f3`o1`\[CapitalSigma]m`ddd`ddd`\[CapitalKappa]i0b, 
    d`f3`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    d`f3`o1`\[CapitalSigma]m`ddd`ddd`\[CapitalKappa]i0b}, 
   {s`f3`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    s`f3`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    s`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    s`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    s`f3`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalSigma]m`etas}}, 
  {{u`f3`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f3`o2`\[CapitalSigma]0`Np`Np`\[CapitalKappa]im, 
    u`f3`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f3`o2`\[CapitalSigma]0`Np`Np`\[CapitalKappa]im, 
    u`f3`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    u`f3`o2`\[CapitalSigma]0`Nn`Nn`\[CapitalKappa]i0b}, 
   {d`f3`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f3`o2`\[CapitalSigma]0`Nn`Nn`\[CapitalKappa]i0b, 
    d`f3`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f3`o2`\[CapitalSigma]0`Nn`Nn`\[CapitalKappa]i0b, 
    d`f3`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    d`f3`o2`\[CapitalSigma]0`Np`Np`\[CapitalKappa]im}, 
   {s`f3`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f3`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f3`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f3`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f3`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    s`f3`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im}}, 
  {{u`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f3`o3`\[CapitalSigma]p`uuu`uuu`\[CapitalKappa]im, 
    u`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f3`o3`\[CapitalSigma]p`uuu`uuu`\[CapitalKappa]im, 
    u`f3`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]ip, 
    u`f3`o3`\[CapitalSigma]p`uuu`uuu`\[CapitalKappa]im}, {}, 
   {s`f3`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]ip, 
    s`f3`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]ip, 
    s`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    s`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    s`f3`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalSigma]p`etas}}, 
  {{u`f3`o4`Np`Np`Np`\[Eta], u`f3`o4`Np`Np`Np`\[Pi]i0, u`f3`o4`Np`Np`Np`etas, 
    u`f3`o4`Np`uuu`uuu`\[Pi]im, u`f3`o4`Np`Np`Np`\[Eta], 
    u`f3`o4`Np`Np`Np`\[Pi]i0, u`f3`o4`Np`Np`Np`etas, 
    u`f3`o4`Np`uuu`uuu`\[Pi]im, u`f3`o4`Np`Nn`Nn`\[Pi]ip, 
    u`f3`o4`Np`uuu`uuu`\[Pi]im}, {d`f3`o4`Np`Nn`Nn`\[Pi]ip, 
    d`f3`o4`Np`Nn`Nn`\[Pi]ip, d`f3`o4`Np`Np`Np`\[Eta], 
    d`f3`o4`Np`Np`Np`\[Pi]i0, d`f3`o4`Np`Np`Np`etas}, {}}, 
  {{u`f3`o5`Nn`Np`Np`\[Pi]im, u`f3`o5`Nn`Np`Np`\[Pi]im, 
    u`f3`o5`Nn`Nn`Nn`\[Eta], u`f3`o5`Nn`Nn`Nn`\[Pi]i0, 
    u`f3`o5`Nn`Nn`Nn`etas}, {d`f3`o5`Nn`ddd`ddd`\[Pi]ip, 
    d`f3`o5`Nn`Nn`Nn`\[Eta], d`f3`o5`Nn`Nn`Nn`\[Pi]i0, d`f3`o5`Nn`Nn`Nn`etas, 
    d`f3`o5`Nn`ddd`ddd`\[Pi]ip, d`f3`o5`Nn`Nn`Nn`\[Eta], 
    d`f3`o5`Nn`Nn`Nn`\[Pi]i0, d`f3`o5`Nn`Nn`Nn`etas, 
    d`f3`o5`Nn`ddd`ddd`\[Pi]ip, d`f3`o5`Nn`Np`Np`\[Pi]im}, {}}, 
  {{}, 
   {d`f3`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalKappa]i0\
b, 
    d`f3`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalKappa]i0b\
, d`f3`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    d`f3`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`etas}, 
   {s`f3`o6`\[CapitalXi]m`sss`sss`\[CapitalKappa]i0, 
    s`f3`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f3`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f3`o6`\[CapitalXi]m`sss`sss`\[CapitalKappa]i0, 
    s`f3`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f3`o6`\[CapitalXi]m`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f3`o6`\[CapitalXi]m`sss`sss`\[CapitalKappa]i0, s`f3`o6`\[CapitalXi]m`\
\[CapitalSigma]m`\[CapitalSigma]m`\[CapitalKappa]i0b}}, 
  {
   {
    u`f3`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalKappa]im\
, u`f3`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalKappa]im, 
    u`f3`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    u`f3`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`etas}, {}, 
   {s`f3`o7`\[CapitalXi]0`sss`sss`\[CapitalKappa]ip, 
    s`f3`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f3`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f3`o7`\[CapitalXi]0`sss`sss`\[CapitalKappa]ip, 
    s`f3`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f3`o7`\[CapitalXi]0`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f3`o7`\[CapitalXi]0`sss`sss`\[CapitalKappa]ip, 
    s`f3`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalSigma]p`\[CapitalKappa]im}\
}, {{u`f3`o8`\[CapitalLambda]`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f3`o8`\[CapitalLambda]`Np`Np`\[CapitalKappa]im, 
    u`f3`o8`\[CapitalLambda]`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im, 
    u`f3`o8`\[CapitalLambda]`Np`Np`\[CapitalKappa]im, 
    u`f3`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    u`f3`o8`\[CapitalLambda]`Nn`Nn`\[CapitalKappa]i0b}, 
   {d`f3`o8`\[CapitalLambda]`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f3`o8`\[CapitalLambda]`Nn`Nn`\[CapitalKappa]i0b, 
    d`f3`o8`\[CapitalLambda]`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    d`f3`o8`\[CapitalLambda]`Nn`Nn`\[CapitalKappa]i0b, 
    d`f3`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    d`f3`o8`\[CapitalLambda]`Np`Np`\[CapitalKappa]im}, 
   {s`f3`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f3`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f3`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f3`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f3`o8`\[CapitalLambda]`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]ip, 
    s`f3`o8`\[CapitalLambda]`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]im}}}, 
 {{{}, {d`f4`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f4`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f4`o1`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f4`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    d`f4`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f4`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f4`o1`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f4`o1`\[CapitalSigma]m`ddd`\[CapitalKappa]i0b}, 
   {s`f4`o1`\[CapitalSigma]m`ddd`\[CapitalKappa]i0b, 
    s`f4`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalKappa]i0}}, 
  {{u`f4`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[Pi]ip, 
    u`f4`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalKappa]ip, 
    u`f4`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[Pi]im, 
    u`f4`o2`\[CapitalSigma]0`Np`\[CapitalKappa]im}, 
   {d`f4`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[Pi]im, 
    d`f4`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    d`f4`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[Pi]ip, 
    d`f4`o2`\[CapitalSigma]0`Nn`\[CapitalKappa]i0b}, 
   {s`f4`o2`\[CapitalSigma]0`Np`\[CapitalKappa]im, 
    s`f4`o2`\[CapitalSigma]0`Nn`\[CapitalKappa]i0b, 
    s`f4`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f4`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalKappa]i0}}, 
  {{u`f4`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f4`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f4`o3`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f4`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalKappa]ip, 
    u`f4`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f4`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f4`o3`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f4`o3`\[CapitalSigma]p`uuu`\[CapitalKappa]im}, {}, 
   {s`f4`o3`\[CapitalSigma]p`uuu`\[CapitalKappa]im, 
    s`f4`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalKappa]ip}}, 
  {{u`f4`o4`Np`Np`\[Eta], u`f4`o4`Np`Np`\[Pi]i0, u`f4`o4`Np`Np`etas, 
    u`f4`o4`Np`Nn`\[Pi]ip, u`f4`o4`Np`Np`\[Eta], u`f4`o4`Np`Np`\[Pi]i0, 
    u`f4`o4`Np`Np`etas, u`f4`o4`Np`uuu`\[Pi]im}, 
   {d`f4`o4`Np`uuu`\[Pi]im, d`f4`o4`Np`Nn`\[Pi]ip}, {}}, 
  {{u`f4`o5`Nn`ddd`\[Pi]ip, u`f4`o5`Nn`Np`\[Pi]im}, 
   {d`f4`o5`Nn`Np`\[Pi]im, d`f4`o5`Nn`Nn`\[Eta], d`f4`o5`Nn`Nn`\[Pi]i0, 
    d`f4`o5`Nn`Nn`etas, d`f4`o5`Nn`ddd`\[Pi]ip, d`f4`o5`Nn`Nn`\[Eta], 
    d`f4`o5`Nn`Nn`\[Pi]i0, d`f4`o5`Nn`Nn`etas}, {}}, 
  {{}, {d`f4`o6`\[CapitalXi]m`sss`\[CapitalKappa]i0, 
    d`f4`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalKappa]i0b}, 
   {s`f4`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalKappa]i0b, 
    s`f4`o6`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f4`o6`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f4`o6`\[CapitalXi]m`sss`\[CapitalKappa]i0, 
    s`f4`o6`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f4`o6`\[CapitalXi]m`\[CapitalXi]m`etas}}, 
  {{u`f4`o7`\[CapitalXi]0`sss`\[CapitalKappa]ip, 
    u`f4`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalKappa]im}, {}, 
   {s`f4`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalKappa]im, 
    s`f4`o7`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f4`o7`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f4`o7`\[CapitalXi]0`sss`\[CapitalKappa]ip, 
    s`f4`o7`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f4`o7`\[CapitalXi]0`\[CapitalXi]0`etas}}, 
  {{u`f4`o8`\[CapitalLambda]`\[CapitalSigma]m`\[Pi]ip, 
    u`f4`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalKappa]ip, 
    u`f4`o8`\[CapitalLambda]`\[CapitalSigma]p`\[Pi]im, 
    u`f4`o8`\[CapitalLambda]`Np`\[CapitalKappa]im}, 
   {d`f4`o8`\[CapitalLambda]`\[CapitalSigma]p`\[Pi]im, 
    d`f4`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalKappa]i0, 
    d`f4`o8`\[CapitalLambda]`\[CapitalSigma]m`\[Pi]ip, 
    d`f4`o8`\[CapitalLambda]`Nn`\[CapitalKappa]i0b}, 
   {s`f4`o8`\[CapitalLambda]`Np`\[CapitalKappa]im, 
    s`f4`o8`\[CapitalLambda]`Nn`\[CapitalKappa]i0b, 
    s`f4`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f4`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalKappa]i0}}}, 
 {{{}, {d`f5`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f5`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f5`o1`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f5`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalKappa]i0, 
    d`f5`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Eta], 
    d`f5`o1`\[CapitalSigma]m`\[CapitalSigma]m`\[Pi]i0, 
    d`f5`o1`\[CapitalSigma]m`\[CapitalSigma]m`etas, 
    d`f5`o1`\[CapitalSigma]m`ddd`\[CapitalKappa]i0b}, 
   {s`f5`o1`\[CapitalSigma]m`ddd`\[CapitalKappa]i0b, 
    s`f5`o1`\[CapitalSigma]m`\[CapitalXi]m`\[CapitalKappa]i0}}, 
  {{u`f5`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[Pi]ip, 
    u`f5`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalKappa]ip, 
    u`f5`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[Pi]im, 
    u`f5`o2`\[CapitalSigma]0`Np`\[CapitalKappa]im}, 
   {d`f5`o2`\[CapitalSigma]0`\[CapitalSigma]p`\[Pi]im, 
    d`f5`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalKappa]i0, 
    d`f5`o2`\[CapitalSigma]0`\[CapitalSigma]m`\[Pi]ip, 
    d`f5`o2`\[CapitalSigma]0`Nn`\[CapitalKappa]i0b}, 
   {s`f5`o2`\[CapitalSigma]0`Np`\[CapitalKappa]im, 
    s`f5`o2`\[CapitalSigma]0`Nn`\[CapitalKappa]i0b, 
    s`f5`o2`\[CapitalSigma]0`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f5`o2`\[CapitalSigma]0`\[CapitalXi]0`\[CapitalKappa]i0}}, 
  {{u`f5`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f5`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f5`o3`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f5`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalKappa]ip, 
    u`f5`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Eta], 
    u`f5`o3`\[CapitalSigma]p`\[CapitalSigma]p`\[Pi]i0, 
    u`f5`o3`\[CapitalSigma]p`\[CapitalSigma]p`etas, 
    u`f5`o3`\[CapitalSigma]p`uuu`\[CapitalKappa]im}, {}, 
   {s`f5`o3`\[CapitalSigma]p`uuu`\[CapitalKappa]im, 
    s`f5`o3`\[CapitalSigma]p`\[CapitalXi]0`\[CapitalKappa]ip}}, 
  {{u`f5`o4`Np`Np`\[Eta], u`f5`o4`Np`Np`\[Pi]i0, u`f5`o4`Np`Np`etas, 
    u`f5`o4`Np`Nn`\[Pi]ip, u`f5`o4`Np`Np`\[Eta], u`f5`o4`Np`Np`\[Pi]i0, 
    u`f5`o4`Np`Np`etas, u`f5`o4`Np`uuu`\[Pi]im}, 
   {d`f5`o4`Np`uuu`\[Pi]im, d`f5`o4`Np`Nn`\[Pi]ip}, {}}, 
  {{u`f5`o5`Nn`ddd`\[Pi]ip, u`f5`o5`Nn`Np`\[Pi]im}, 
   {d`f5`o5`Nn`Np`\[Pi]im, d`f5`o5`Nn`Nn`\[Eta], d`f5`o5`Nn`Nn`\[Pi]i0, 
    d`f5`o5`Nn`Nn`etas, d`f5`o5`Nn`ddd`\[Pi]ip, d`f5`o5`Nn`Nn`\[Eta], 
    d`f5`o5`Nn`Nn`\[Pi]i0, d`f5`o5`Nn`Nn`etas}, {}}, 
  {{}, {d`f5`o6`\[CapitalXi]m`sss`\[CapitalKappa]i0, 
    d`f5`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalKappa]i0b}, 
   {s`f5`o6`\[CapitalXi]m`\[CapitalSigma]m`\[CapitalKappa]i0b, 
    s`f5`o6`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f5`o6`\[CapitalXi]m`\[CapitalXi]m`etas, 
    s`f5`o6`\[CapitalXi]m`sss`\[CapitalKappa]i0, 
    s`f5`o6`\[CapitalXi]m`\[CapitalXi]m`\[Eta], 
    s`f5`o6`\[CapitalXi]m`\[CapitalXi]m`etas}}, 
  {{u`f5`o7`\[CapitalXi]0`sss`\[CapitalKappa]ip, 
    u`f5`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalKappa]im}, {}, 
   {s`f5`o7`\[CapitalXi]0`\[CapitalSigma]p`\[CapitalKappa]im, 
    s`f5`o7`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f5`o7`\[CapitalXi]0`\[CapitalXi]0`etas, 
    s`f5`o7`\[CapitalXi]0`sss`\[CapitalKappa]ip, 
    s`f5`o7`\[CapitalXi]0`\[CapitalXi]0`\[Eta], 
    s`f5`o7`\[CapitalXi]0`\[CapitalXi]0`etas}}, 
  {{u`f5`o8`\[CapitalLambda]`\[CapitalSigma]m`\[Pi]ip, 
    u`f5`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalKappa]ip, 
    u`f5`o8`\[CapitalLambda]`\[CapitalSigma]p`\[Pi]im, 
    u`f5`o8`\[CapitalLambda]`Np`\[CapitalKappa]im}, 
   {d`f5`o8`\[CapitalLambda]`\[CapitalSigma]p`\[Pi]im, 
    d`f5`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalKappa]i0, 
    d`f5`o8`\[CapitalLambda]`\[CapitalSigma]m`\[Pi]ip, 
    d`f5`o8`\[CapitalLambda]`Nn`\[CapitalKappa]i0b}, 
   {s`f5`o8`\[CapitalLambda]`Np`\[CapitalKappa]im, 
    s`f5`o8`\[CapitalLambda]`Nn`\[CapitalKappa]i0b, 
    s`f5`o8`\[CapitalLambda]`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f5`o8`\[CapitalLambda]`\[CapitalXi]0`\[CapitalKappa]i0}}}, 
 {{{}, {d`f6`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f6`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f6`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f6`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    d`f6`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f6`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f6`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f6`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b}, 
   {s`f6`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    s`f6`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0}}, 
  {{u`f6`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    u`f6`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    u`f6`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f6`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im}, 
   {d`f6`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    d`f6`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    d`f6`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f6`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b}, 
   {s`f6`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    s`f6`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    s`f6`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f6`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0}}, 
  {{u`f6`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f6`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f6`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f6`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    u`f6`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f6`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f6`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f6`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im}, {}, 
   {s`f6`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    s`f6`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip}}, 
  {{u`f6`o4`Np`\[CapitalDelta]p`\[Pi]i0, u`f6`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    u`f6`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f6`o4`Np`\[CapitalDelta]pp`\[Pi]im}, 
   {d`f6`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    d`f6`o4`Np`\[CapitalDelta]0`\[Pi]ip}, {}}, 
  {{u`f6`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    u`f6`o5`Nn`\[CapitalDelta]p`\[Pi]im}, 
   {d`f6`o5`Nn`\[CapitalDelta]p`\[Pi]im, d`f6`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f6`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    d`f6`o5`Nn`\[CapitalDelta]0`\[Pi]i0}, {}}, 
  {{}, {d`f6`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    d`f6`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b}, 
   {s`f6`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    s`f6`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f6`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f6`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f6`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f6`o6`\[CapitalXi]m`\[CapitalXi]sm`etas}}, 
  {{u`f6`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    u`f6`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im}, {}, 
   {s`f6`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    s`f6`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f6`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f6`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f6`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f6`o7`\[CapitalXi]0`\[CapitalXi]s0`etas}}, 
  {{u`f6`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    u`f6`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    u`f6`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im}, 
   {d`f6`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    d`f6`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    d`f6`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip}, 
   {s`f6`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f6`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0}}}, 
 {{{}, {d`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    d`f7`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b}, 
   {s`f7`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    s`f7`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    s`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    s`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    s`f7`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas}}, 
  {{u`f7`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f7`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    u`f7`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f7`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    u`f7`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    u`f7`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b}, 
   {d`f7`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f7`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    d`f7`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f7`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    d`f7`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    d`f7`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im}, 
   {s`f7`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f7`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f7`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f7`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f7`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    s`f7`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im}}, 
  {{u`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    u`f7`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im}, {}, 
   {s`f7`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    s`f7`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    s`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    s`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    s`f7`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas}}, 
  {{u`f7`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f7`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    u`f7`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f7`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    u`f7`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    u`f7`o4`Np`\[CapitalDelta]pp`\[Pi]im}, 
   {d`f7`o4`Np`\[CapitalDelta]0`\[Pi]ip, d`f7`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    d`f7`o4`Np`\[CapitalDelta]p`\[Pi]i0}, {}}, 
  {{u`f7`o5`Nn`\[CapitalDelta]p`\[Pi]im, u`f7`o5`Nn`\[CapitalDelta]p`\[Pi]im, 
    u`f7`o5`Nn`\[CapitalDelta]0`\[Pi]i0}, 
   {d`f7`o5`Nn`\[CapitalDelta]m`\[Pi]ip, d`f7`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f7`o5`Nn`\[CapitalDelta]m`\[Pi]ip, d`f7`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f7`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    d`f7`o5`Nn`\[CapitalDelta]p`\[Pi]im}, {}}, 
  {{}, {d`f7`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    d`f7`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    d`f7`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    d`f7`o6`\[CapitalXi]m`\[CapitalXi]sm`etas}, 
   {s`f7`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f7`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f7`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f7`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f7`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f7`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f7`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f7`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b}}, 
  {{u`f7`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    u`f7`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    u`f7`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    u`f7`o7`\[CapitalXi]0`\[CapitalXi]s0`etas}, {}, 
   {s`f7`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f7`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f7`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f7`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f7`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f7`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f7`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f7`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im}}, 
  {{u`f7`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    u`f7`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    u`f7`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0}, 
   {d`f7`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    d`f7`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    d`f7`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip}, 
   {s`f7`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f7`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f7`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f7`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f7`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    s`f7`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im}}}, 
 {{{}, {d`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    d`f8`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b}, 
   {s`f8`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    s`f8`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    s`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    s`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    s`f8`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas}}, 
  {{u`f8`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f8`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    u`f8`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f8`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    u`f8`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    u`f8`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b}, 
   {d`f8`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f8`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    d`f8`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f8`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    d`f8`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    d`f8`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im}, 
   {s`f8`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f8`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f8`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f8`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f8`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    s`f8`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im}}, 
  {{u`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    u`f8`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im}, {}, 
   {s`f8`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    s`f8`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    s`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    s`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    s`f8`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas}}, 
  {{u`f8`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f8`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    u`f8`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f8`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    u`f8`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    u`f8`o4`Np`\[CapitalDelta]pp`\[Pi]im}, 
   {d`f8`o4`Np`\[CapitalDelta]0`\[Pi]ip, d`f8`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    d`f8`o4`Np`\[CapitalDelta]p`\[Pi]i0}, {}}, 
  {{u`f8`o5`Nn`\[CapitalDelta]p`\[Pi]im, u`f8`o5`Nn`\[CapitalDelta]p`\[Pi]im, 
    u`f8`o5`Nn`\[CapitalDelta]0`\[Pi]i0}, 
   {d`f8`o5`Nn`\[CapitalDelta]m`\[Pi]ip, d`f8`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f8`o5`Nn`\[CapitalDelta]m`\[Pi]ip, d`f8`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f8`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    d`f8`o5`Nn`\[CapitalDelta]p`\[Pi]im}, {}}, 
  {{}, {d`f8`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    d`f8`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    d`f8`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    d`f8`o6`\[CapitalXi]m`\[CapitalXi]sm`etas}, 
   {s`f8`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f8`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f8`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f8`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f8`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f8`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f8`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f8`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b}}, 
  {{u`f8`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    u`f8`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    u`f8`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    u`f8`o7`\[CapitalXi]0`\[CapitalXi]s0`etas}, {}, 
   {s`f8`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f8`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f8`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f8`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f8`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f8`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f8`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f8`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im}}, 
  {{u`f8`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    u`f8`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    u`f8`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0}, 
   {d`f8`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    d`f8`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    d`f8`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip}, 
   {s`f8`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f8`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f8`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f8`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    s`f8`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    s`f8`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im}}}, 
 {{{}, {d`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[Eta], 
    d`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]i0, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`etas, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalDelta]m`ddd`\[CapitalKappa]i0b, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[Eta], 
    d`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]i0, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`etas, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalDelta]m`ddd`\[CapitalKappa]i0b, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]i0, 
    d`f9`o1`\[CapitalSigma]m`\[CapitalDelta]m`ddd`\[CapitalKappa]i0b}, 
   {s`f9`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]i0, 
    s`f9`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]i0, 
    s`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[Eta], 
    s`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]i0, 
    s`f9`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[CapitalSigma]m`etas}}, 
  {{u`f9`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]im, 
    u`f9`o2`\[CapitalSigma]0`\[CapitalDelta]p`Np`\[CapitalKappa]im, 
    u`f9`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]im, 
    u`f9`o2`\[CapitalSigma]0`\[CapitalDelta]p`Np`\[CapitalKappa]im, 
    u`f9`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]i0, 
    u`f9`o2`\[CapitalSigma]0`\[CapitalDelta]0`Nn`\[CapitalKappa]i0b}, 
   {d`f9`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]ip, 
    d`f9`o2`\[CapitalSigma]0`\[CapitalDelta]0`Nn`\[CapitalKappa]i0b, 
    d`f9`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]ip, 
    d`f9`o2`\[CapitalSigma]0`\[CapitalDelta]0`Nn`\[CapitalKappa]i0b, 
    d`f9`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]ip, 
    d`f9`o2`\[CapitalSigma]0`\[CapitalDelta]p`Np`\[CapitalKappa]im}, 
   {s`f9`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f9`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f9`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f9`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f9`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]ip, 
    s`f9`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]im}}, 
  {{u`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`\[Eta], 
    u`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]i0, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`etas, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalDelta]pp`uuu`\[CapitalKappa]im, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`\[Eta], 
    u`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]i0, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`etas, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalDelta]pp`uuu`\[CapitalKappa]im, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]ip, 
    u`f9`o3`\[CapitalSigma]p`\[CapitalDelta]pp`uuu`\[CapitalKappa]im}, {}, 
   {s`f9`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]ip, 
    s`f9`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]ip, 
    s`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`\[Eta], 
    s`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]i0, 
    s`f9`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[CapitalSigma]p`etas}}, 
  {{u`f9`o4`Np`\[CapitalDelta]p`Np`\[Pi]i0, 
    u`f9`o4`Np`\[CapitalDelta]pp`uuu`\[Pi]im, 
    u`f9`o4`Np`\[CapitalDelta]p`Np`\[Pi]i0, 
    u`f9`o4`Np`\[CapitalDelta]pp`uuu`\[Pi]im, 
    u`f9`o4`Np`\[CapitalDelta]0`Nn`\[Pi]ip, 
    u`f9`o4`Np`\[CapitalDelta]pp`uuu`\[Pi]im}, 
   {d`f9`o4`Np`\[CapitalDelta]0`Nn`\[Pi]ip, 
    d`f9`o4`Np`\[CapitalDelta]0`Nn`\[Pi]ip, 
    d`f9`o4`Np`\[CapitalDelta]p`Np`\[Pi]i0}, {}}, 
  {{u`f9`o5`Nn`\[CapitalDelta]p`Np`\[Pi]im, 
    u`f9`o5`Nn`\[CapitalDelta]p`Np`\[Pi]im, 
    u`f9`o5`Nn`\[CapitalDelta]0`Nn`\[Pi]i0}, 
   {d`f9`o5`Nn`\[CapitalDelta]m`ddd`\[Pi]ip, 
    d`f9`o5`Nn`\[CapitalDelta]0`Nn`\[Pi]i0, 
    d`f9`o5`Nn`\[CapitalDelta]m`ddd`\[Pi]ip, 
    d`f9`o5`Nn`\[CapitalDelta]0`Nn`\[Pi]i0, 
    d`f9`o5`Nn`\[CapitalDelta]m`ddd`\[Pi]ip, 
    d`f9`o5`Nn`\[CapitalDelta]p`Np`\[Pi]im}, {}}, 
  {{}, 
   {d`f9`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[CapitalKappa]i\
0b, 
    d`f9`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[CapitalKappa]i\
0b, d`f9`o6`\[CapitalXi]m`\[CapitalXi]sm`\[CapitalXi]m`\[Eta], 
    d`f9`o6`\[CapitalXi]m`\[CapitalXi]sm`\[CapitalXi]m`etas}, 
   {s`f9`o6`\[CapitalXi]m`\[CapitalOmega]m`sss`\[CapitalKappa]i0, 
    s`f9`o6`\[CapitalXi]m`\[CapitalXi]sm`\[CapitalXi]m`\[Eta], 
    s`f9`o6`\[CapitalXi]m`\[CapitalXi]sm`\[CapitalXi]m`etas, 
    s`f9`o6`\[CapitalXi]m`\[CapitalOmega]m`sss`\[CapitalKappa]i0, 
    s`f9`o6`\[CapitalXi]m`\[CapitalXi]sm`\[CapitalXi]m`\[Eta], 
    s`f9`o6`\[CapitalXi]m`\[CapitalXi]sm`\[CapitalXi]m`etas, 
    s`f9`o6`\[CapitalXi]m`\[CapitalOmega]m`sss`\[CapitalKappa]i0, s`f9`o6`\
\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalSigma]m`\[CapitalKappa]i0b}}, 
  {{u`f9`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalSigma]p`\[CapitalKappa]i\
m, 
    u`f9`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalSigma]p`\[CapitalKappa]im\
, u`f9`o7`\[CapitalXi]0`\[CapitalXi]s0`\[CapitalXi]0`\[Eta], 
    u`f9`o7`\[CapitalXi]0`\[CapitalXi]s0`\[CapitalXi]0`etas}, {}, 
   {s`f9`o7`\[CapitalXi]0`\[CapitalOmega]m`sss`\[CapitalKappa]ip, 
    s`f9`o7`\[CapitalXi]0`\[CapitalXi]s0`\[CapitalXi]0`\[Eta], 
    s`f9`o7`\[CapitalXi]0`\[CapitalXi]s0`\[CapitalXi]0`etas, 
    s`f9`o7`\[CapitalXi]0`\[CapitalOmega]m`sss`\[CapitalKappa]ip, 
    s`f9`o7`\[CapitalXi]0`\[CapitalXi]s0`\[CapitalXi]0`\[Eta], 
    s`f9`o7`\[CapitalXi]0`\[CapitalXi]s0`\[CapitalXi]0`etas, 
    s`f9`o7`\[CapitalXi]0`\[CapitalOmega]m`sss`\[CapitalKappa]ip, s`f9`o7`\
\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalSigma]p`\[CapitalKappa]im}}, 
  {{u`f9`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]im, 
    u`f9`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]im, 
    u`f9`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]i0}, 
   {d`f9`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]ip, 
    d`f9`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]ip, 
    d`f9`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]ip}, 
   {s`f9`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f9`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f9`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalXi]m`\[CapitalKappa]ip, 
    s`f9`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalXi]0`\[CapitalKappa]i0, 
    s`f9`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[CapitalSigma]m`\[Pi]ip, 
    s`f9`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[CapitalSigma]p`\[Pi]im}}}, 
 {{{}, {d`f10`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f10`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f10`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f10`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    d`f10`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f10`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f10`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f10`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b}, 
   {s`f10`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    s`f10`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0}}, 
  {{u`f10`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    u`f10`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    u`f10`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f10`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im}, 
   {d`f10`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    d`f10`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    d`f10`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f10`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b}, 
   {s`f10`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    s`f10`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    s`f10`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f10`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0}}, 
  {{u`f10`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f10`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f10`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f10`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    u`f10`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f10`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f10`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f10`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im}, {}, 
   {s`f10`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    s`f10`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip}}, 
  {{u`f10`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f10`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    u`f10`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f10`o4`Np`\[CapitalDelta]pp`\[Pi]im}, 
   {d`f10`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    d`f10`o4`Np`\[CapitalDelta]0`\[Pi]ip}, {}}, 
  {{u`f10`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    u`f10`o5`Nn`\[CapitalDelta]p`\[Pi]im}, 
   {d`f10`o5`Nn`\[CapitalDelta]p`\[Pi]im, 
    d`f10`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f10`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    d`f10`o5`Nn`\[CapitalDelta]0`\[Pi]i0}, {}}, 
  {{}, {d`f10`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    d`f10`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b}, 
   {s`f10`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    s`f10`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f10`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f10`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f10`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f10`o6`\[CapitalXi]m`\[CapitalXi]sm`etas}}, 
  {{u`f10`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    u`f10`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im}, {}, 
   {s`f10`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    s`f10`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f10`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f10`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f10`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f10`o7`\[CapitalXi]0`\[CapitalXi]s0`etas}}, 
  {{u`f10`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    u`f10`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    u`f10`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im}, 
   {d`f10`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    d`f10`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    d`f10`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip}, 
   {s`f10`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f10`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0}}}, 
 {{{}, {d`f11`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f11`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f11`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f11`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0, 
    d`f11`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Eta], 
    d`f11`o1`\[CapitalSigma]m`\[CapitalSigma]sm`\[Pi]i0, 
    d`f11`o1`\[CapitalSigma]m`\[CapitalSigma]sm`etas, 
    d`f11`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b}, 
   {s`f11`o1`\[CapitalSigma]m`\[CapitalDelta]m`\[CapitalKappa]i0b, 
    s`f11`o1`\[CapitalSigma]m`\[CapitalXi]sm`\[CapitalKappa]i0}}, 
  {{u`f11`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    u`f11`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    u`f11`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    u`f11`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im}, 
   {d`f11`o2`\[CapitalSigma]0`\[CapitalSigma]sp`\[Pi]im, 
    d`f11`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0, 
    d`f11`o2`\[CapitalSigma]0`\[CapitalSigma]sm`\[Pi]ip, 
    d`f11`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b}, 
   {s`f11`o2`\[CapitalSigma]0`\[CapitalDelta]p`\[CapitalKappa]im, 
    s`f11`o2`\[CapitalSigma]0`\[CapitalDelta]0`\[CapitalKappa]i0b, 
    s`f11`o2`\[CapitalSigma]0`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f11`o2`\[CapitalSigma]0`\[CapitalXi]s0`\[CapitalKappa]i0}}, 
  {{u`f11`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f11`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f11`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f11`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip, 
    u`f11`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Eta], 
    u`f11`o3`\[CapitalSigma]p`\[CapitalSigma]sp`\[Pi]i0, 
    u`f11`o3`\[CapitalSigma]p`\[CapitalSigma]sp`etas, 
    u`f11`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im}, {}, 
   {s`f11`o3`\[CapitalSigma]p`\[CapitalDelta]pp`\[CapitalKappa]im, 
    s`f11`o3`\[CapitalSigma]p`\[CapitalXi]s0`\[CapitalKappa]ip}}, 
  {{u`f11`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f11`o4`Np`\[CapitalDelta]0`\[Pi]ip, 
    u`f11`o4`Np`\[CapitalDelta]p`\[Pi]i0, 
    u`f11`o4`Np`\[CapitalDelta]pp`\[Pi]im}, 
   {d`f11`o4`Np`\[CapitalDelta]pp`\[Pi]im, 
    d`f11`o4`Np`\[CapitalDelta]0`\[Pi]ip}, {}}, 
  {{u`f11`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    u`f11`o5`Nn`\[CapitalDelta]p`\[Pi]im}, 
   {d`f11`o5`Nn`\[CapitalDelta]p`\[Pi]im, 
    d`f11`o5`Nn`\[CapitalDelta]0`\[Pi]i0, 
    d`f11`o5`Nn`\[CapitalDelta]m`\[Pi]ip, 
    d`f11`o5`Nn`\[CapitalDelta]0`\[Pi]i0}, {}}, 
  {{}, {d`f11`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    d`f11`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b}, 
   {s`f11`o6`\[CapitalXi]m`\[CapitalSigma]sm`\[CapitalKappa]i0b, 
    s`f11`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f11`o6`\[CapitalXi]m`\[CapitalXi]sm`etas, 
    s`f11`o6`\[CapitalXi]m`\[CapitalOmega]m`\[CapitalKappa]i0, 
    s`f11`o6`\[CapitalXi]m`\[CapitalXi]sm`\[Eta], 
    s`f11`o6`\[CapitalXi]m`\[CapitalXi]sm`etas}}, 
  {{u`f11`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    u`f11`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im}, {}, 
   {s`f11`o7`\[CapitalXi]0`\[CapitalSigma]sp`\[CapitalKappa]im, 
    s`f11`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f11`o7`\[CapitalXi]0`\[CapitalXi]s0`etas, 
    s`f11`o7`\[CapitalXi]0`\[CapitalOmega]m`\[CapitalKappa]ip, 
    s`f11`o7`\[CapitalXi]0`\[CapitalXi]s0`\[Eta], 
    s`f11`o7`\[CapitalXi]0`\[CapitalXi]s0`etas}}, 
  {{u`f11`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip, 
    u`f11`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    u`f11`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im}, 
   {d`f11`o8`\[CapitalLambda]`\[CapitalSigma]sp`\[Pi]im, 
    d`f11`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0, 
    d`f11`o8`\[CapitalLambda]`\[CapitalSigma]sm`\[Pi]ip}, 
   {s`f11`o8`\[CapitalLambda]`\[CapitalXi]sm`\[CapitalKappa]ip, 
    s`f11`o8`\[CapitalLambda]`\[CapitalXi]s0`\[CapitalKappa]i0}}}}
